### ISSUE TITLE
Option to skip utf-8 check

### ISSUE THREAD

**Issue by Mesteery** [websockets/ws#1924] opened 2021-08-01 13:57 UTC
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I was wondering if it would be interesting to have an option (disabled by default) to skip the UTF-8 check. This would give a slight performance gain in my opinion. (Only for the client)

**Comment by lpinca** [comment] 2021-08-01 18:44
I'm -1 because it is mandatory per specification and skipping it might lead to unexpected behavior. See https://github.com/websockets/ws/issues/1868.

**Comment by Mesteery** [comment] 2021-08-01 18:57
Even if the utf8 check is voluntarily disabled because the developer is sure of the origin and the encoding?

**Comment by lpinca** [comment] 2021-08-01 19:17
The spec doesn't say anything about that. You might trust a sever but I don't see a real need for the option. `utf-8-validate` is already pretty fast and I'll make it use https://github.com/simdutf/simdutf soon so the overhead will be insignificant.

**Comment by lpinca** [comment] 2021-08-01 19:31
Usually an application does not open thousands of WebSocket connection to the same trusted server or set of servers which is the only scenario I can think of where the option would be useful.

**Comment by Mesteery** [comment] 2021-08-01 19:45
Indeed, but for example, a bot, which obviously trusts the server, can receive a lot of messages, and can also have many connections.

**Comment by lpinca** [comment] 2021-08-01 19:49
I'm not sure I understand, what would that bot do?

**Comment by Mesteery** [comment] 2021-08-01 19:50
Un bot Discord par exemple.

**Comment by Mesteery** [comment] 2021-08-01 19:50
A Discord bot for example.

**Comment by lpinca** [comment] 2021-08-01 19:53
I don't know how a discord bot works but wouldn't it open a single (client) connection to a server? Why would it need more?

**Comment by Mesteery** [comment] 2021-08-01 20:04
When a Discord bot is on a large number of guilds (> 1000), we use the "sharding", this system allows to "divide" the bot in several parts, each one takes care of a chunk of guilds, each part is independent and has its own websocket connection.

https://discord.com/developers/docs/topics/gateway#sharding

**Comment by lpinca** [comment] 2021-08-02 05:04
Ok but it seems an edge case and even if there is no limit I think the number of shards is usually in the order or tens?

**Comment by Mesteery** [comment] 2021-08-02 08:26
It can start from a few shards up to several thousands for big bots.

**Comment by lpinca** [comment] 2021-08-02 08:32
Adding the option is easy but I want it to meet a real need/demand. The same argument made here for the client can also be done for the server if clients are trusted. If the option is added for the client, it should also be added for the server.

I am personally not interested but let's keep this open for a few days to see if other people are interested in having this feature.

**Comment by lpinca** [comment] 2021-08-02 08:35
Anyway does a shard run in its own process or do shards share the same process?

**Comment by Mesteery** [comment] 2021-08-02 08:55
In its own process.

**Closed** 2021-08-11 13:48 UTC
