### ISSUE TITLE
can't inherit onopen method

### ISSUE THREAD

**Issue by Cinux-Chosan** [websockets/ws#1404] opened 2018-06-24 07:22 UTC
#### Description

In my code, I extend the `WebSocket` from 'ws':

```ts
import WebSocket from 'ws';
   ...
export default class MyWS extends WebSocket {
    private msgQueue: any [] = [];
    constructor(url, opt?) {
        super(url, opt);
    }
    onopen() {
        this.flushMsgQueue();
    }
   ...
}
```

Then I create an instance of MyWS with `new` operator and the given address and what I  expected is the `onopen` method will be invoked once, but actually, never;

I feel it very strange util I see [this](https://github.com/websockets/ws/blob/307be7a81ee1c08cbd1e2acf2ea98fbf26ae390d/lib/websocket.js#L366);

So I have to use the code below instead:

```ts
import WebSocket from 'ws';
   ...
export default class MyWS extends WebSocket {
    private msgQueue: any [] = [];
    constructor(url, opt?) {
        super(url, opt);
        this.onopen = function (){
            this.flushMsgQueue();
        }
    }
   ...
```

But I don't think this is a good solution.

**Comment by lpinca** [comment] 2018-06-24 07:59
You are overriding `onopen` so that's expected. Instead of overriding it, use this:

```js
class MyWS extends WebSocket {
    private msgQueue: any [] = [];
    constructor(url, opt?) {
        super(url, opt);
    }
}

const ws = new MyWS(url);
ws.onopen = function () {
  this.flushMsgQueue();
};
```

**Comment by lpinca** [comment] 2018-06-24 11:31
Yes in that case you can set `onopen` in the constructor like you did:

```js
function onopen() {
  this.flushMsgQueue();
}

class MyWS extends WebSocket {
    private msgQueue: any [] = [];
    constructor(url, opt?) {
      super(url, opt);
      this.onopen = onopen;
    }
}

const ws = new MyWS(url);
```

This is not bug, it works as intended, if you try to extend the native `WebSocket` object in the browser you get the same behavior.

**Comment by Cinux-Chosan** [comment] 2018-06-24 11:39
@lpinca  Ok, thanks a lot!   (*￣︶￣)

**Comment by lpinca** [comment] 2018-06-24 12:51
Closing, discussion can continue if needed.

**Closed by lpinca** 2018-06-24 12:51 UTC
