### ISSUE TITLE
handleUpgrade() and undefined upgrade header

### ISSUE THREAD

**Issue by FranckFreiburger** [websockets/ws#1838] opened 2021-01-28 19:21 UTC
https://github.com/websockets/ws/blob/2789887c4c3769721c371a0edf3caa6c6933f114/lib/websocket-server.js#L193

`req.headers.upgrade` may be undefined, that will raise `TypeError: Cannot read property 'toLowerCase' of undefined`

**Comment by lpinca** [comment] 2021-01-28 19:35
It can only happen if the `req` argument was not an upgrade request. `wss.handleUpgrade()` must be called from the listener of the `'upgrade'` event.

```js
httpServer.on('upgrade', function(req, socket, head) {
  // Here `req.headers.upgrade` cannot be `undefined`, otherwise there is a bug in Node.js.
  wss.handleUpgrade(req, socket, head, callback);
});
```

**Comment by lpinca** [comment] 2021-01-28 19:38
Please fill the issue template, it's there for a reason. Also, if you can, please write a test case using only `ws` to reproduce the issue.

**Comment by FranckFreiburger** [comment] 2021-01-28 19:44
Sorry for that, I created the issue from the code view (Reference in new issue), no model was requested.

**Comment by FranckFreiburger** [comment] 2021-01-28 19:47
In fact I am using `handleUpgrade()` in a get() handler of express :

```
app.get('/myWs', (req, res) => {
  wss.handleUpgrade(req, req.socket, [], handler);
})
```

Everything seems to work properly except for non-ws requests

**Comment by lpinca** [comment] 2021-01-28 19:50
Yes, you can't do that, it doesn't make sense. The HTTP parser is still attached to the `http.IncomingMessage` object (`req`) in your example.

**Comment by FranckFreiburger** [comment] 2021-01-28 19:55
Thanks, however, I don't understand properly why it can't work

**Comment by lpinca** [comment] 2021-01-28 20:05
Because upgrade requests are used to upgrade to another protocol not HTTP and are handled differently by Node.js. When you use `app.get()` you are handling a request received via

```js
httpServer.on('request', function (req, res) {});
```

Upgrade requests are handled with

```js
httpServer.on('upgrade', function (req, socket, head) {});
```

and the socket in this case is freed.

In your example the socket is still piped to the HTTP parser so it will not work when the client writes something using a different protocol.

**Comment by FranckFreiburger** [comment] 2021-01-28 20:08
ok I see, thanks !

**Comment by lpinca** [comment] 2021-01-28 20:30
I'm closing this as answered. Discussion can continue if needed.

**Closed by lpinca** 2021-01-28 20:30 UTC
