### ISSUE TITLE
Socket sometimes stuck at onopen with no error

### ISSUE THREAD

**Issue by benzmuircroft** [websockets/ws#2154] opened 2023-07-26 14:23 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I have been putting this off for a long time as it happens randomly but when it does happen it happens many times in a row and the simplest solution is to leave the socket stuck at 'onopen' and wait for about 5-10 minutes until the socket comes alive on it's own.

Page refreshing does not help. I see this happening randomly 1-3 times per month. I've seen it across projects, various versions of Ubuntu and Node. Here's an example of my code below, but, please note that I have older versions of my code using ws that was not using noServer and I saw this problem back then also (I just thought it may have been a problem with the server at the time, but since then I've moved servers, operating systems, even seen this inside docker). also please note that I have managed to capture a socket when it is stuck (please see 'Attachment'). Thank you.

```
socketServer = G.hardHttps.createServer({
    key:          G.pem.key,
    cert:         G.pem.cert,
    ca:           [G.pem.ca],
    requestCert:  false
  });
  socketServer.on("close", function (e) {
    fs.writeFile(path.join(__dirname, '..', '..', 'BUGS', (new Date().toString().split(' GMT+')[0]) + 'https-close'), e.stack, 'utf-8', () => {});
    G.listen(52367);
  });
  socketServer.on("error", function (e) {
    console.log(e);
    fs.writeFile(path.join(__dirname, '..', '..', 'BUGS', (new Date().toString().split(' GMT+')[0]) + 'https-error'), e.stack, 'utf-8', () => {});
  });
  socketServer.on("upgrade", function (req, socket, head) {
    let ip = req.headers['x-forwarded-for'] || req.connection.remoteAddress || req.socket.remoteAddress || req.connection.socket.remoteAddress;
    if (ip == G.developer) {
      // always allow admin!
    }
    else if (G.BAN.ips[ip]) {
      socket._tlsOptions.server.BANNED = true;
    }
    for (ip in G.BAN.ips) { if (G.BAN.ips[ip].t < (+new Date())) { delete G.BAN.ips[ip]; } }//delete day old
    G.SS.handleUpgrade(req, socket, head, function done(ws) {//https://github.com/websockets/ws/issues/1678
      G.SS.emit('connection', ws, req);
    });
  });
  socketServer.listen(port);


G.SS = new WebSocketServer({
      noServer: true,
      verifyClient: function (info, cb) {
          cb(true);
      }
});

G.SS.on('connection', function (main, req) {
    let s = { soc: main }; 
    function onopen() {
        console.log('onopen');
        s[m].soc.send('hello');
        }
    s[m].soc.on('open', onopen);
});

```

### ws version

8.13.0

### Node.js Version

v18.12.1

### System

System:
    OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (1) x64 Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
    Memory: 213.90 MB / 442.73 MB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

Always get passed 'ononpen'

### Actual result

The socket connects and is able to send it's message 99% of the time. But occasionally it hangs for around 5-10 minutes at 'onopen' before it wakes up and sends the message. Restarting the node app has no effect until suddenly it goes back to normal behavior. Page refreshing or moving to a different tab has no effect. Please see the attachment that shows the socket when it is in this odd state. Also, The connection does not timeout as 'onopen' does even fire in the browser and the server!

### Attachments

[onopen.json.zip](https://github.com/websockets/ws/files/12173556/onopen.json.zip)

**Comment by lpinca** [comment] 2023-07-26 16:22
There is `'open'` event on the server so I'm not sure how this

```js
G.SS.on('connection', function (main, req) {
    let s = { soc: main }; 
    function onopen() {
        console.log('onopen');
        s[m].soc.send('hello');
        }
    s[m].soc.on('open', onopen);
});
```

works. The `'connection'` event is your `'open'` event on the server.

**Comment by lpinca** [comment] 2023-07-26 16:23
See also https://github.com/websockets/ws#how-to-detect-and-close-broken-connections.

**Comment by benzmuircroft** [comment] 2023-07-26 16:29
> There is `'open'` event on the server so I'm not sure how this
> 
> ```js
> G.SS.on('connection', function (main, req) {
>     let s = { soc: main }; 
>     function onopen() {
>         console.log('onopen');
>         s[m].soc.send('hello');
>         }
>     s[m].soc.on('open', onopen);
> });
> ```
> 
> works. The `'connection'` event is your `'open'` event on the server.

Why does the `'open'` event fire if `'connection'` is the `'open'` event?

**Comment by benzmuircroft** [comment] 2023-07-26 16:31
> See also https://github.com/websockets/ws#how-to-detect-and-close-broken-connections.

this happens almost never, but when it does I'd be detecting and closing hundreds to thousands of sockets in the period of time that this occurs.

**Comment by benzmuircroft** [comment] 2023-07-26 16:32
please see the attachment

**Comment by lpinca** [comment] 2023-07-26 16:57
> Why does the `'open'` event fire if `'connection'` is the `'open'` event?

I have no clue. Maybe you are emitting it manually? You can test yourself with this code:

```js
const http = require('http');
const { WebSocketServer, WebSocket } = require('ws');

const server = http.createServer();
const websocketServer = new WebSocketServer({
  noServer: true,
  verifyClient(_, callback) {
    callback(true);
  }
});

server.on('upgrade', function (request, socket, head) {
  websocketServer.handleUpgrade(request, socket, head, function (ws) {
    websocketServer.emit('connection', ws);
  });
});

websocketServer.on('connection', function (ws) {
  console.log('ok');

  ws.on('open', function () {
    console.log('NEVER EMITTED');
  });
});

server.listen(function () {
  const ws = new WebSocket(`ws://localhost:${server.address().port}`);
});
```

> please see the attachment

I did, there is nothing interesting in it. It's just a serialized form of `WebSocket` object.

**Comment by lpinca** [comment] 2023-07-26 17:39
> it still perplexes me as to why occasionally it takes 5-10 minutes for any sockets to get to readyState 1

It does not make sense. The `WebSocket` you receive from the `'connection'` event has `readyState` set to 1 as soon as the the `'connection'` event is emitted unless you delay the `'connection'` event itself.

> At random times, no sockets will get to readyState 1 but if left connected they magically come to life with readyState 1.

This also does not make sense. The `readyState` does not go back to `1`. It can only be `2` or `3` if it is a server `Websocket` and when you read it is not `1`. Make sure you are working with the same `WebSocket` object and not a different one.

**Comment by benzmuircroft** [comment] 2023-07-26 18:02
I agree (this is why I waited so long to open this).

I am removing the open event entirely and I will wait until this seemingly random issue happens again.

As you said, the attachment is just a serialized WebSocket object - what then would be useful to see when it next happens?

**Comment by lpinca** [comment] 2023-07-26 18:24
> what then would be useful to see when it next happens?

Check for example the buffered amount to see if the data is flowing or not.

**Comment by benzmuircroft** [comment] 2023-08-11 16:36
happening again over and over and over for at least 10 minutes ...

onconnected readyState: 1
BUFFERERD AMOUNT: 263

always 263

**Comment by lpinca** [comment] 2023-08-11 16:38
I guess data is not flowing because the other peer is dead without the server noticing.

**Comment by benzmuircroft** [comment] 2023-08-11 16:38
it's chrome! just tried another browser and it's ok!

I think this then is more about the state of the socket on the client side

**Comment by lpinca** [comment] 2023-08-11 16:48
Anyway this example Anyway this is what https://github.com/websockets/ws#how-to-detect-and-close-broken-connections  is exactly for cases like this.

**Comment by benzmuircroft** [comment] 2023-08-11 16:52
I'd be closing thousands of them per user, I have got to fix this issue, users would come at me with pitch forks. It looks like they are starting with readyState: 3 for long periods then after going back to normal. It's been happening for years on many different servers

**Comment by lpinca** [comment] 2023-08-11 16:58
> I'd be closing thousands of them per user

I don't know the details but I'm not sure I understand. Even if a user opens thousands of connections, the above example would only close the unresponsive ones.

 > It looks like they are starting with readyState: 3 for long periods then after going back to normal.

Ready state 3 means closed. Once closed a WebSocket connection cannot go back to 1. A new one (new TCP connection) must be established.

**Comment by benzmuircroft** [comment] 2023-08-11 17:00
each user has 1 connection but it reconnects (by making a new websocket)

**Comment by lpinca** [comment] 2023-08-11 17:02
I don't see the problem then. Why can't you destroy unresponsive connections?

**Comment by benzmuircroft** [comment] 2023-08-11 17:05
because I'd be destroying all of them for 15-20 minutes and the user would think my site's busted and I'd get complaints that I don't know how to fix and it would not get good reviews

**Comment by benzmuircroft** [comment] 2023-08-11 17:06
plus when I want to work on my site but cant get a connection for ages it is frustrating as hell

**Comment by lpinca** [comment] 2023-08-11 17:09
What's the difference from now? When the socket get unresponsive what happens on the client side? The user is stuck no?

If the server cannot accept new connections the issue is different.

**Comment by benzmuircroft** [comment] 2023-08-11 17:20
If I restart the browser it works, but the user isn't going to do that

**Comment by lpinca** [comment] 2023-08-11 17:23
I still don't understand. If you open a new WebSocket on the client does it work? If so why not using an heartbeat system also on the client? You can't send a ping frame but you can use a normal message.

**Comment by benzmuircroft** [comment] 2023-08-11 17:25
no it does not work and I have a heartbeat system already

**Comment by lpinca** [comment] 2023-08-11 17:26
Then I think there is no way you can solve this.

**Comment by benzmuircroft** [comment] 2023-08-11 17:27
I'll eventually find out what is the cause and kill it with a rusty spoon

**Comment by lpinca** [comment] 2023-08-11 17:30
Having unresponsive connection is common, but having the browser block you from opening a new WebSocket is really weird.

**Comment by lpinca** [comment] 2023-08-17 08:32
I'm closing this as answered.

**Closed by lpinca** 2023-08-17 08:32 UTC
