### ISSUE TITLE
Process not exiting when socket connection is closed

### ISSUE THREAD

**Issue by tsbraun1891** [websockets/ws#1851] opened 2021-02-22 18:32 UTC
- [X ] I've searched for any related issues and avoided creating a duplicate
  	Issue.

I’m submitting a…
- [ X] support request

#### Description
My application previously used socket.io, and I am working to replace socket io with ws for communication. I am trying to replicate the behavior present when a socket.io client disconnects using `socket.close()`, where the client application would exit after the connection was closed. Have tried using `socket.terminate()` on the client side when receiving the  close  event,  but this didn’t appear to change the behavior. 

Do you have any insight into what may cause an application to hang after the socket connection has been closed? 

#### Reproducible in:

- version: 7.4.3
- Node.js version(s): 12.19.0
- OS version(s): Windows 10.0.19041

#### Steps to reproduce:
I don’t have a minimal demo to reproduce this, as you would need to clone the jiff repo: https://github.com/multiparty/jiff

#### Expected result:
Client application should exit after disconnecting from server (after  receiving  the  ‘close’ event from server)
https://github.com/multiparty/jiff/tree/ws-testing/demos/sum

#### Actual result:
A client connected to a ws server calls `socket.close()`, receives the `close` event from server, then hangs and the process does not exit.  Both the server and  client log that the client acknowledge/log that the client has disconnected, but the client process does not exit.

**Comment by lpinca** [comment] 2021-02-22 19:01
A timeout? Reconnection? I don't know and can't reproduce:

```
$ cat index.js 
const WebSocket = require('ws')

const ws = new WebSocket('wss://echo.WebSocket.org');

ws.on('open', function() {
  ws.send('foo')
});

ws.on('message', function(message) {
  console.log(message);
  ws.close();
});

ws.on('close', function(code) {
  console.log(code);
});
```

```
$ node index.js 
foo
1005
```

```
$ echo $?
0
```

Try with https://github.com/mafintosh/why-is-node-running using it some time after the `'close'` event is emitted.

**Comment by tsbraun1891** [comment] 2021-02-26 17:06
Thanks for the response, I'll try out why node is running to see if I can get any more information about what's going wrong.  Can you give me some more insight as to how the websocket actually closes its connection? Is that something that just happens under the hood when a client receives the close event?

**Comment by p-flock** [comment] 2021-02-26 17:22
to add some detail, I ran the jiff demo with websockets and probed with why-is-node-running, it seems like the `net.connect()` call in the ws library is keeping the process alive, what I don't understand is why it doesn't seem to be shut down by the `.close()` function. The client receives the 1005 disconnect  code from the server. 
Here is a screenshot of the trace:
<img width="1680" alt="Screen Shot 2021-02-26 at 12 17 38 PM" src="https://user-images.githubusercontent.com/412265/109333267-3c921480-782d-11eb-9511-e8454dd32b09.png">

**Comment by p-flock** [comment] 2021-02-26 17:44
Is it possible the application code is interrupting the closing handshake?

**Comment by lpinca** [comment] 2021-02-26 19:40
No, I don't think so unless you mess with `ws` internals.

I'm pretty sure this is not a `ws` issue but I'm running that demo (sum) now on the `ws-testing` branch. How can I make the server close the client connection?

**Comment by lpinca** [comment] 2021-02-26 20:38
> I'm running that demo (sum) now on the ws-testing branch. How can I make the server close the client connection?

I figured it out.

By running that example I see that [`guardedSocket()`](https://github.com/multiparty/jiff/blob/ws-testing/lib/ext/jiff-client-websockets.js#L251-L269) is called twice so two WebSocket connections are created but only one is closed. You can verify that by applying the following patch

```diff
$ git diff
diff --git a/lib/ext/jiff-client-websockets.js b/lib/ext/jiff-client-websockets.js
index 48bb30cb..c0ae88b5 100644
--- a/lib/ext/jiff-client-websockets.js
+++ b/lib/ext/jiff-client-websockets.js
@@ -251,6 +251,11 @@ const socket = require('../server/socket.js');
     function guardedSocket(jiffClient) {
       // Create plain socket io object which we will wrap in this
       var socket = new WebSocket(jiffClient.hostname)
+      console.log('open');
+
+      socket.on('close', function () {
+        console.log('closed');
+      });
 
       socket.old_disconnect = socket.close;
 

```

This explains why the process does not exit.

**Comment by p-flock** [comment] 2021-02-26 20:51
Thank you very much, we started to suspect we were initiating two connections but had not verified or tracked it down yet. This is super helpful, thanks for spending your time looking into this and helping. Also thanks for working on ws! We've enjoyed using it so far

**Closed** 2021-02-26 22:37 UTC
