### ISSUE TITLE
Dependencies bufferutil and utf-8-validate are listed as devDependencies

### ISSUE THREAD

**Issue by TheLudd** [websockets/ws#659] opened 2016-01-08 15:02 UTC
My app has this library as a child dependency. I can currently not start it since I get errors saying that module `bufferutil` and `utf-8-validate` cannot be found. The errors originate from this module I notice that the two dependencies are listed as devDependencies. Could they be included as regular dependencies?

**Comment by 3rd-Eden** [comment] 2016-01-08 19:23
No, they are dev dependencies, nothing in this library depends directly on it. The error is somewhere in your own code or the library that consumes this library.

Arnout Kazemier

**Comment by janhoogeveen** [comment] 2016-01-08 20:55
For what it's worth, I had the same trouble in my custom version of https://github.com/erikras/react-redux-universal-hot-example and removing everything related to Socket.IO got rid of all the errors. Maybe worth investigating if they have new minor/patch versions released that got automatically updated.

**Comment by TheLudd** [comment] 2016-01-08 22:15
Yes I now understand that the error occurs when browserify is used with this project. It does not handle the try-catch around the non existing dependencies. Is there a good solution for handling this?

**Comment by janhoogeveen** [comment] 2016-01-09 00:37
Check https://github.com/socketio/socket.io-client/issues/933

**Comment by 3rd-Eden** [comment] 2016-01-09 18:47
@TheLudd It's really a bug in browserify for not understanding conditional imports. 

Anyways, i'm going to close this bug for now. If there are concrete fixes that I can do in this module to make bundling easier, feel free to give me a poke.

**Closed by 3rd-Eden** 2016-01-09 18:47 UTC

**Comment by wayofthefuture** [comment] 2017-06-26 17:06
Just installed 3.0.0, can't even get it to build with webpack. Same error.

import WebSocket from 'ws';

This is client-side browser code. Am I not suppose to use the 'ws' lib client-side? Should I use the native browser implementation?

Is this incorrect?
Thanks for your help.

**Comment by 3rd-Eden** [comment] 2017-06-26 17:07
This is a node client, not a front-end library.

**Comment by wayofthefuture** [comment] 2017-06-26 17:08
@3rd-Eden So I should just use native websocket?

**Comment by 3rd-Eden** [comment] 2017-06-26 17:11
Yes

**Comment by wayofthefuture** [comment] 2017-06-26 17:17
Thank you for your time.

**Comment by fabcotech** [comment] 2019-09-10 16:28
I just found a solution.

The problem has been described above : those two libraries are not at all required by `ws` module. So the problem is that some bundlers (mine is rollup) still try to resolve it, and if they do not resolve it, you have a `Cannot find module 'bufferutil'` or similar error at runtime.

My simple solution was simply to create fake modules in my `node_modules` folder.

> mkdir ./node_modules/bufferutil/ && touch ./node_modules/bufferutil/index.js
> mkdir ./node_modules/utf-8-validate/ && touch ./node_modules/utf-8-validate/index.js

**Comment by swissmanu** [comment] 2021-05-15 18:01
for what its worth: with rollup, you can use the [virtual](https://github.com/rollup/plugins/tree/master/packages/virtual) plugin to provide stubs for the two optional peer dependencies of `ws`:

```javascript
import virtual from '@rollup/plugin-virtual';

// rollup.config.js
{
  plugins: [
    virtual({
      bufferutil: '',
      'utf-8-validate': '',
    }),
  ]
}
```

**Comment by sebbean** [comment] 2025-01-05 22:58
ty @swissmanu helped me out!
