### ISSUE TITLE
uncaught exception for TLS protocol version mismatch 

### ISSUE THREAD

**Issue by lagebaue** [websockets/ws#1819] opened 2020-11-30 12:34 UTC
#### Description

Similiar to https://github.com/websockets/ws/issues/1305

no uncaughtException handler exists.

There's multiple issues that report this problem, why is it always handwaved as a non issue, if it's such a simple fix to just check for null?

#### Reproducible in:

- version: 7.4.0
- Node.js version(s): v12.18.3
- OS version(s): Win 7

#### Steps to reproduce:

1. connect to a server that only allows TLSv.1.2 with  `options: { maxVersion "TLSv1.1" }`

#### Expected result:

ideally: throw only the protocol error, but throwing the first error (connection closed) would still be better than an uncaughtException.

#### Actual result:

Throws two errors: connection closed, then protocol error. On second error and uncaughtException happens.

**Comment by lpinca** [comment] 2020-11-30 20:04
> why is it always handwaved as a non issue, if it's such a simple fix to just check for null?

Because it's either a bug in Node.js or user code. Please post some code with no external dependencies to reproduce the issue you are describing.

**Comment by lpinca** [comment] 2020-11-30 20:26
```js
const fs = require('fs');
const https = require('https');

const WebSocket = require('.');

const server = https.createServer({
  cert: fs.readFileSync('./test/fixtures/certificate.pem'),
  key: fs.readFileSync('./test/fixtures/key.pem'),
  minVersion: 'TLSv1.2'
});

const wss = new WebSocket.Server({ server });

server.listen(0, () => {
  const ws = new WebSocket(`wss://localhost:${server.address().port}`, {
    rejectUnauthorized: false,
    maxVersion: 'TLSv1'
  });

  ws.on('error', console.error);
});
```

I get no uncaught exception with Node.js v15.3.0. I will check tomorrow with Node.js v12.

**Comment by lpinca** [comment] 2020-12-01 14:28
Ok, I can reproduce the issue on Node.js v12. The bug is in Node.js. The `'error'` event is emitted more than once on both the socket

```js
const fs = require('fs');
const tls = require('tls');

const server = tls.createServer({
  cert: fs.readFileSync('./certificate.pem'),
  key: fs.readFileSync('./key.pem')
});

server.listen(0, function () {
  const socket = tls.connect({
    port: server.address().port,
    rejectUnauthorized: false
  });

  socket.on('error', console.error);

  socket.on('connect', function () {
    socket.destroy(new Error('Oops'));
  });

  socket.write('hello');
});
```

and the `http.ClientRequest` object

```js
const fs = require('fs');
const https = require('https');

const server = https.createServer({
  cert: fs.readFileSync('./certificate.pem'),
  key: fs.readFileSync('./key.pem'),
  minVersion: 'TLSv1.2'
});

server.listen(0, function () {
  const request = https.get({
    port: server.address().port,
    rejectUnauthorized: false,
    maxVersion: 'TLSv1.1'
  });

  request.on('error', console.error);
});
```

The bug is in `stream.Writable` as demonstrated by the following test case

```js
const { Writable } = require('stream');

const writable = new Writable({
  write(chunk, encoding, callback) {
    process.nextTick(callback, new Error('Write error'));
  },
  autoDestroy: false
});

writable.on('error', console.error);

writable.write('hello');
writable.destroy(new Error('Destroy error'));
```

The good news is that the bug has been fixed in Node.js v14. The bad news is that Node.js v12 is in maintenance mode and bug fixes are no longer accepted.

I'll try to fix the issue in `ws`.

**Comment by lagebaue** [comment] 2020-12-01 15:20
Thanks for the efforts, I'm not using ws, directly but rather through the `mqtt` package and didn't have the time to (successfully) write a succinct test like that (was missing the certs apparently).
For my immediate needs I just added the aforementioned null check in local copy, but will also upgrade to v14 asap.
Let's hope that future Node.js versions are 100% bug free (very likely :)).

**Closed** 2020-12-04 19:57 UTC
