### ISSUE TITLE
Not a bug, don't listen to me :) I'm dumb 

### ISSUE THREAD

**Issue by McFarts** [websockets/ws#519] opened 2015-06-27 06:14 UTC
Line 230 in Receiver.js:
```
 if (typeof handler == 'undefined') this.error('no handler for opcode ' + this.state.opcode, 1002);
```

If you send a binary data as of follows from the CLIENT:
```
var array = new Float32Array(99999);
Socket.send(array, { binary: true, mask: true });
```
To the server, you will get a fatal error (crashes nodejs)

A Fix that I found (wrapping it in try / catch blocks) but only temporarily a better solution is
Line 183 Receiver.js ~
```
/**
 * Start processing a new packet.
 *
 * @api private
 */

Receiver.prototype.processPacket = function (data) {
	try{
  if (this.extensions[PerMessageDeflate.extensionName]) {
    if ((data[0] & 0x30) != 0) {
      this.error('reserved fields (2, 3) must be empty', 1002);
      return;
    }
  } else {
    if ((data[0] & 0x70) != 0) {
      this.error('reserved fields must be empty', 1002);
      return;
    }
  }
  this.state.lastFragment = (data[0] & 0x80) == 0x80;
  this.state.masked = (data[1] & 0x80) == 0x80;
  var compressed = (data[0] & 0x40) == 0x40;
  var opcode = data[0] & 0xf;
  if (opcode === 0) {
    if (compressed) {
      this.error('continuation frame cannot have the Per-message Compressed bits', 1002);
      return;
    }
    // continuation frame
    this.state.fragmentedOperation = true;
    this.state.opcode = this.state.activeFragmentedOperation;
    if (!(this.state.opcode == 1 || this.state.opcode == 2)) {
      this.error('continuation frame cannot follow current opcode', 1002);
      return;
    }
  }
  else {
    if (opcode < 3 && this.state.activeFragmentedOperation != null) {
      this.error('data frames after the initial data frame must have opcode 0', 1002);
      return;
    }
    if (opcode >= 8 && compressed) {
      this.error('control frames cannot have the Per-message Compressed bits', 1002);
      return;
    }
    this.state.compressed = compressed;
    this.state.opcode = opcode;
    if (this.state.lastFragment === false) {
      this.state.fragmentedOperation = true;
      this.state.activeFragmentedOperation = opcode;
    }
    else this.state.fragmentedOperation = false;
  }
  var handler = opcodes[this.state.opcode];
  if (typeof handler == 'undefined') this.error('no handler for opcode ' + this.state.opcode, 1002);
  else {
    handler.start.call(this, data);
  }
	}catch(e){console.log(e)}
	
};
```

**Comment by Deathspike** [comment] 2015-06-27 08:55
I tried to reproduce this. I couldn't. Could you post some test code to reproduce the issue?

**Comment by McFarts** [comment] 2015-06-27 18:02
Hmm. Use this as server.js:
```
var WebSocketServer = require('ws').Server, wss = new WebSocketServer({ port: 9300 });
```

Then, use this as the client to try to connect
```
var numberOfConnections = 5;
 
for (var i = 0; i < numberOfConnections; i++) {
  (function() {
    var ws = new WebSocket('ws://localhost:9300/');
    ws.onopen = function(){
			var buffer = new Float32Array(999);
			
		ws.send(buffer, {binary: true, mask: false}, function() {
        ws.close();
      });
    };
  })();
}
```
Then, boom. Fatal error:
http://i.gyazo.com/ab0f9296e3e82afd7d4b9a54cf45195c.png

**Comment by McFarts** [comment] 2015-06-27 18:17
> I tried to reproduce this. I couldn't. Could you post some test code to reproduce the issue?

I'm dumb. I forgot to add my on handler functions below in the server code.. lol

```
server.on('connection', function(socket) {
  console.log('Got a connection!');
  socket.on('message', function() {
    console.log('Got a message!');
  });
 socket.on('error', function(e) {
  console.log('Error from client: ' + e);
 });
  socket.on('close', function() {
    console.log('Got a close!');
  });
});
```
Thank you!!

**Comment by leoetlino** [comment] 2015-08-04 08:29
Please close the issue if this is not a bug to avoid cluttering this issue tracker.

**Closed** 2015-08-04 21:17 UTC
