### ISSUE TITLE
There may be a memory leak in a weak network environment

### ISSUE THREAD

**Issue by kekeqy** [websockets/ws#1830] opened 2021-01-04 01:26 UTC
- version:7.3.1
- Node.js version(s):v12.20.0
- OS version(s):Linux_x64_3.10.0-1127.18.2.el7.x86_64

I use WS for video streaming.I found a problem.

When the client（browser） network is slow, the server's memory explodes.Memory does not drop when the connection is closed.

Later I changed the policy and dropped the frame appropriately according to bufferedAmount.Memory is no longer exploding.But it will still grow slowly.Memory does not drop after connection is closed.

It is possible that WS has a memory leak in a weak network environment.No memory leak when the network is unblocked.

**Comment by lpinca** [comment] 2021-01-04 06:05
`websocket.bufferedAmount` is not reset after the connection is closed. All the buffered data to write is still there until the `websocket` object is GC'ed.

The value of `websocket.bufferedAmount` is also increased if you write to a `CLOSING` or `CLOSED` `WebSocket`.

**Comment by kekeqy** [comment] 2021-01-04 07:54
After closing the connection, I did not send data.I mean, in a weak network environment, memory will grow slowly.When the connection is closed, it cannot be fully released.Assuming an increase of 100M, only 5M May be released when the connection is closed.

**Comment by lpinca** [comment] 2021-01-04 10:26
Do no use `websocket.bufferedAmount` to monitor memory usage. Use [`process.memoryUsage()`](https://nodejs.org/api/process.html#process_process_memoryusage). Monitor it over a long amount of time like a day and when there are no connections. Ignore the initial values.

**Comment by lpinca** [comment] 2021-01-04 10:48
You can also take heap snapshots with [heapdump](https://github.com/bnoordhuis/node-heapdump) or the [`inspector`](https://nodejs.org/api/inspector.html#inspector_heap_profiler) module and later analyze them to find memory leaks.

**Comment by kekeqy** [comment] 2021-01-05 01:49
> Do not use `websocket.bufferedAmount` to monitor memory usage. Use [`process.memoryUsage()`](https://nodejs.org/api/process.html#process_process_memoryusage). Monitor it over a long amount of time like a few days and when there are no connections. Ignore the initial values.
> 
> Also ensure that you are not keeping references to `WebSocket` objects preventing them from being GC'ed.

I understand that.

**Comment by kekeqy** [comment] 2021-01-05 01:51
> You can also take heap snapshots with [`heapdump`](https://github.com/bnoordhuis/node-heapdump) or the [`inspector`](https://nodejs.org/api/inspector.html#inspector_heap_profiler) module and later analyze them to find memory leaks.
> 
> As is, without a reproducible test case, the issue is not actionable as there is no proof that the memory leak is caused by `ws`.



> You can also take heap snapshots with [`heapdump`](https://github.com/bnoordhuis/node-heapdump) or the [`inspector`](https://nodejs.org/api/inspector.html#inspector_heap_profiler) module and later analyze them to find memory leaks.
> 
> As is, without a reproducible test case, the issue is not actionable as there is no proof that the memory leak is caused by `ws`.

Ok, I'll grab the heap memory snapshot later.

**Comment by kekeqy** [comment] 2021-01-05 09:51
[HeapProfile.zip](https://github.com/websockets/ws/files/5769351/HeapProfile.zip)
It doesn't seem like heap memory has increased that much.However, the value obtained through process.memoryUsage() is larger.

**Comment by lpinca** [comment] 2021-01-05 12:47
From a quick look, by comparing the last two snapshots, I see an increase of `JSArrayBufferData` but it does not seem worrying and related to `ws`. What is `RtmpSession` and `RtmpServer`?

If you suspect that the issue is in `ws` you should test with an app using only `ws` and no other dependencies.

Are you permessage-deflate?

**Comment by kekeqy** [comment] 2021-01-06 00:59
I'm not using permessage-deflate.I'll test it again when there's plenty of time. Thank you for your answer.

**Closed** 2021-01-06 00:59 UTC
