### ISSUE TITLE
Exceptions inside the message handler will break everything silently

### ISSUE THREAD

**Issue by ghost** [websockets/ws#266] opened 2013-11-20 10:32 UTC
I have a ws server so I do as prescribe in the example to handle connections. When I get new connection and register 'message' event handler, if there is any kind of error inside the handler (e.g. new Error('')) the error will be discarded silently and the message handler will not be called anymore.

**Comment by lpinca** [comment] 2016-11-10 08:01
The error should bubble up if not handled.

```js
const WebSocket = require('.');

const wss = new WebSocket.Server({ port: 3000 }, () => {
  const ws = new WebSocket('ws://localhost:3000');
  ws.on('open', () => ws.send('throw'));
});

wss.on('connection', (ws) => {
  ws.on('message', () => {
    throw new Error('damn');
  });
});
```

The above code seems to work as intended. Closing this.

**Closed by lpinca** 2016-11-10 08:01 UTC
