### ISSUE TITLE
Error event called without Close event

### ISSUE THREAD

**Issue by pulviscriptor** [websockets/ws#672] opened 2016-01-17 12:35 UTC
Code i use:
```javascript
var WebSocket = require('ws'); // remove this for browser run
var socket = new WebSocket('ws://1.2.3.4:5/');

socket.onopen = function() {
    console.log('onopen called');
};

socket.onclose = function(event) {
    console.log('onclose called');
};

socket.onerror = function(error) {
    console.log('onerror called');
};
```
- Node.JS v0.12.2 + ws 1.0.1

Result:
```
onerror called
```
- Firefox ESR 38.5.2
- SRWare Iron 46.0.2450.0 (chromium based)
- Internet Explorer 11

Result:
```
onerror called
onclose called
```
I assume change this behavior is very "painful" with so many users of library.
But sometimes <b>ws</b> do call `onerror` and then `onclose`. Is there some "algorithm" when `onclose` called after `onerror` and when not? 
I want to emit `disconnect` events in my library even when connection failed, like browsers do.
I tried to find places in source code, but its too hard for me (for my experience and knowledge).

**Comment by misobytes** [comment] 2016-04-01 23:32
Hi! We're noticing the same behavior using our node.js app.

I can see there is a similar outstanding issue, opened from last year: #505 

According to [https://www.w3.org/TR/websockets/](url) it seems the expected behavior should include the close event:

> If the establish a WebSocket connection algorithm fails, it triggers the fail the WebSocket connection algorithm, which then invokes the close the WebSocket connection algorithm, which then establishes that the WebSocket connection is closed, which fires the close event

I can see in WebSocket.js:
```
var req = httpObj.request(requestOptions);

  req.on('error', function onerror(error) {
    self.emit('error', error);
    cleanupWebsocketResources.call(self, error);
  });
```
... that there is an error listener for the http request responsible for establishing the socket connection.

However, since the ```readyState === WebSocket.CONNECTING``` a close event is intentionally not emitted:

``` var emitClose = this.readyState !== WebSocket.CONNECTING; ```

I'm guessing the above statement exists for a reason. Can anyone explain the rationale behind it?

It would be possible to emit the close event when an error is detected during connection establishment if we:
* Removed the conditional check ```this.readyState !== WebSocket.CONNECTING```.
* Checked the type of error within the request error handler to see if it contains ENOTFOUND or similar. If it does contain such an error then explicitly emit a close event or set the ```readyState``` to something other than ```WebSocket.CONNECTING```.

I would be happy to open a PR once I have a little more background information. 

Thanks!

**Comment by 3rd-Eden** [comment] 2016-04-11 10:39
Fixed in master.

**Closed by 3rd-Eden** 2016-04-11 10:39 UTC
