### ISSUE TITLE
WS-Server using express.js leads to "invalid frame header" when connecting with browser

### ISSUE THREAD

**Issue by messerbill** [websockets/ws#2183] opened 2023-12-17 14:33 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I have an express.js server combined with ws:

```
import express from "express"
import { IncomingMessage, Server, ServerResponse } from "http"
import { WebSocketServer } from "ws"

const expressApp = express()
const server = registerApiListeners(expressApp, port)
const wss = new WebSocketServer({ server })

wss.on(
    "connection",
    async function connection(ws: WebSocket, req: IncomingMessage | Request) {
      logger.info("New WebSocket connected")
      try {
        const { authorizedUser, projectId } = await authorize(ws, req)
        const projectId_ = parseInt(projectId)
        console.log(ws.readyState) // <--------------- logs "3" which means closed
        ws.send(JSON.stringify({ type: "WELCOME" }))
      } catch (error) {
        logger.error("Error parsing message:", error)
      }
    }
)

function registerApiListeners(expressApp: Express, port: number) {
    return expressApp.listen(port, () => {
      logger.info("Registering API listeners")
      indexEndpoints(expressApp)
      roomEndpoints(expressApp)
      logger.info(`Service started on port: ${port}`)
    })
}

```

Client code (executed in a browser):

```
const ws = new WebSocket(url, [token, projectId])
```

The connection is established at first since chrome dev tools show the following:

> Request-URL:
ws://localhost:3017/;
Requestmethod:
GET;
Statuscode:
101 Switching Protocols

When I inspect the messages that has been sent I see: `Invalid Frame Header`.

### ws version

^8.14.2

### Node.js Version

v18.12.1

### System

  System:
    OS: Windows 11 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 2600 Six-Core Processor
    Memory: 7.92 GB / 15.95 GB

### Expected result

No error at all.

### Actual result

Error in console: "Invalid frame header" with a `readyState` of `3`

### Attachments

![image](https://github.com/websockets/ws/assets/11415481/9d298150-cae1-4d9f-bffa-1b4d2e4c17dd)

Maybe interesting: Inside of the `authorize` method an ssh public key is read from the file system. Before the `fs.readFile` call `ws.readyState` is still `1`. Afterwards it is `3`. However, even when i outcomment the authorization method the problem persists.

**Comment by lpinca** [comment] 2023-12-17 20:35
I cannot reproduce the issue. This is the code I'm using:

```js
const express = require('express');
const { WebSocketServer } = require('ws');

const app = express();
const server = app.listen(8080);

const wss = new WebSocketServer({ server });

wss.on('connection', function (ws) {
  ws.send(JSON.stringify({ type: 'WELCOME' }));
});
```

The browser is Chrome 120.0.6099.109.

>  Inside of the `authorize` method an ssh public key is read from the file system. Before the `fs.readFile` call `ws.readyState` is still `1`. Afterwards it is `3`.

The `authorize` function is async. The websocket can be closed before it completes.

**Comment by messerbill** [comment] 2023-12-17 20:45
Thank you for the answer!

> The authorize function is async. The websocket can be closed before it completes.

But since there is the `await` it should be awaited before executing the next line, doesn't it?

**Comment by lpinca** [comment] 2023-12-17 20:52
No, `await` does not block.

**Comment by lpinca** [comment] 2023-12-17 21:16
You can reproduce the "Invalid frame header" error on the browser by sending an invalid frame. For example you can send a masked frame.

```js
const { WebSocketServer } = require('ws');

const wss = new WebSocketServer({ port: 8080 });

wss.on('connection', function (ws) {
  ws._socket.write('828000000000');
});
```

but `ws.send()` should only produce valid frames.

**Comment by messerbill** [comment] 2023-12-17 21:39
I already gave up since you said that you could not reproduce it. I now added my code step by step to you minimum example. Now it is working. The mistake I made was kind of silly but the error was missleading so I did not notice it for several days....

I've had another socket server in my application (peerjs) for a voice chat implementation. When my first websocket server started (which is linked to my express app as described above) it conflicted with that peer server (which is my second websocket server) since both of them were using the same port. I thought that it was possible to link as many ws servers to the express app as I want to but when I use peerjs this seems not to be true.

Now I have two express apps running parallel: The first one is linked to the websocket server as my example shows and the second one is implemented like so:

```
import express from "express"
import { ExpressPeerServer } from "peer"
import { logger } from "services"

export async function createPeerServer() {
  logger.info("Creating Peer Server")
  const expressInstance = express()
  const server = expressInstance.listen(process.env.PEER_SERVER_PORT!)
  const peerServer = ExpressPeerServer(server, {
    proxied: true,
  })
  expressInstance.use(peerServer)
}
```

What confused me that much was the error which I read like there must have been something wrong with the first ws server since the printed URL in the error message was the one of that ws server (with its path) and not the one of the peer server.

Anyway, thank you very much for your reply since this made me find the mistake in the end. 

Merry Christmas!

**Comment by lpinca** [comment] 2023-12-18 06:40
Ok, I'm closing this then.

**Closed by lpinca** 2023-12-18 06:40 UTC
