### ISSUE TITLE
Incompatibility between documentation and Typescript

### ISSUE THREAD

**Issue by Don2Quixote** [websockets/ws#1812] opened 2020-10-24 08:26 UTC
- [X] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

Typescript and related mistake in the documentation 

#### Reproducible in:

- version: 7.3.1
- Node.js version(s): 14.9.0
- OS version(s): Arch Linux x86_64 (Kernel: 5.9.1)

#### Steps to reproduce:

In the documentation there is a note about how to detect and close broken connections, which contains
`ws.isAlive = true` on `connection` event. But `isAlive` is not real property of `ws` and Typescript raises error.

#### Expected result:

`isAlive` is a property of `ws` or another way to detect broken connections is documented

#### Actual result:

Type script raises error when trying to reproduce documented way to detect broken connections

#### Attachments:

```
src/main.ts:44:12 - error TS2339: Property 'isAlive' does not exist on type 'WebSocket'.

44     socket.isAlive = true;
```

**Comment by juanp123** [comment] 2020-10-24 09:25
Working through the ping/pong myself with typescript.   I have other issues but this will solve the above...

https://stackoverflow.com/questions/57906105/nodejs-ws-module-heartbeat-in-typescript

> I got it to work by creating a Custom Socket interface that extends Web Socket.

```

interface CustomSocket extends WebSocket {
    isAlive: boolean
}
export default class WS {
    private heartbeat: ReturnType<typeof setInterval>
    private wss: WebSocket.Server


    constructor(port: number) {
        this.wss = new WebSocket.Server({port});

        this.wss.on('connection', this.handleConnection)
    }

    private handleConnection(socket: CustomSocket) {
        socket.on('pong', () => socket.isAlive = true)
    }
}
```

**Comment by lpinca** [comment] 2020-10-25 05:15
I'm closing this as this as it is not a bug in the library.

**Closed by lpinca** 2020-10-25 05:15 UTC

**Comment by juanp123** [comment] 2020-10-25 06:23
@Don2Quixote Just leaving this as reference for you and anyone else using typescript that stumbles here.   This is a typescript node/express example using ws.  The methods (below) for `onMessage` and `onWSServerClose` are not yet tested but work in theory.  Mainly wanted to put a server.close so people do not mistake it for websocket.close.  The ping-pong works.   

I am not adding to the client example on [https://github.com/websockets/ws]( https://github.com/websockets/ws) but note that that example uses ` this.terminate();` .  Terminate is from the 'ws' lib.  This method does not exist in native browser websocket api [https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Methods](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Methods)).  If the client is the native browser, there is no `.terminate()`. Could use `.close()`. 

This example is using node/express,  so elsewhere it is called like
 
` const httpsServer = https.createServer(credentials);   // <== this is `HTTPS`  (i.e. for use with wss:// not ws:// )

  const wss = webSocketService.createServer( httpsServer );`

tsconfig.json needs a ` compilerOption"`  set to  `"esModuleInterop": true,` for the following imports to resolve properly.

**--- websocket-service.ts ---**
`
import WebSocket from 'ws';
import {Server} from "ws";

interface  CustomWebSocket extends WebSocket {
    isAlive: boolean
}

class WebSocketService {
    wss: WebSocket.Server;
    interval: NodeJS.Timer;

    createServer( server ) {
        this.wss = new Server({ server });
        this.startHeartBeatPing();

        this.wss.on('connection',
            (ws: CustomWebSocket)  => {
                const that = this;
                ws.isAlive = true;
                ws.on('pong', (data)  => this.onHeartbeat(ws, data, that)); //<== example to show explicitly passing ws or wss ref
                ws.on('message', this.onMessage);
                ws.on('error', (error: Error) => console.error( `[error] ${error.message}`) );
                ws.on('close',  this.onWSClose );
            }
        );

        this.wss.on('close', this.onWSServerClose);
    }

    onWSServerClose( ) {
        clearInterval(this.interval);
    }

    onWSClose( code:number , reason: string) {
        console.info(`[close] Connection closed code=${code} reason=${reason}`);
    }

    startHeartBeatPing() {
        this.interval = setInterval( () => {
            this.wss.clients.forEach( (ws: CustomWebSocket ) => {
                console.info ( `ws.isAlive: ${ws.isAlive}`);
                if (ws.isAlive === false) {
                    console.log ( 'ws-terminating' );
                    return ws.terminate();
                }
                ws.isAlive = false;
                ws.ping(this.noop); //client (browser) internally responds with a 'pong' as per the spec
            });

        }, 10000);  // <== use a short time out quicker testing 
    }

    onMessage(data: WebSocket.Data) {
        console.info('onMessage received: %s', data);
    }

    noop() {
    }

    onHeartbeat( ws: CustomWebSocket, data: Buffer, wss: WebSocketService)  {
        ws.isAlive = true;
        console.info ( 'onHeartbeat' );
    }
}

**Comment by ferares** [comment] 2022-09-19 11:59
> @Don2Quixote Just leaving this as reference for you and anyone else using typescript that stumbles here. This is a typescript node/express example using ws. The methods (below) for `onMessage` and `onWSServerClose` are not yet tested but work in theory. Mainly wanted to put a server.close so people do not mistake it for websocket.close. The ping-pong works.
> 
> I am not adding to the client example on https://github.com/websockets/ws but note that the example uses ` this.terminate();` . Terminate is from the 'ws' lib. This method does not exist in native browser websocket api https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Methods). If the client is the native browser, there is no `.terminate()`. Could use `.close()`.
> 
> This example is using node/express, so elsewhere it is called like
> 
> `const httpsServer = https.createServer(credentials); // <== this is`HTTPS` (i.e. for use with wss:// not ws:// )
> 
> const wss = webSocketService.createServer( httpsServer );`
> 
> tsconfig.json needs a ` compilerOption"` set to `"esModuleInterop": true,` for the following imports to resolve properly.
> 
> **--- websocket-service.ts ---** ` import WebSocket from 'ws'; import {Server} from "ws";
> 
> interface CustomWebSocket extends WebSocket { isAlive: boolean }
> 
> class WebSocketService { wss: WebSocket.Server; interval: NodeJS.Timer;
> 
> ```
> createServer( server ) {
>     this.wss = new Server({ server });
>     this.startHeartBeatPing();
> 
>     this.wss.on('connection',
>         (ws: CustomWebSocket)  => {
>             const that = this;
>             ws.isAlive = true;
>             ws.on('pong', (data)  => this.onHeartbeat(ws, data, that)); //<== example to show explicitly passing ws or wss ref
>             ws.on('message', this.onMessage);
>             ws.on('error', (error: Error) => console.error( `[error] ${error.message}`) );
>             ws.on('close',  this.onWSClose );
>         }
>     );
> 
>     this.wss.on('close', this.onWSServerClose);
> }
> 
> onWSServerClose( ) {
>     clearInterval(this.interval);
> }
> 
> onWSClose( code:number , reason: string) {
>     console.info(`[close] Connection closed code=${code} reason=${reason}`);
> }
> 
> startHeartBeatPing() {
>     this.interval = setInterval( () => {
>         this.wss.clients.forEach( (ws: CustomWebSocket ) => {
>             console.info ( `ws.isAlive: ${ws.isAlive}`);
>             if (ws.isAlive === false) {
>                 console.log ( 'ws-terminating' );
>                 return ws.terminate();
>             }
>             ws.isAlive = false;
>             ws.ping(this.noop); //client (browser) internally responds with a 'pong' as per the spec
>         });
> 
>     }, 10000);  // <== use a short time out for quicker testing 
> }
> 
> onMessage(data: WebSocket.Data) {
>     console.info('onMessage received: %s', data);
> }
> 
> noop() {
> }
> 
> onHeartbeat( ws: CustomWebSocket, data: Buffer, wss: WebSocketService)  {
>     ws.isAlive = true;
>     console.info ( 'onHeartbeat' );
> }
> ```
> 
> }
> 
> `
Ty, only thing that wasn't working for me was the forEach loop, I had to go with this approach for that https://github.com/websockets/ws/issues/1517#issuecomment-518051914
