### ISSUE TITLE
'close' event firing too late

### ISSUE THREAD

**Issue by cronvel** [websockets/ws#964] opened 2017-01-11 15:28 UTC
It seems that the 'close' event is emitted once the readyState is set to `CLOSED`.

But there is another readyState named `CLOSING` that does not emit anything, still, if `.send()` is called, it throws the ambiguous *Not opened* error. Since this `CLOSING` state doesn't last long (few milliseconds), this causes some rare bugs hard to reproduce. Usually, I receive the 'close' event up to 8ms after the error was thrown.

Checking readyState before each `.send()` is an option, but it's not particularly nice, and since events are specifically designed to centralize clean up code, it would be great if:
* either the 'close' event would be fired immediately once readyState is set to `CLOSING`
* or if another event would be created specifically for that task, maybe 'end'

It's worth noting that listening the underlying socket does not help, the 'end' (in the Net Socket sense) event fire too late too. A potential 'end' event on the WebSocket object should be emitted as soon as the WebSocket is not writable anymore.

**Comment by lpinca** [comment] 2017-01-11 15:34
> Since this CLOSING state doesn't last long

It really depends, it can last far more than few milliseconds as a WebSocket stays in `CLOSING` state for the whole duration a close handshake. In the worst case possible when the other peer does not answer it can be 30 sec.

> Checking readyState before each .send() is an option

I think this is what most people do.

**Comment by lpinca** [comment] 2017-01-11 15:36
We could make `send` fail silently if `readyState` is not open but I'm not sure if it is a good idea.

**Comment by cronvel** [comment] 2017-01-11 16:35
You don't like the 'end' event idea?

**Comment by lpinca** [comment] 2017-01-11 16:39
@cronvel what happens if `send` is called after the `end` event is emitted?

**Comment by cronvel** [comment] 2017-01-11 16:47
It still throws an exception. The difference is that the cleanup code bound to the 'close' event would be bound to the 'end' event.

Usually, that cleanup code removes the client/user from the list of connected clients/users maintained by the application.

**Comment by lpinca** [comment] 2017-01-11 17:20
If I understand correctly, you would like to have an event which is emitted when no more data should be written to the websocket in order to remove it from the list of connected clients, right?

If the websocket is not fully closed it shouldn't be cleaned up imo. You may still receive valid data when `readyState` is `CLOSING`, the size of your collection will not match the actually connected sockets, etc.

**Comment by cronvel** [comment] 2017-01-11 17:26
Yes that's it ;)

**Comment by lpinca** [comment] 2017-01-11 17:44
Ok, then it might have more sense to call the event `closing`, but I'm honestly -1 on this.
Anyway other collaborators may disagree with me.

**Comment by lpinca** [comment] 2017-01-13 08:12
Refs: https://github.com/websockets/ws/issues/464

**Comment by lpinca** [comment] 2017-07-22 05:53
Duplicate of #464.

**Comment by christopherreay** [comment] 2018-07-10 10:11
> If the websocket is not fully closed it shouldn't be cleaned up imo. You may still receive valid data when readyState is CLOSING, the size of your collection will not match the number of connected sockets, etc.

Could you just quickly mention *how* data can still arrive thats valid during 'CLOSING' state?

Thank you

**Comment by lpinca** [comment] 2018-07-10 10:21
@christopherreay from one peer you send a close frame via `ws.close()`, that sets the `readyState` to `CLOSING`, the other peer does not receive the close frame immediately and before it receives it, it may send some data. That data is on the wire while the `readyState` is `CLOSING`. The peer that initiated the closing handshake will then receive the data and after that the close frame. Only at this point the `readyState` is set to `CLOSED`.

As per spec the closing handshake is completed only when both peers have sent and received a close frame.

Hope this makes sense.

**Closed** 2018-08-21 06:26 UTC
Labels: duplicate
