### ISSUE TITLE
Payload size issue

### ISSUE THREAD

**Issue by kashish-airmeet** [websockets/ws#1888] opened 2021-05-24 12:14 UTC
```
  const socket = new WebSocket.Server({
    server: server,
    maxPayload: 512 * 1024
  }, {
    rejectUnauthorized: false,
  });
```
Added max payload size as 512 kb. But the server is throwing error on 120 kb also.
`"message":"Error occurred Max payload size exceeded and payload length is 121068 and buffered length is 11304","level":"error","timestamp":"2021-05-24 11:14:31"`

**Comment by lpinca** [comment] 2021-05-24 17:16
I can't reproduce:

```
$ cat index.js 
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server(
  { port: 0, maxPayload: 512 * 1024 },
  function () {
    const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

    ws.on('open', function () {
      ws.send(Buffer.alloc(120 * 1024));
    });
  }
);

wss.on('connection', function(ws) {
  ws.on('message', function(message) {
    console.log(message.length);
    wss.close();
  })
});
```

```
$ node index.js 
122880
```

Also that error message is not produced by `ws` so make sure you are actually receiving an error from `ws`.

**Comment by kashish-airmeet** [comment] 2021-05-24 17:18
> I can't reproduce:
> 
> ```
> $ cat index.js 
> 'use strict';
> 
> const WebSocket = require('ws');
> 
> const wss = new WebSocket.Server(
>   { port: 0, maxPayload: 512 * 1024 },
>   function () {
>     const ws = new WebSocket(`ws://localhost:${wss.address().port}`);
> 
>     ws.on('open', function () {
>       ws.send(Buffer.alloc(120 * 1024));
>     });
>   }
> );
> 
> wss.on('connection', function(ws) {
>   ws.on('message', function(message) {
>     console.log(message.length);
>     wss.close();
>   })
> });
> ```
> 
> ```
> $ node index.js 
> 122880
> ```
> 
> Also that error message is not produced by `ws` so make sure you are actually receiving an error from `ws`.

Actually the error is logged by us but in case of lesser payload than the required one, it goes onto the error event

**Comment by lpinca** [comment] 2021-05-24 17:59
1. Do not use `ws._receiver._payloadLength`. Property prefixed with `_` are "private" and should not be used.
2. `ws._receiver._payloadLength` gives you the last frame payload length but the message might be fragmented and/or compressed so the `message` size might be bigger.
3. I don't understand what is the issue. No error is raised if the message size is <= `maxPayload` and the code snippet in the previous comment seems to be truncated. Please fill the issue template and write a test case I can run to reproduce the issue.

**Comment by kashish-airmeet** [comment] 2021-05-25 05:37
> 1. Do not use `ws._receiver._payloadLength`. Property prefixed with `_` are "private" and should not be used.
> 2. `ws._receiver._payloadLength` gives you the last frame payload length but the message might be fragmented and/or compressed so the `message` size might be bigger.
> 3. I don't understand what is the issue. No error is raised if the message size is <= `maxPayload` and the code snippet in the previous comment seems to be truncated. Please fill the issue template and write a test case I can run to reproduce the issue.

`'use strict';
const nr = require('newrelic');
const WebSocket = require('ws');
const app = require('express')();
const cluster = require('cluster');
const http = require('http');
const logger = require('./lib/logger');
const connectionProcessor = require('./processors/connection-processor');
const eventProcessor = require('./processors/event-processor');
const errors = require('./lib/constants/constants').ERRORS;
const socketConfiguration = require('./configs/config').get('socket');
const { v4: uuidv4 } = require('uuid')

const NEW_RELIC_CUSTOM_EVENTS = require('./lib/constants/constants').NEW_RELIC_CUSTOM_EVENTS;
const numCPUs = require('os').cpus().length;
if (cluster.isMaster) {
  logger.info(`Master ${process.pid} is running`);
  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }
  cluster.on('exit', (worker, code, signal) => {
    logger.error(`worker ${worker.process.pid} died, code: ${code}, signal ${signal}`);
  });
} else {
  const server = http.createServer(app);
  logger.info(`Worker ${process.pid} started`);
  const socket = new WebSocket.Server({
    server: server,
    maxPayload: 512 * 1024
  }, {
    rejectUnauthorized: false,
  });

  function noop() { }

  function heartbeat() {
    this.isAlive = true;
  }

  socket.on('connection', (ws, request) => {
    nr.startWebTransaction('/websocket/connect', function transactionHandler() {

      connectionProcessor.handleOpenConnection(ws, request);
      nr.endTransaction();
    })
    ws.isAlive = true;

    // add another new relic endpoint to check for successfull connections
    nr.startWebTransaction('/websocket/successful-connections', function transactionHandler() {
      nr.endTransaction();
    })

    ws.on('pong', heartbeat);
    ws.on('message', (message) => {
      const payload = JSON.parse(message);
      const size = 150 * 1024
      const generated_id = uuidv4();
      logger.info(`Received payload of length ${ws._receiver._payloadLength} with id ${generated_id}`);
      payload['generated_id'] = generated_id;
      const payload_final = JSON.stringify(payload);
      logger.info(`Payload received is ${payload_final}`);
      if (parseInt(ws._receiver._payloadLength) > size) {
        logger.info(`Received payload ${payload_final} greater than the minimum limit with size ${ws._receiver._payloadLength}`);
      }
      nr.startWebTransaction('/websocket/message-received', function transactionHandler() {
        var handle = function (error, value) {
          if (!error) return;
          nr.recordCustomEvent(NEW_RELIC_CUSTOM_EVENTS.MESSAGE_ERROR, {
            errorCode: error
          });
          if (errors.INVALID_JSON === error) {
            logger.error(`Invalid json error for message: ${JSON.stringify(message)} on ws ${JSON.stringify(ws)}`);
            return ws.terminate();
          } else if (error) {
            logger.error(`error for message: ${JSON.stringify(message)} on ws ${JSON.stringify(ws)} , error :${error}`);
          }
        }
        eventProcessor.processUIEvent(ws, message, handle);
        nr.endTransaction();
      });
    });

    ws.on('close', (code, reason) => {
      nr.startWebTransaction('/websocket/disconnect', function transactionHandler() {
        connectionProcessor.handleCloseConnection(ws, code, reason);
        nr.endTransaction();
      })
    });
    ws.on('error', (e) => {
      logger.error(`Error occurred ${e.message} and payload length is ${ws._receiver._payloadLength} and buffered length is ${ws._receiver._bufferedBytes}`);
    });
  });

  const interval = setInterval(() => {
    logger.info(`Current connections are ${socket.clients.size}`);
    socket.clients.forEach(function each(ws) {
      if (ws.isAlive === false) return ws.terminate();
      ws.isAlive = false;
      ws.ping(noop);
    });
  }, socketConfiguration.heartbeat_interval);

  socket.on('close', function close() {
    logger.error(`Websocket closed `);
  });
  socket.onerror = function(error) {
    logger.error(`Socket error ${error.message}`);
  };

  const port = process.env.PORT || 8080;
  app.get('/health', (req, res) => res.status(200).send("OK"));
  server.listen(port, function () {
    logger.info(`Server listening on ${process.env.PORT}`);
  });
}`

**Comment by kashish-airmeet** [comment] 2021-05-25 05:39
> 1. Do not use `ws._receiver._payloadLength`. Property prefixed with `_` are "private" and should not be used.
> 2. `ws._receiver._payloadLength` gives you the last frame payload length but the message might be fragmented and/or compressed so the `message` size might be bigger.
> 3. I don't understand what is the issue. No error is raised if the message size is <= `maxPayload` and the code snippet in the previous comment seems to be truncated. Please fill the issue template and write a test case I can run to reproduce the issue.

```
'use strict';
const nr = require('newrelic');
const WebSocket = require('ws');
const app = require('express')();
const cluster = require('cluster');
const http = require('http');
const logger = require('./lib/logger');
const connectionProcessor = require('./processors/connection-processor');
const eventProcessor = require('./processors/event-processor');
const errors = require('./lib/constants/constants').ERRORS;
const socketConfiguration = require('./configs/config').get('socket');
const { v4: uuidv4 } = require('uuid')

const NEW_RELIC_CUSTOM_EVENTS = require('./lib/constants/constants').NEW_RELIC_CUSTOM_EVENTS;
const numCPUs = require('os').cpus().length;
if (cluster.isMaster) {
  logger.info(`Master ${process.pid} is running`);
  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }
  cluster.on('exit', (worker, code, signal) => {
    logger.error(`worker ${worker.process.pid} died, code: ${code}, signal ${signal}`);
  });
} else {
  const server = http.createServer(app);
  logger.info(`Worker ${process.pid} started`);
  const socket = new WebSocket.Server({
    server: server,
    maxPayload: 512 * 1024
  }, {
    rejectUnauthorized: false,
  });

  function noop() { }

  function heartbeat() {
    this.isAlive = true;
  }

  socket.on('connection', (ws, request) => {
    nr.startWebTransaction('/websocket/connect', function transactionHandler() {

      connectionProcessor.handleOpenConnection(ws, request);
      nr.endTransaction();
    })
    ws.isAlive = true;

    // add another new relic endpoint to check for successfull connections
    nr.startWebTransaction('/websocket/successful-connections', function transactionHandler() {
      nr.endTransaction();
    })

    ws.on('pong', heartbeat);
    ws.on('message', (message) => {
      const payload = JSON.parse(message);
      const size = 150 * 1024
      const generated_id = uuidv4();
      logger.info(`Received payload of length ${ws._receiver._payloadLength} with id ${generated_id}`);
      payload['generated_id'] = generated_id;
      const payload_final = JSON.stringify(payload);
      logger.info(`Payload received is ${payload_final}`);
      if (parseInt(ws._receiver._payloadLength) > size) {
        logger.info(`Received payload ${payload_final} greater than the minimum limit with size ${ws._receiver._payloadLength}`);
      }
      nr.startWebTransaction('/websocket/message-received', function transactionHandler() {
        var handle = function (error, value) {
          if (!error) return;
          nr.recordCustomEvent(NEW_RELIC_CUSTOM_EVENTS.MESSAGE_ERROR, {
            errorCode: error
          });
          if (errors.INVALID_JSON === error) {
            logger.error(`Invalid json error for message: ${JSON.stringify(message)} on ws ${JSON.stringify(ws)}`);
            return ws.terminate();
          } else if (error) {
            logger.error(`error for message: ${JSON.stringify(message)} on ws ${JSON.stringify(ws)} , error :${error}`);
          }
        }
        eventProcessor.processUIEvent(ws, message, handle);
        nr.endTransaction();
      });
    });

    ws.on('close', (code, reason) => {
      nr.startWebTransaction('/websocket/disconnect', function transactionHandler() {
        connectionProcessor.handleCloseConnection(ws, code, reason);
        nr.endTransaction();
      })
    });
    ws.on('error', (e) => {
      logger.error(`Error occurred ${e.message} and payload length is ${ws._receiver._payloadLength} and buffered length is ${ws._receiver._bufferedBytes}`);
    });
  });

  const interval = setInterval(() => {
    logger.info(`Current connections are ${socket.clients.size}`);
    socket.clients.forEach(function each(ws) {
      if (ws.isAlive === false) return ws.terminate();
      ws.isAlive = false;
      ws.ping(noop);
    });
  }, socketConfiguration.heartbeat_interval);

  socket.on('close', function close() {
    logger.error(`Websocket closed `);
  });
  socket.onerror = function(error) {
    logger.error(`Socket error ${error.message}`);
  };

  const port = process.env.PORT || 8080;
  app.get('/health', (req, res) => res.status(200).send("OK"));
  server.listen(port, function () {
    logger.info(`Server listening on ${process.env.PORT}`);
  });
}
```
This is the complete file

**Comment by lpinca** [comment] 2021-05-25 06:23
It means that the client is sending a fragmented message whose size is bigger than `maxPayload`. Here is a test case to reproduce it:

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server(
  { port: 0, maxPayload: 512 * 1024 },
  function () {
    const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

    ws.on('open', function () {
      const chunk = Buffer.alloc(256 * 1024);

      ws.send(chunk, { fin: false });
      ws.send(chunk, { fin: false });
      ws.send(chunk, { fin: true });
    });
  }
);

wss.on('connection', function(ws) {
  ws.on('message', function(message) {
    console.log(message.length);
  });

  ws.on('error', function (err) {
    console.error(err);
    wss.close();
  })
});
```

This is not a bug. It is working as expected. What you are logging is the payload size of the last fragment before the error is raised.

**Comment by kashish-airmeet** [comment] 2021-05-25 08:03
> It means that the client is sending a fragmented message whose size is bigger than `maxPayload`. Here is a test case to reproduce it:
> 
> ```js
> const WebSocket = require('ws');
> 
> const wss = new WebSocket.Server(
>   { port: 0, maxPayload: 512 * 1024 },
>   function () {
>     const ws = new WebSocket(`ws://localhost:${wss.address().port}`);
> 
>     ws.on('open', function () {
>       const chunk = Buffer.alloc(256 * 1024);
> 
>       ws.send(chunk, { fin: false });
>       ws.send(chunk, { fin: false });
>       ws.send(chunk, { fin: true });
>     });
>   }
> );
> 
> wss.on('connection', function(ws) {
>   ws.on('message', function(message) {
>     console.log(message.length);
>   });
> 
>   ws.on('error', function (err) {
>     console.error(err);
>     wss.close();
>   })
> });
> ```
> 
> This is not a bug. It is working as expected. What you are logging is the payload size of the last fragment before the error is raised.

Is there any way of logging the payload inside onError?

**Comment by lpinca** [comment] 2021-05-25 08:39
> Is there any way of logging the payload inside onError?

There is no official way. If you keep the permessage-deflate extension disabled you can use `ws._receiver._totalPayloadLength` but again those properties are "private" and should not be used.

**Comment by kashish-airmeet** [comment] 2021-05-25 08:43
> > Is there any way of logging the payload inside onError?
> 
> There is no official way. If you keep the permessage-deflate extension disabled you can use `ws._receiver._totalPayloadLength` but again those properties are "private" and should not be used.

No I am asking if I can log the complete payload inside error event

**Comment by lpinca** [comment] 2021-05-25 08:54
You can read the data in the `receiver._fragments` array but the latest chunk is not included.

**Comment by lpinca** [comment] 2021-05-25 10:41
I'm closing this as answered. Discussion can continue if needed.

**Closed by lpinca** 2021-05-25 10:41 UTC
