### ISSUE TITLE
client websocket not receiving all messages before close event when sending large messages

### ISSUE THREAD

**Issue by go-oleg** [websockets/ws#678] opened 2016-02-11 23:28 UTC
I am running into a situation where my browser websocket's `onclose` handler is firing before the `onmessage` handler has received all the sent messages.

gist: https://gist.github.com/go-oleg/32d73afdf2d4a616d9d5

```
$ npm install
$ node app.js
```

and

```
$ open index.html
```

I see this in the logs:
![image](https://cloud.githubusercontent.com/assets/3344137/12994133/2f56fc10-d0d3-11e5-91ea-12b1d878716d.png)

and this in chrome (Version 48.0.2564.109 (64-bit) on OS) dev tools:
![image](https://cloud.githubusercontent.com/assets/3344137/12994143/3f124bf0-d0d3-11e5-95f7-985e269d252a.png)

I am sending 3 messages and there are 3 in chrome dev tools but my `onmessage` handler is only firing twice.

If I decrease the number of points per message, this is not an issue. If I delay the closing of the websocket on the server by a second, this also isn't an issue.

Is there a cleaner way I should be closing the websocket on the server to ensure the client-side doesn't run into these issues? Or is it up to me to send acknowledgement messages from the client back to the server and only close when I've confirmed I've processed all the messages.  I am frankly not even sure if this is a server-side or a client-side problem.

Any pointers would be greatly appreciated!

**Comment by rkaw92** [comment] 2016-02-12 19:53
Confirmed on Chromium 47.0 (Debian 8), but non-reproducible on Iceweasel (Firefox) 38.5, using your test code.
Chromium bug?

**Comment by go-oleg** [comment] 2016-02-12 20:15
@rkaw92, thx for trying it out (and reminding me that I should've included my browser version too).

**Comment by lpinca** [comment] 2016-12-19 17:07
@go-oleg Thank you for the report and the test case!
I can't reproduce the issue in Chrome 55 and Firefox 50.

Maybe it was a Chrome bug?

Closing, please reopen if the issue persists.

**Closed by lpinca** 2016-12-19 17:07 UTC
