### ISSUE TITLE
Broken compatibility with Rollup

### ISSUE THREAD

**Issue by LinusU** [websockets/ws#2057] opened 2022-06-09 10:05 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

When upgrading our app that is deployed to Lambda to version 8.x, we noticed that it will fail at runtime with the following error:

```text
TypeError: Cannot read property 'mask' of undefined
    at mask (file:///var/task/index.js:14547:23)
    at Function.frame (file:///var/task/index.js:16009:5)
    at Sender$1.send (file:///var/task/index.js:16226:18)
    at WebSocket.send (file:///var/task/index.js:17277:18)
    at WebSocket.<anonymous> (file:///var/task/index.js:18302:12)
    at WebSocket.emit (events.js:400:28)
    at WebSocket.setSocket (file:///var/task/index.js:17046:10)
    at ClientRequest.<anonymous> (file:///var/task/index.js:17783:15)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketOnData (_http_client.js:553:11)
```

I believe that this is because of the following conditional export:

https://github.com/websockets/ws/blob/0792742de13bfac0faecf044d290485808192665/lib/buffer-util.js#L102-L126

I believe that this could be fixed by doing something like:

```js
module.exports = {
  concat,
  mask: _mask,
  toArrayBuffer,
  toBuffer,
  unmask: _unmask
}; 
  
try { 
  const bufferUtil = require('bufferutil');

  module.exports.mask = function mask(source, mask, output, offset, length) {
    if (length < 48) _mask(source, mask, output, offset, length);
    else bufferUtil.mask(source, mask, output, offset, length);
  };

  module.exports.unmask = function unmask(buffer, mask) { 
    if (buffer.length < 32) _unmask(buffer, mask);
    else bufferUtil.unmask(buffer, mask);
  };
} catch (e) /* istanbul ignore next */ {}
```

### ws version

8.7.0

### Node.js Version

v18.0.0

### System

```text
  System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 90.55 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
```

### Expected result

No error

### Actual result

TypeError: Cannot read property 'mask' of undefined

### Attachments

n/a

**Comment by LinusU** [comment] 2022-06-09 10:45
Nice! 👍 

That seems like it indeed would fix this problem as well

**Comment by lpinca** [comment] 2022-06-09 19:34
Nevermind, I missed this line `at mask (file:///var/task/index.js:14547:23)`.
I'm closing this. Please post back if the issue persists.

**Closed by lpinca** 2022-06-09 19:34 UTC

**Comment by LinusU** [comment] 2022-06-10 14:19
I get a slightly different error message with 8.8.0, but I think that this might be an limitation/error in Rollup rather than here...

This is the code that rollup outputs:

```js

bufferUtil$1.exports = {
  concat: concat$1,
  mask: _mask,
  toArrayBuffer: toArrayBuffer$1,
  toBuffer: toBuffer$2,
  unmask: _unmask
};

/* istanbul ignore else  */
if (!process.env.WS_NO_BUFFER_UTIL) {
  try {
    const bufferUtil = undefined;

    mask = bufferUtil$1.exports.mask = function (source, mask, output, offset, length) {
      if (length < 48) _mask(source, mask, output, offset, length);
      else bufferUtil.mask(source, mask, output, offset, length);
    };

    unmask$1 = bufferUtil$1.exports.unmask = function (buffer, mask) {
      if (buffer.length < 32) _unmask(buffer, mask);
      else bufferUtil.unmask(buffer, mask);
    };
  } catch (e) {
    // Continue regardless of the error.
  }
}
```

Notice that `const bufferUtil = require('bufferutil');` is being rewritten to `const bufferUtil = undefined;`

**Comment by lpinca** [comment] 2022-06-10 15:54
I do not know if this is caused by the conditional export in [`bufferutil`](https://github.com/websockets/bufferutil/blob/v4.0.6/index.js) but I think there is not much we can do about it.
