### ISSUE TITLE
CLient only connect via localhost

### ISSUE THREAD

**Issue by ZederickVargas** [websockets/ws#2049] opened 2022-05-26 10:18 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

The client can only connect using localhost address, if I ttry to connect using my actual ip address it failed

**Comment by lpinca** [comment] 2022-05-26 10:44
I'm sorry but as is this issue is not actionable. Please provide more info and add a test case to reproduce the issue.

**Comment by ZederickVargas** [comment] 2022-05-26 12:15
I solved it but indirectly, the thing is when I use basic server http and I try to connect it shows that I am trying to connect via https (wss) even I have ws written on my client url. so I change my server  to https and is working

**Comment by lpinca** [comment] 2022-05-26 16:50
`ws` does not do this. If you use the `ws:` protocol in the connection URL, the request for the opening handshake is sent over plain HTTP, not HTTPS. It must be caused by something on your setup/application.

I'm closing this. Discussion can continue if needed.

**Closed by lpinca** 2022-05-26 16:50 UTC
