### ISSUE TITLE
add ws.open() method

### ISSUE THREAD

**Issue by Kamikadze4GAME** [websockets/ws#1451] opened 2018-09-28 15:31 UTC
Hi all! I want to suggest to add `ws.open()` method. Do not immediately connect. 

Why? For example, i want to add some event handlers and after all connect.
Something like this
```js
let ws = new WS('wss://example.org', {
  doNotOpenImmediately: true
});

...
  // something here
...

ws.on('error', err => console.error(err));
ws.on('message', mess => console.log(mess));

...
  // something else
...

// and now
ws.open(cb(){
  // callback
});
```

**Comment by lpinca** [comment] 2018-09-28 18:37
Connection is asynchronous so you can safely add all the handlers after creating the instance even if connection is established immediately.

**Comment by Kamikadze4GAME** [comment] 2018-09-28 19:05
But what if connection immediate throw error?

**Comment by lpinca** [comment] 2018-09-28 19:59
It doesn't.

**Comment by Kamikadze4GAME** [comment] 2018-09-28 20:01
But if wrong url of ws (typo)? `wss://example.com/socket` - good, `wss://example.com/socke`

**Comment by lpinca** [comment] 2018-09-28 20:09
There are cases where the constructor can throw but that is by design, for example when the programmer uses an invalid URL.

**Comment by lpinca** [comment] 2018-09-29 19:12
Closing as I see no real advantage in doing this and diverging from the browser interface. Discussion can continue if needed.

**Closed by lpinca** 2018-09-29 19:12 UTC
