### ISSUE TITLE
It's not efficient enough to deal with large amount of data

### ISSUE THREAD

**Issue by leeyo** [websockets/ws#289] opened 2014-02-21 01:52 UTC
I build up a server ,and 20 clients.then the clients send datas to the server with 1000 packet per client.It can be saw,server receive many pacets.and then i kill the clients,the server console clients ammount is 0. it's sure that there is no connections.
But,it's weired that the server on.('message') event still receive packets! 
Why does it happen?

**Comment by lpinca** [comment] 2017-03-06 08:14
Closing this as the issue is 3 years old, please comment or reopen if needed.

**Closed by lpinca** 2017-03-06 08:14 UTC
