### ISSUE TITLE
node ws client wont connect to wss server

### ISSUE THREAD

**Issue by pkassonqh** [websockets/ws#1576] opened 2019-06-02 01:44 UTC
node ws client wont connect to wss server

Connecting to node ws server works fine ... added SSL cert (self signed) and HTTPS web server, all web pages work fine after accepting self signed cert.

When change ws client (node websocket/ws) to use wss, connection never works (oddly enough, a Java client still connects over ws: instead of wss:)

Browser console shows error:
   WebSocket network error: The operation couldn’t be completed. (OSStatus error -9847.)

Server connection code:  
    const wss = new WebSocket.Server({ port: 40510, server:  httpsServer });

Client connection code:
   ws = new WebSocket('wss://macpro:40510');

**Comment by lpinca** [comment] 2019-06-02 05:17
The issue template is there for a reason. Please fill it and provide a test case to reproduce the issue. Btw we have tests for this, see https://github.com/websockets/ws/blob/911bb6fb1145c9b09ae4b1cf4c993b3b8ce9e1cf/test/websocket.test.js#L1923-L1940 for example.

Since you are using a self signed certificate, you might only need to use the `rejectUnauthorized` option and set it to `false` as show in the above test.

**Comment by lpinca** [comment] 2019-06-03 19:23
I'm closing this, if you can please provide a reproducible test case and I will reopen.
Thank you.

**Closed by lpinca** 2019-06-03 19:23 UTC
