### ISSUE TITLE
send only in ws.on('connection')

### ISSUE THREAD

**Issue by cosimocelestegoglia** [websockets/ws#1826] opened 2020-12-18 14:17 UTC
#### Description
I make a websocket server, but the send function only available in the connection event

#### Reproducible in:

- version: 7.4.1
- Node.js version(s): 12.19.0
- OS version(s): windows 10

#### Steps to reproduce:
![image](https://user-images.githubusercontent.com/74128717/102648830-7decb080-4168-11eb-973b-800aabf7857f.png)
![image](https://user-images.githubusercontent.com/74128717/102648876-92c94400-4168-11eb-8f0d-36fbbab367b4.png)

**Comment by lpinca** [comment] 2020-12-18 16:57
There is no global send. [`send` is a method](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketsenddata-options-callback) of the `WebSocket` object.

Please fill the issue template. It's there for a reason.

**Comment by cosimocelestegoglia** [comment] 2020-12-18 18:39
@lpinca  i updated the issue, with also some screenshot

**Comment by lpinca** [comment] 2020-12-18 18:44
Yes this is by design. There is no `send` method on the WebSocket server.

**Comment by lpinca** [comment] 2020-12-18 18:46
You can use something like

```js
this.server.clients.forEach(function each(client) {
  if (client.readyState === WebSocket.OPEN) {
    client.send(data);
  }
});
```

if you want to send something to all clients.

**Comment by cosimocelestegoglia** [comment] 2020-12-18 19:14
What if I want to send a message to a single client, and not all of them?
Sorry for my bad english

**Comment by lpinca** [comment] 2020-12-18 20:27
Get the client you want to send the message to and call `send` on it.

**Comment by lpinca** [comment] 2020-12-18 20:57
See https://github.com/websockets/ws/issues/1308#issuecomment-366808059 for a basic example on how to use and identifier for every client and get a client by its identifier.

I'm closing this as it is not a bug in the library.

**Closed by lpinca** 2020-12-18 20:57 UTC
