### ISSUE TITLE
info.origin and info.req.headers.host issue in verifyClient after upgrade ws from 1.1.4 to 3.3.3

### ISSUE THREAD

**Issue by rutanika** [websockets/ws#1271] opened 2018-01-03 14:50 UTC
Hello, 

After we upgraded ws from 1.1.4 to 3.3.3 and did the adjustment as suggested in #1099, we get different behaviour in verifyClient. 
We recognized that in verifyClient info.origin comes without port and info.req.headers.host comes with port 443. 
Without the change both of them comes without the port.
Do you know what can be the reason for that? 

Thanks, 
Tali

node version: 6.0.0
platform: cf

**Comment by lpinca** [comment] 2018-01-03 15:28
I'm not sure, `info.origin` is just a shortcut to `req.headers['sec-websocket-origin']` or `req.headers.origin` depending on the protocol version.

Is the client a browser?

**Comment by rutanika** [comment] 2018-01-03 15:35
req.headers['sec-websocket-version'] is 13, therefor origin is req.headers['origin']

**Comment by rutanika** [comment] 2018-01-03 15:55
right, but I still don't understand why req.headers['origin'] comes without port and info.req.headers.host comes with port 443 :)

**Comment by lpinca** [comment] 2018-01-03 16:11
They are set by the client, are `origin` and `host` the same on 1.1.4? Is the client the same or are you using a different client?

**Comment by rutanika** [comment] 2018-01-03 17:01
Yes, on 1.1.4 origin and host are the same. 
The client is also the same. The only change is the version of ws and the adjustment for upgradeReq property.

**Comment by lpinca** [comment] 2018-01-03 17:28
`origin` is the same on both [`1.1.4`](https://github.com/websockets/ws/blob/24edef58a0aab05e8220f76bd2377614dd4eee85/lib/WebSocketServer.js#L207-L209) and [`3.3.3`](https://github.com/websockets/ws/blob/f941a4046481f1aa182aba11bb958e4306fd92fc/lib/WebSocketServer.js#L202), `host` is never touched so I don't really know.

Print `info.req.headers` and see if it is the same on both versions.

**Comment by rutanika** [comment] 2018-01-03 18:11
I already printed it and saw that the host has port 443 in 3.3.3 and does not has port at all in 1.1.4.

I open this github issue only after I printed it and saw the difference.

**Comment by lpinca** [comment] 2018-01-03 20:40
I cannot reproduce, here is my code.

```js
const https = require('https');
const fs = require('fs');
const WebSocket = require('.');

const data = `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <script>
      (function () {
        var ws = new WebSocket('wss://localhost:443');
      })();
    </script>
  </body>
</html>`;

const server = https.createServer({
  cert: fs.readFileSync('test/fixtures/certificate.pem'),
  key: fs.readFileSync('test/fixtures/key.pem')
});

server.on('request', (req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.end(data);
});

const wss = new WebSocket.Server({
  verifyClient (info) {
    console.log(info.origin);
    console.log(info.req.headers.host);
    return true;
  },
  server
});

wss.on('connection', (ws) => ws.close());

server.listen(443);
```

This prints the same stuff on both 1.1.4 and 3.3.3.

**Comment by lpinca** [comment] 2018-01-04 13:12
@rutanika I've also tested it on Firefox and it works the same on both 1.1.4 and 3.3.3.
Are you able to write a test to reproduce the issue?

**Comment by lpinca** [comment] 2018-01-05 09:11
Closing as I can't reproduce this, discussion can continue on the closed thread.

**Closed by lpinca** 2018-01-05 09:11 UTC

**Comment by rutanika** [comment] 2018-01-07 14:34
Hi, 
I will try to isolate the issue and create a standealone example that demonstrates what was done here. 
Thanks, 
Tali
