### ISSUE TITLE
Connection stuck in CLOSING state

### ISSUE THREAD

**Issue by zdila** [websockets/ws#1125] opened 2017-05-26 11:32 UTC
Probably it starts with some connection problem: `readyState` is set to 2 (CLOSING) and `close` event is never fired. Is this expected?

**Comment by lpinca** [comment] 2017-05-26 12:11
No it's not, when `ws.close()` is called a [timer](https://github.com/websockets/ws/blob/cb1c893ce94f3d800cd6e4166e6640bda24d74ab/lib/WebSocket.js#L295) is started to forcibly close the connection if the other peer fails to work properly.

Is there any way to reproduce this?

**Comment by zdila** [comment] 2017-05-26 12:13
But we are not calling `ws.close()` in this case. `readyState` gets to 2 probably because of network (or remote server) problem.

**Comment by lpinca** [comment] 2017-05-26 12:16
Yes but `readyState` is set to `CLOSING` only when the connection is being closed ([1](https://github.com/websockets/ws/blob/cb1c893ce94f3d800cd6e4166e6640bda24d74ab/lib/WebSocket.js#L284), [2](https://github.com/websockets/ws/blob/cb1c893ce94f3d800cd6e4166e6640bda24d74ab/lib/WebSocket.js#L182)).

**Comment by zdila** [comment] 2017-05-26 12:18
I'll try to collect some more details then.

**Comment by lpinca** [comment] 2017-05-26 12:18
The only thing I can think of is this [callback](https://github.com/websockets/ws/blob/cb1c893ce94f3d800cd6e4166e6640bda24d74ab/lib/WebSocket.js#L213) not being called but it's hard to tell why without a test case as it should be called in all cases.

**Comment by logidelic** [comment] 2017-06-22 15:05
Thanks for the response @lpinca. Some notes/questions

- My client (regular chrome websocket) pings the server regularly, and the server responds to the pings with pongs. My client will detect an unresponsive server and close the websocket (and try to reconnect).

- I don't really care if the server is unaware of the broken connection right away, but I was assuming that _eventually_ (i.e. when the browser closes that websocket connection with the server or if the browser window is closed), a "close" event would get emitted on the server-side for that connection. Have I misunderstood?

> Is the readyState stuck on CLOSING for more than 30 seconds in your case?

Yes, I believe that the "close" event _never_ gets emitted in certain cases. I will debug further to to confirm.

**Comment by lpinca** [comment] 2017-06-22 15:17
> My client (regular chrome websocket) pings the server regularly, and the server responds to the pings with pongs. My client will detect an unresponsive server and close the websocket (and try to reconnect).

I guess you are sending a text or binary frame as ping because afaik there is no way to send ping frames from the browser.

> I don't really care if the server is unaware of the broken connection right away, but I was assuming that eventually (i.e. when the browser closes that websocket connection with the server or if the browser window is closed), a "close" event would get emitted on the server-side for that connection. Have I misunderstood?

Generally this is true but there are cases where there is no way to know that the connection is broken. In these cases the connection is technically working and `OPEN` on the server and that's why you need an heartbeat system.

Anyway if your connections are stuck in `CLOSING` for more than 30 sec then there is a bug.

**Comment by logidelic** [comment] 2017-06-22 15:18
Yea, I'm using sending my own ping/pong text. I will test further and report back about the closing state.

**Comment by rsarili** [comment] 2017-08-15 12:48
Hi, I coming up with similar problem, my connection `readyState` stucks in `CLOSING` state when server close the connection. Here is my test case,
- client connects to server
- after some operations server close the connection
- client side got the `close` event
- I expect `close` event should be emitted in server-side too. I run server from localhost and from Azure service. In localhost it works but, in Azure service connection `readyState` stucks in `CLOSING` state for 30secs. I am not sure if this is a bug of 'ws' since it is work in localhost. This test case result every time like that, so I am not sure if it is a network problem. Do you have and idea of the reason? and Can you suggests to way handle that?

**Comment by lpinca** [comment] 2017-08-15 13:03
@rsarili since you have a way to reproduce the issue it would be great if you can verify a couple of things:

1. Check if this [callback](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L282-L293) is called and if `_closeTimer` is set.

2. Check if this [callback](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L210) is called.

**Comment by rsarili** [comment] 2017-08-15 13:37
@lpinca  Latter callback is not called in stuck case.
> 2. Check if this [callback](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L210) is called.

**Comment by lpinca** [comment] 2017-08-15 13:54
Wait, maybe I misunderstood. In your case is the connection stuck in `CLOSING` state indefinitely or just for 30 sec?

If it's only for 30 sec then there is no bug and it may be a network issue where the client fails to send a FIN packet to the server.

**Comment by rsarili** [comment] 2017-08-15 13:58
it is for only 30 sec, is there way to check FIN packet from code?

**Comment by lpinca** [comment] 2017-08-15 14:10
If everything works as expected you should first receive a close frame. You can verify if this happens by checking if [`receiver.onclose()`](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L149-L153) is called.

Then you should receive a FIN packet, you can check this by checking if this [callback](https://github.com/websockets/ws/blob/a1ac65994d59d46feb7b93ab1f91cd658394e301/lib/WebSocket.js#L131) is called (wrap it in another function).

Here is a diagram which should clarify how the closing handshake works:

```
            +----------+  +-----------+  +----------+
     - - - -|ws.close()|->|close frame|->|ws.close()|- - - -
    |       +----------+  +-----------+  +----------+       |
            +----------+  +-----------+        |
    |       |ws.close()|<-|close frame|<-------+            |
            +----------+  +-----------+        |
 CLOSING          |           +---+            |         CLOSING
                  |        +--|fin|<-----------+
    |             |        |  +---+                         |
                  |        |  +---+     +-------------+
    |             +--------+->|fin|---->|ws.finalize()| - - +
                           |  +---+     +-------------+
    |      +-------------+ |
     - - - |ws.finalize()|<+
           +-------------+
```

**Comment by rsarili** [comment] 2017-08-15 14:18
I will check those functions, thank you for diagram art.

**Comment by lpinca** [comment] 2017-11-21 06:54
Closing due to inactivity. If needed I will reopen this.

**Closed by lpinca** 2017-11-21 06:54 UTC

**Comment by portugaldev** [comment] 2018-01-24 21:48
I have this issue.

**Comment by pl-buiquang** [comment] 2018-03-14 17:19
I also have this issue.

**Comment by miroslavvojtus** [comment] 2018-03-26 16:13
We have a similar issue right now. Until upgrade from v 2.2.2 to 5.1.0 everything worked just fine. 
I mean, in most cases the connection was closed before a heartbeat (ping) was considered dead.
When the client shouted down the connection (power, manual process teardown) it almost instantly disconnected also the server (emitted "close" event).

Right now it newer emits close event until server fails to receive a "pong" response. What can take up to 30 seconds.

We are fine with it right now as in a case a send fails due to such a half-closed connection, it simply fails and we react to it manually. But still, it would be nice to have the close event as soon as the TCP is down as it currently emits unnecessary warn/error logs.

**Comment by inca** [comment] 2018-09-05 07:07
Same issue here. Server terminated abnormally, and client stuck in CLOSING indefinitely (no `close` event fired). Here's the WebSocket state I managed to collect:

<img width="649" alt="screen shot 2018-09-05 at 10 06 08" src="https://user-images.githubusercontent.com/118196/45076603-7b7aff80-b0f3-11e8-88bc-6dd9a33206bd.png">
