### ISSUE TITLE
socket error:  [Error: invalid stored block lengths]

### ISSUE THREAD

**Issue by sushiljainam** [websockets/ws#1136] opened 2017-06-08 14:37 UTC
anybody already got this?
can you explain this?

**Comment by lpinca** [comment] 2017-06-08 14:51
The issue template is there for a reason. This report is so vague that I'm tempted to close it immediately.

**Comment by lpinca** [comment] 2017-06-09 07:00
I've managed to reproduce this error by feeding random data to the inflate stream as per this SO question/answer: https://stackoverflow.com/questions/10577045/what-might-explain-an-invalid-stored-block-lengths-error.

```js
const crypto = require('crypto');
const WebSocket = require('ws');

const wss = new WebSocket.Server({
  perMessageDeflate: { threshold: 0 },
  port: 3000
}, () => {
  const ws = new WebSocket('ws://localhost:3000', {
    perMessageDeflate: { threshold: 0 }
  });

  ws.on('open', () => {
    ws._socket.write(Buffer.from([0xc2, 0x0a]));
    ws._socket.write(crypto.randomBytes(10));
  });
});

wss.on('connection', (ws) => {
  ws.on('error', (err) => console.error(err.stack));
});
```

The error message depends on the data being sent but after multiple runs I got:

```
Error: invalid stored block lengths
    at InflateRaw.zlibOnError (zlib.js:152:15)
```

**Comment by lpinca** [comment] 2017-06-09 12:36
Closing, feel free to continue discussing on the closed thread.

**Closed by lpinca** 2017-06-09 12:36 UTC

**Comment by yganatra** [comment] 2017-07-12 10:55
+1
I got this error when I tried to parse protected zip file.
Can someone help to resolve it?

**Comment by jukben** [comment] 2018-05-18 17:44
Hi there, we have run into the same issue in https://github.com/callstack/haul/

I've tried to catch this error by

```js
webSocket.on('error', error => {
  console.log(error);
});
```

but without luck.

I think this problem is related due to we are trying to send ~40 MB (42633238b) file over WS. Is it possible?

Intresting fact is that we are not using `perMessageDeflate` (it's disabled by default).

The most surprising thing is that I can hotfix this and get the expected behavior with options (passed to `new Server`)

```js 
maxPayload: 100 * 1024 * 1024 // this is way over 40 MB right...
```

Do you have any explanation? I would like to help fix it. But I'm really confused.

cc @lpinca

**Comment by lpinca** [comment] 2018-05-18 19:01
No, it doesn't make much sense, if permessage-deflate is disabled I can't see how this can happen.

**Comment by lpinca** [comment] 2018-05-18 19:05
In [`ws@2.2.2`](https://github.com/callstack/haul/blob/127abe20893d99192ff760f06803eacbb637e092/package.json#L75), permessage-deflate is not disabled by default.

**Comment by jukben** [comment] 2018-05-21 07:55
I've tried to track it down but I wasn't successful. It's absolutely strange. I might try to create some repro repo for you because I really don't know where could be the other place which calls `(pako) zlib.js` – and why `maxPayload` "solved" it.

**Comment by lpinca** [comment] 2018-05-22 19:01
@jukben are you sending the the file as a single frame or is the message fragmented?

**Comment by jukben** [comment] 2018-05-22 21:30
@lpinca I hope it's text in a single frame (https://github.com/callstack/haul/blob/next/src/compiler/worker/initWorker.js#L83) we are using memory-fs (https://github.com/webpack/memory-fs/blob/master/lib/MemoryFileSystem.js#L99).

Could you guide me how can I test it? I tried to do some magic with Whireshark but not sure what I'm looking for.

**Comment by lpinca** [comment] 2018-05-23 06:04
@jukben can you share an of the string that is sent? Like save it on a file and attach it here?

**Comment by jukben** [comment] 2018-05-23 07:57
Thanks a lot for this assisted debugging. I've realized that memory-fs is returning Buffer by default so we are serializing a buffer. This another example is in buffer version ~25 MB, when I have converted the Buffer to utf-8 text I got ~7 MB. So that makes sense regarding the size.

```js
{"type":"FILE_RECEIVED","taskId":0,"file":{"type":"Buffer","data":[105,102,32,40,116,104,105,115,32,38,38,32,33,116,104,105,115,46,115,101,108,102,41,32,123,32,116,104,105,115,46,115,101,108,102,32,61    ,32,116,104,105,115,59,32,125,59,10,10,47,42,42,42,42,...]}, "mimeType": "text/javascript"}
```

**Comment by lpinca** [comment] 2018-05-23 08:11
Ok yes it makes sense, but using a JSON stringified buffer sounds like very inefficient.
Anyway, for a message that is not fragmented and uncompressed, max size is based on the length of the buffer that is being sent. If you are sending a string that is `Buffer.byteLength(string, 'utf8')`.

**Comment by jukben** [comment] 2018-05-23 08:15
Thanks again for your help! I feel the same. I don't know why we are stringifying the Buffer anyway I have to get back to the other maintainers of Haul and we will figure it out.  💪
