### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by vitaliystoliarovcc** [websockets/ws#1889] opened 2021-05-24 13:41 UTC
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

~~`close` and `terminate` do not always free the memory~~
Garbage collection is completely performed only after a few minutes after ws is closed and terminated (even with force garbage collection)

#### Reproducible in:

- version: 7.4.5
- Node.js version(s): v12.22.1
- OS version(s): Ubuntu 18

#### Steps to reproduce:

1. Create file
```js
const WebSocket = require('ws')
const restify = require('restify')

const server = restify.createServer()

server.get('/', async (req, res, next) => {
  const ws = new WebSocket('wss://api.bitfinex.com/ws/')

  ws.on('error', () => {})
  setTimeout(() => {
    ws.close()
    ws.terminate()
  }, 1000)
  res.send()
  next()
})

server.listen(3000)
```

2. Install `autocannon` and `restify`

3. Run `node --inspect basic.js`

4. Open `Memory` tab in DevTools - Node.js and create snapshot

5. Run `autocannon -c 2 localhost:3000` in the different terminal

6. wait a couple of minutes for GC to clear the memory

7.  Create snapshot

#### Expected result:

Latest snapshot should display the same amount of memory as in step 4

#### Actual result:

Latest snapshot displays about 15-20MB

#### Attachments:

![image](https://user-images.githubusercontent.com/70510980/119353627-caa25d80-bcab-11eb-83d0-1bab86324cd3.png)

UPD: https://github.com/websockets/ws/issues/1889#issuecomment-847645125

**Comment by lpinca** [comment] 2021-05-24 18:33
I'm on Node.js 16.2.0 and macOS but I can't reproduce. Ran `autocannon` after every snapshot and waited ~4 min before taking the snapshots.

<img width="760" alt="Screen Shot 2021-05-24 at 20 32 16" src="https://user-images.githubusercontent.com/1443911/119391920-4b268580-bccf-11eb-8f38-bc2f064584b2.png">
<img width="761" alt="Screen Shot 2021-05-24 at 20 32 40" src="https://user-images.githubusercontent.com/1443911/119391934-51b4fd00-bccf-11eb-9006-04bda09328ae.png">
<img width="760" alt="Screen Shot 2021-05-24 at 20 33 09" src="https://user-images.githubusercontent.com/1443911/119391954-57aade00-bccf-11eb-8cd1-32378b3ccb85.png">

**Comment by vitaliystoliarovcc** [comment] 2021-05-25 08:02
Indeed, if we wait longer, the memory is cleared (for example, after 3.5 minutes on the screenshot below), but not always completely


![image](https://user-images.githubusercontent.com/70510980/119460592-84024100-bd47-11eb-9396-9d11fa64a915.png)

after 6 minutes some closures remained in memory (possibly related only to 'restify')

![image](https://user-images.githubusercontent.com/70510980/119461094-0a1e8780-bd48-11eb-9c3d-ca8f370dc1ad.png)

**Comment by lpinca** [comment] 2021-05-25 08:28
I think because there is plenty of memory available so it does not aggressively try reclaim memory.

**Comment by vitaliystoliarovcc** [comment] 2021-05-25 08:44
but it should clear the memory immediately when you click on the "Collect garbage" button, isn't?

**Comment by lpinca** [comment] 2021-05-25 08:50
I don't know. You can try forcing garbage collection with `global.gc()` and using the [`--max-old-space`](https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_megabytes) option. Garbage collectors are scary beasts.

**Comment by lpinca** [comment] 2021-05-25 10:40
I'm closing this as it does not seem to be an issue in ws. Discussion can continue if needed.

**Closed by lpinca** 2021-05-25 10:40 UTC
