### ISSUE TITLE
Upgrade required 

### ISSUE THREAD

**Issue by totovr** [websockets/ws#1501] opened 2019-02-06 05:41 UTC
Hello I'm trying to share some data with ws but I can just access in a local way in my own pc

- version:
- Node.js 11.8.0
- Ubuntu 18.04

The code that I use for the `server.js` is:

```js
var SerialPort = require('serialport');// include the library
// get port name from the command line:
var portName = process.argv[2];
// Setup the port
var myPort = new SerialPort(portName, { baudRate: 115200 });
var Readline = SerialPort.parsers.Readline; // make instance of Readline parser
var parser = new Readline(); // make a new parser to read ASCII lines

var WebSocketServer = require('ws').Server;
var SERVER_PORT = 8081;               // port number for the webSocket server
var wss = new WebSocketServer({ port: SERVER_PORT }); // the webSocket server
var connections = new Array;          // list of connections to the server

// Events for the serial reading
myPort.pipe(parser); // pipe the serial stream to the parser
myPort.on('open', showPortOpen);
parser.on('data', readSerialData);
myPort.on('close', showPortClose);
myPort.on('error', showError);

// Event for the socket connection 
wss.on('connection', handleConnection);

function handleConnection(client) {
   console.log("New Connection"); // you have a new client
   connections.push(client); // add this client to the connections array
   client.on('message', sendToSerial); // when a client sends a message,
   client.on('close', function () { // when a client closes its connection
      console.log("connection closed"); // print it out
      var position = connections.indexOf(client); // get the client's position in the array
      connections.splice(position, 1); // and delete it from the array
   });
}

function showPortOpen() {
   console.log('port open. Data rate: ' + myPort.baudRate);
}

function readSerialData(data) {
   // console.log(data);
   // if there are webSocket connections, send the serial data
   // to all of them:
   if (connections.length > 0) {
      broadcast(data);
   }
}

function showPortClose() {
   console.log('port closed.');
}

function showError(error) {
   console.log('Serial port error: ' + error);
}

function sendToSerial(data) {
   console.log("sending to serial: " + data);
   myPort.write(data);
}

// This function broadcasts messages to all webSocket clients
function broadcast(data) {
   for (myConnection in connections) {   // iterate over the array of connections
      connections[myConnection].send(data); // send the data to each connection
   }
}
```
and form the `client.js` is:

```js
var text;     // variable for the text div you'll create
var socket = new WebSocket("ws://localhost:8081");

var value;

function setup() {
    createCanvas(1200, 100);
    // The socket connection needs two event listeners:
    socket.onopen = openSocket;
    socket.onmessage = showData;
    // make a new div and position it at 10, 10:
    text = createDiv("Sensor reading: ");
    text.position(40, 50);
}

function draw() {
    if (value == 0) {
        background(120);
    } else if (value == 1023) {
        background(220);
    }
}

function openSocket() {
    text.html("Socket open");
    socket.send("Hello server");
}

function showData(result) {
    // when the server returns, show the result in the div:
    value = map(result.data, 0, 4095, 0, 1023);
    text.html("Sensor reading: " + value);
    var xPos = int(value);        // convert result to an integer
    if (xPos != 0) {
        text.position(xPos, 50);        // position the text
    } else if (xPos == 0) {
        text.position(xPos + 40, 50);
    }
}
```
the `index.html` is:

```html
<!DOCTYPE html>
<html>

<head>
   <meta charset="utf-8">
   <title>Serial connection</title>

   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.js"></script>
   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.dom.js"></script>
   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.sound.js"></script>
   <script type="text/javascript" src="client.js"></script>

</head>

<body>

</body>

</html>
```

The outputs in the same pc is:

![image](https://user-images.githubusercontent.com/15333235/52322622-2da95100-2a1d-11e9-9051-523b7589f2fc.png)

![image](https://user-images.githubusercontent.com/15333235/52322662-474a9880-2a1d-11e9-9a07-3cbef3d3ca3e.png)

**Comment by lpinca** [comment] 2019-02-06 07:04
This is because the request to `10.31.1.66:8081` is answered with `426` instead of the actual contents of `index.html`. This works as intended as per https://github.com/websockets/ws/blob/b45e9121f4a1f067a142c0fb4f2fae65658e90fc/lib/websocket-server.js#L62-L68

To make it work use something like this:

```js
const http = require('http');
const WebSocket = require('ws');

const server = http.createServer(function(req, res) {
  // send `index.html`;
});

const wss = new WebSocket({ server });

server.listen(8081);
```

**Comment by totovr** [comment] 2019-02-06 08:06
Thanks @lpinca, I add this code in the server as you commented above:

```js
var sensorData; // Data acquired by the sensor
const server = http.createServer(function (req, res) {
   res.writeHead(200, { 'Content-Type': 'text/plain' });
   // res.write('Hello World!');
   res.write(sensorData.toString());
   res.end();
});
```
But is just showing the string as below:
![image](https://user-images.githubusercontent.com/15333235/52327986-6f43f700-2a31-11e9-9923-e45e1c623653.png)

But is not showing nothing of the `client.js`

**Comment by lpinca** [comment] 2019-02-06 08:33
Your server should reply to requests with the correct data. Assume the following is the `'request'` event listener you pass to `http.createServer()`;

```js
function handler(req, res) {
  if (req.url === '/' || req.url === '/index.html') {
    res.writeHead(200, { 'Content-Type': 'text/html' });
    res.end(/* index.html contents */);
  } else if (req.url === '/client.js') {
    res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
    res.end(/* client.js contents */);
  }
}
```

**Comment by totovr** [comment] 2019-02-06 10:46
Now the request is working with:

```js
const server = http.createServer(function (req, res) {
   if (req.url === '/' || req.url === '/index.html') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.write('<title>Serial connection</title>');
      res.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.js"></script>');
      res.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.dom.js"></script>');
      res.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.sound.js"></script>');
      res.write('<script type="text/javascript" src="client.js"></script>');
      res.end(/* index.html contents */);
   } else if (req.url === '/client.js') {
      res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
      res.write('var text;     var socket = new WebSocket("ws://localhost:8081"); var value;');
      res.write('function setup() { createCanvas(1200, 100); socket.onopen = openSocket; socket.onmessage = showData; text = createDiv("Sensor reading: "); text.position(40, 50);}');
      res.write('function draw() { if (value == 0) { background(120); } else if (value == 1023) { background(220); }}');
      res.write('function openSocket() { text.html("Socket open"); socket.send("Hello server"); }');
      res.write('function showData(result) { value = map(result.data, 0, 4095, 0, 1023); text.html("Sensor reading: " + value); var xPos = int(value); if (xPos != 0) { text.position(xPos, 50); } else if (xPos == 0) { text.position(xPos + 40, 50); } }');
      res.end(/* client.js contents */);
   }
});
```

If I connect with another pc is not openning the connection due too is a http protocol, is it possible to add https protocol? I saw the example code:

```js
const fs = require('fs');
const https = require('https');

const server = new https.createServer({
  cert: fs.readFileSync('/path/to/cert.pem'),
  key: fs.readFileSync('/path/to/key.pem')
});
```

**Comment by totovr** [comment] 2019-02-06 11:20
I modified in this way:

```js
const fs = require("fs"),
   https = require("https");

var handler = function (req, res) {
   if (req.url === '/' || req.url === '/index.html') {
      res.writeHead(200, { 'Content-Type': 'text/html' });
      res.write('<title>Serial connection</title>');
      res.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/p5.js"></script>');
      res.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.dom.js"></script>');
      res.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.7.3/addons/p5.sound.js"></script>');
      res.write('<script type="text/javascript" src="client.js"></script>');
      res.end(/* index.html contents */);
   } else if (req.url === '/client.js') {
      res.writeHead(200, { 'Content-Type': 'application/javascript; charset=utf-8' });
      res.write('var text;     var socket = new WebSocket("ws://localhost:8081"); var value;');
      res.write('function setup() { createCanvas(1200, 100); socket.onopen = openSocket; socket.onmessage = showData; text = createDiv("Sensor reading: "); text.position(40, 50);}');
      res.write('function draw() { if (value == 0) { background(120); } else if (value == 1023) { background(220); }}');
      res.write('function openSocket() { text.html("Socket open"); socket.send("Hello server"); }');
      res.write('function showData(result) { value = map(result.data, 0, 4095, 0, 1023); text.html("Sensor reading: " + value); var xPos = int(value); if (xPos != 0) { text.position(xPos, 50); } else if (xPos == 0) { text.position(xPos + 40, 50); } }');
      res.end(/* client.js contents */);
   }
};

const server = new https.createServer({
   cert: fs.readFileSync('cert.pem'),
   key: fs.readFileSync('key.pem')
});

server.addListener("request", handler);
```

But is not responding:
![image](https://user-images.githubusercontent.com/15333235/52338040-9bb93c80-2a4c-11e9-8dea-1fb9866665b8.png)

**Comment by lpinca** [comment] 2019-02-06 11:27
Use `wss://` in the connection URL in `client.js`. If the cert is self signed you might need to manually add and exception in the browser.

Anyway I'm going to close this as it's not a ws issue, please use another channel for support questions.

**Closed by lpinca** 2019-02-06 11:27 UTC
