### ISSUE TITLE
Server port stays in use after `close()` method call

### ISSUE THREAD

**Issue by lonelyelk** [websockets/ws#527] opened 2015-07-08 13:52 UTC
It seems there is no way to tell, when server address and port are stopped being used:

``` javascript
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({port:9000});
wss.close();
wss = new WebSocketServer({port:9000});
```

This gives EADDRINUSE on both node v0.12.6 and iojs v2.3.3. If this is an asynchronous method, than there should be a callback but `wss.on('close', fn)` is never called.

The problem appears when trying to test something that requires creation of the same server in `beforeEach`.

**Comment by Eeems** [comment] 2015-07-14 17:59
+1 on this. I'm racking my brain currently attempting to figure out a way to wait until it's free. It's causing problems with some hot-reloading I'm trying to get working.

**Comment by woverton** [comment] 2015-08-26 09:40
+1

**Comment by woverton** [comment] 2015-08-26 09:44
Right, I did a little hunting and found this https://github.com/joyent/node/issues/55

It turns out that ws is doing nothing wrong.

```this_server``` is a simple node http server, and then ws calls close on it.

https://github.com/websockets/ws/blob/master/lib/WebSocketServer.js#L59

**Comment by Eeems** [comment] 2015-08-26 13:25
@woverton the problem is that there is no exposed way to pass a callback for after the connection finally closes. WS closes it fine, but you run into timing issues due to t knowing if its closed yet or not.

**Comment by woverton** [comment] 2015-08-26 13:28
I know, It's just the error exists in node http not the lib. I cant see that anything can be done unless you want to switch to another port or something I'm afraid...

(I'm not a ws dev, just looked at the code and then did some digging)

**Comment by Eeems** [comment] 2015-08-26 13:32
Nodes http server has a callback at fires after the port is released. All ws needs to do is expose it. https://nodejs.org/api/http.html#http_event_close

**Comment by woverton** [comment] 2015-08-26 14:46
I tried making the change. It didn't seem to work however...

https://github.com/woverton/ws/commit/131c5e96dabf4318e1981564bc82058c985e4d56

**Comment by Eeems** [comment] 2015-08-26 14:57
Interesting. I've not had problems with it when I'm us in it with http servers manually. What version of nodejs are you using?

**Comment by woverton** [comment] 2015-08-26 15:02
With just http servers it works fine, I tested that once confused.

**Comment by woverton** [comment] 2015-08-26 15:05
I think it may be todo with this line here: https://github.com/woverton/ws/blob/131c5e96dabf4318e1981564bc82058c985e4d56/lib/WebSocketServer.js#L137

**Comment by woverton** [comment] 2015-08-26 15:06
We might be deleting the server before it fully finishes closing

**Comment by woverton** [comment] 2015-08-26 15:13
Interestingly:

```
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({port:9000});

wss.close(function(){
    setTimeout(function(){
        wss = new WebSocketServer({port:9000});
    }, 10000);
});
```

Still doesnt work. Which means that ws isn't closing it at all....

**Comment by Eeems** [comment] 2015-08-26 23:19
Unless there is something wrong with your changes. Reviewing them now.

**Comment by woverton** [comment] 2015-08-27 15:08
Good thinking but that doesn't seem to help :/

**Comment by woverton** [comment] 2015-08-27 15:20
Maybe actually. setting my own http server and closing that did work however.

```
var http = require('http');

var server = http.createServer(function(request, response) {
    console.log((new Date()) + ' Received request for ' + request.url);
    response.writeHead(404);
    response.end();
});

server.listen(9000, function() {
    console.log((new Date()) + ' Server is listening on port 8080');
});

var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({server: server});

setTimeout(function(){
    server.close(function(){
        console.log("Closed...");
        wss = new WebSocketServer({port:9000});
    });
}, 1000);
```

This could mean that the ```this. _server``` object is either not getting set correctly, or is accidentally being cloned? or something weird. The callback does get called back, but it appears the close method is no longer linked to the actual http server.

**Comment by Eeems** [comment] 2015-08-27 16:03
I'll take a closer look. You could also try throwing some console logging into there to see what happens to _closeServer

**Comment by woverton** [comment] 2015-08-28 10:55
Boom ! https://github.com/woverton/ws/commit/8edf58f55daa5ff33c8f93b3321ef94c4db29e65

Works for me now :)

My test app:

```
var http = require('http');

// var server = http.createServer(function(request, response) {
//     console.log((new Date()) + ' Received request for ' + request.url);
//     response.writeHead(404);
//     response.end();
// });

// server.listen(9000, function() {
//     console.log((new Date()) + ' Server is listening on port 8080');
// });

var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({port: 9000});
// var wss = new WebSocketServer({server: server});

// setTimeout(function(){
//     server.close(function(){
//         console.log("Closed...");
//         wss = new WebSocketServer({port:9000});
//     });
// }, 1000);

setTimeout(function(){
    wss.close(function(){
        console.log("Closed...");
        wss = new WebSocketServer({port:9000});
    });
}, 1000);
```

If you could give it a little test and let me know, the I'll open a pull request

**Comment by Eeems** [comment] 2015-08-28 17:59
Hmm, looks like you have some scope problems. I'd suggest changing it to this:
```javascript
var self = this;
this._server.once('close', function(){
    cb.apply(this,arguments);
    delete self._server;
});
if(typeof this._closeServer !== 'undefined'){
    this._closeServer();
}
```

**Comment by woverton** [comment] 2015-09-02 09:39
hmm, might be better to just bind() the function for this one case.

Did you get any errors or did you just spot it and think it may cause errors in the future?

**Comment by Eeems** [comment] 2015-09-02 13:32
Not quite re  bind would be better then once here.

I spotted it while reading your code.

**Comment by lpinca** [comment] 2016-12-27 07:18
Should be fixed on master. Closing, please reopen if the issue persists.

**Closed by lpinca** 2016-12-27 07:18 UTC

**Comment by rradczewski** [comment] 2017-05-18 13:41
Hi, looks like this bug is in still/again present on node versions `<v7.0.0`.

I checked the [changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#7.0.0) briefly but found nothing noting a change in `http` that could've fixed this.

Upgrading to node `>=v7.0.0` fixes the issue for me.

### Dirty fix on Node v6.10.3
I found that calling `server.close()` after calling `close()` on the websocket server fixes this issue:

```js
var WebSocketServer = require('ws').Server;
var wss = new WebSocketServer({port:9000});

const server = wss._server;

wss.close(function(){
    server.close();
    setTimeout(function(){
        wss = new WebSocketServer({port:9000});
    }, 1000);
});
```

**Comment by lpinca** [comment] 2017-05-18 14:00
@rradczewski can you reproduce without `ws`? We call [`server.close()`](https://github.com/websockets/ws/blob/38df5a330aa91123851d8b49c231adf6c337ea77/lib/WebSocketServer.js#L120) internally and forward the callback to it.

Are you calling `wss.close()` on the same tick?

**Comment by rradczewski** [comment] 2017-05-18 16:14
Hi @lpinca, thanks for answering so quickly and thanks for your work on `ws`!

The testcase above is enough to reproduce the error (just comment out `server.close()` on node `v6.10.3`). Apparently it helps to call `server.close()` twice, once in your implementation and once outside.

I'm pretty sure this is not related to `ws`, but I figured I add it to this issue as I stumbled upon it through using `ws` in my tests.

I will try to come up with a testcase without `ws` and then open an issue with node itself.

Cheers!

**Comment by rradczewski** [comment] 2017-05-19 16:17
Soo, looks like that's [wanted behavior](https://nodejs.org/dist/latest-v6.x/docs/api/net.html#net_server_close_callback): The server does not close if it wasn't open in the first place.

So yeah, everything is behaving like it should, it's just me using it wrong 😅. 

```
const http = require('http');

const launchServer = () => {
  const server = http.createServer();
  server.listen(8000, null, null, () => {
    console.log('Listening');
  });
  server.close((e) => {
    console.log('Closed', e); // e is an error here
    setTimeout(launchServer, 1000);
  });
}

launchServer();
```

**Comment by lpinca** [comment] 2017-05-19 16:25
Yup I was exactly thinking at a race condition between `listen()` and `close()`. I guess in Node.js 6 the server is actually bound after the `close()` call so that's probably why you need that second `close()` on the next tick.

This is just a guess though 😄.

**Comment by Xan-Kun** [comment] 2017-06-08 21:42
Is there any way to close the server and give a code and reason to the browser? I could not get it to work, the code is always 1006 and the reason always empty.

**Comment by lpinca** [comment] 2017-06-09 05:24
@Xan-Kun no there isn't. In that case you have to stop accepting new connections and close all clients gracefully.

```js
const http = require('http');
const ws = require('ws');

const server = http.createServer();
const wss = new WebSocket.Server({ server });

server.listen(3000, () => {
  // Close all clients with a non default code and reason after 30s.
  setTimeout(() => {
    server.close(() => wss.close());
    wss.clients.forEach((ws) => ws.close(code, reason));
  }, 30000);
});
```
