### ISSUE TITLE
RangeError: out of range index crashing server

### ISSUE THREAD

**Issue by j-mcnally** [websockets/ws#778] opened 2016-07-12 05:00 UTC
```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/Users/jmcnally/projects/nextlot-projects/nextlot-webcast-rtc/node_modules/ws/lib/Receiver.js:317:24)
    at Receiver.add (/Users/jmcnally/projects/nextlot-projects/nextlot-webcast-rtc/node_modules/ws/lib/Receiver.js:78:3)
    at Socket.firstHandler (/Users/jmcnally/projects/nextlot-projects/nextlot-webcast-rtc/node_modules/ws/lib/WebSocket.js:663:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

Not really sure what this means or how to fix, or where the problem is actually.

**Comment by rkaw92** [comment] 2016-07-12 08:21
Also seeing this with ws@0.8.0 (required by our engine.io version) on Node 6.3.0.

```
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/home/debian/GEOS/b2b/node_modules/ws/lib/Receiver.js:386:24)
    at Receiver.add (/home/debian/GEOS/b2b/node_modules/ws/lib/Receiver.js:86:3)
    at Socket.realHandler (/home/debian/GEOS/b2b/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Socket.Readable.push (_stream_readable.js:135:10)
    at TCP.onread (net.js:542:20)
```

The final line of the stack trace seems to be doing a call to Buffer#copy(). This is right after an upgrade from 0.12.

**Comment by fippo** [comment] 2016-07-14 05:18
i also saw this, after upgrading to node 6.3.0. The first argument to fastCopy is -1 which is clearly odd.
Anecdotally I am also seeing a lot of off-by-one errors where the last data byte is not delivered.

**Comment by j-mcnally** [comment] 2016-07-14 17:09
upgrading to 1.1.1 resolved this issue for me.

**Comment by rkaw92** [comment] 2016-07-14 17:36
I concur. Upgrading to 1.1.1 (got pulled automatically by npm when upgrading to a newer socket.io release) has resolved this. May be beneficial to close the issue, but leave it here for posterity.

**Comment by j-mcnally** [comment] 2016-07-15 00:09
Yes best bet is to PR / open issues with packages depending on old
versions. Kurento in my case.

On Thursday, July 14, 2016, Robert Kawecki <notifications@github.com> wrote:

> I concur. Upgrading to 1.1.1 (got pulled automatically by npm when
> upgrading to a newer socket.io release) has resolved this. May be
> beneficial to close the issue, but leave it here for posterity.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/websockets/ws/issues/778#issuecomment-232736355>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA2d3vOnIwZo9R8g8ZNMGFynr79e12__ks5qVnOHgaJpZM4JKCYP>
> .
>


-- 

<http://www.kohactive.com>
Justin McNally
Technology Director / Principal
p: 312.273.3074 <+13122733074> | e: justin@kohactive.com | skype:
justinmcnally211 <http://is.gd/UuXAGG>
  <https://github.com/j-mcnally>  <https://twitter.com/j_mcnally>
<https://www.linkedin.com/profile/view?id=143776726>

**Comment by FalloutPL** [comment] 2016-07-20 13:19
I think problem is much worse. See this:

Send ok:
> [2016-07-20T12:44:17.705Z] TRACE: ts_lib/11413 on GlobeTwo: Sending data...
>     data: {"method":"virtual.setProperties","params":{"virtual":65429,"properties":{"versionTs":1469018657705}},"id":1847}
> [2016-07-20T12:44:17.757Z] TRACE: ts_lib/11413 on GlobeTwo: Message received.
>     data: {"type":"result","id":1847,"result":true}
> 

server got it ok:

> 2016-07-20 12:44:17.705 [info] <0.12884.0>@stl2_api_session:try_parse_incoming_json:257 [<<"devsuperuser">>] incomming json: {"method":"virtual.setProperties","params":{"virtual":65429,"properties":{"versionTs":1469018657705}},"id":1847}
> 2016-07-20 12:44:17.757 [info] <0.12884.0>@stl2_api_session:send_encoded_response:178 [<<"devsuperuser">>] outgoing json: {"type":"result","id":1847,"result":true}

next:

> [2016-07-20T12:44:17.931Z] TRACE: ts_lib/11413 on GlobeTwo: Sending data...
>     data: {"method":"virtual.setProperties","params":{"virtual":934,"properties":{"versionTs":1469018657931}},"id":1849}
> [2016-07-20T12:44:17.932Z] TRACE: ts_lib/11413 on GlobeTwo: Message received.
>     data: {"type":"error","id":0,"reason":"invalid_json"}

because:

> 2016-07-20 12:44:17.931 [info] <0.12884.0>@stl2_api_session:try_parse_incoming_json:257 [<<"devsuperuser">>] incomming json: {"method":"virtual.setProperties","params":{"virtual":934,"properties":{"versionTs":1469018657931}},"id":1849
> 2016-07-20 12:44:17.932 [warning] <0.12884.0>@stl2_api_session:invalid_json_response:441 Received malformed json, detailed error message: {110,truncated_json}
> 2016-07-20 12:44:17.932 [info] <0.12884.0>@stl2_api_session:send_encoded_response:178 [<<"devsuperuser">>] outgoing json: {"type":"error","id":0,"reason":"invalid_json"}

as you see server did not recieved last "}" 

i have NodeJS 6.3.0 and updated to lastest socket.io because of "RangeError: out of range index" mentioned at start.

**Comment by xBytez** [comment] 2016-07-21 14:17
I'm experiencing both the "Out of range index"  and "Unexpected end of JSON input" error after upgrading to node.js 6.3.0. I'm not using socket.io but just the WS module on it's own.

**Comment by sushantdhiman** [comment] 2016-07-26 07:16
Using the latest `v1.1.1` along with Node `v6.2.0` resolves this issue. But upgrading to `Node v6.3.0` make this issue reappear

**Comment by rkaw92** [comment] 2016-07-26 07:25
@sushantdhiman you sure your dependencies were not reset? I have not seen this behaviour after upgrading to Node 6.3.0.

**Comment by shaniceweiwei** [comment] 2016-07-27 03:58
stupid question... how do i upgrade ws to 1.1.1?

**Comment by sushantdhiman** [comment] 2016-07-27 05:21
`npm install --save ws@latest` will do

**Comment by sushantdhiman** [comment] 2016-07-27 05:24
@rkaw92 same dependencies switch to `Node v6.3` , I will get buffer errors.  But switch to `Node v6.2` everything works.

**Comment by shaniceweiwei** [comment] 2016-07-27 06:28
@sushantdhiman how to switch to v6.2? i'm on sw@1.1.1 and node@6.3.0... the same problem never goes. :(

**Comment by sushantdhiman** [comment] 2016-07-27 06:42
I use [nvm](https://github.com/creationix/nvm) to manage the node versions

**Comment by deep9** [comment] 2016-09-20 08:03
I can confirm the problem also on `Node v6.5.0`, but with `ws@0.5.0`. Now trying on `ws@1.1.0` (socket.io dependency)

**Comment by coffenbacher** [comment] 2016-09-26 21:58
@deep9 any luck? I'm getting this as well on `Node v6.6.0` and `ws@0.8.1`

**Comment by vainly** [comment] 2016-10-10 10:27
I can confirm the problem also on Node v6.6.0  with ws@1.1.1 in windows7

**Comment by yosheeck** [comment] 2016-12-15 09:09
Just a report: 
I confirm seeing that quite often with <1.0 version, and I confirm **in 1.1.1 it doesn't happen anymore** (in the same conditions). I think it's fixed.

**Comment by lpinca** [comment] 2016-12-19 17:38
@yosheeck thanks. I close this, please comment/reopen if needed.

**Closed by lpinca** 2016-12-19 17:38 UTC

**Comment by theturtle32** [comment] 2016-12-29 01:49
Anybody know what was the cause of this? The stack trace doesn't include any library code, only node internals.

**Comment by lazamarius** [comment] 2017-04-04 07:03
Hi,
I see this issue again with node 6.5.0 and WS 1.1.1.
Tue, 04 Apr 2017 03:48:03 GMT [Process-app] uncaughtException: out of range index
RangeError: out of range index
    at RangeError (native)
    at fastCopy (/var/execui/node_modules/ws/lib/Receiver.js:414:24)
    at Receiver.add (/var/execui/node_modules/ws/lib/Receiver.js:94:3)
    at Socket.realHandler (/var/execui/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)

Can anyone help on this?

**Comment by lpinca** [comment] 2017-04-04 07:10
@lazamarius I recommend to upgrade to `ws@2`.

**Comment by lazamarius** [comment] 2017-04-04 07:13
@lpinca , thanks, will try that.
Do you know how I can reproduce this issue to test after the upgrade?

**Comment by lpinca** [comment] 2017-04-04 07:15
@lazamarius it seems that the issue is cause by a wrong? value here https://github.com/websockets/ws/blob/c7bb7306cb0e1d17df141f61a220056eaa5e3502/lib/Receiver.js#L414. Not sure which one though.

It might makes sense to also use a different Node.js version as it seems, from the comments above, that 6.5.0. was particularly affected.

**Comment by FrancooHM** [comment] 2017-05-18 22:44
Using 

"socket.io": "^1.7.3",
"ws": "^2.2.3"

and having the issue: Caught exception: RangeError: out of range index

On node v6.6.0

**Comment by lpinca** [comment] 2017-05-19 05:18
@FrancooHM socket.io@1.7.3 uses engine.io@1.8.3 which uses ws@1.1.2 not ws@2.

**Comment by FrancooHM** [comment] 2017-05-19 13:04
hi @lpinca.

thanks, for your quick answer. There is a stable setup you could advice for production enviroment ?
Or there is recomended version dependency list ?

**Comment by lpinca** [comment] 2017-05-19 13:08
I don't use Socket.IO so I can't really answer.

**Comment by MonkeyDo** [comment] 2017-05-19 13:13
@FrancooHM I've been using an npm-shrinkwrap file to force an adequate version of ws package is use by dependencies. So far no problem.

**Comment by FrancooHM** [comment] 2017-05-19 13:17
that's ok @lpinca. 

ok @MonkeyDo thanks a lot i will try. If a fix i will post my setup here again to the posterity, thanks again everybody.

**Comment by FrancooHM** [comment] 2017-05-19 23:44
@lpinca would you recommend to update to:
- socket.io 2.0.1
- engine.io 3.1.0
- ws 2
- node 6.6.0

?

after reading deeply all this thread i don't really get wich version of node works with ws1.x or ws2.x

**Comment by lpinca** [comment] 2017-05-20 04:59
@FrancooHM if you use `ws@>=2` you should be fine will all supported Node.js versions (4+).
