### ISSUE TITLE
ECONNRESET on sending data to a socket while status pre-check "WebSocket.readyState === "OPEN" is true

### ISSUE THREAD

**Issue by jacobbogers** [websockets/ws#1794] opened 2020-09-02 13:19 UTC
- [x] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

It doesn't happen alot but the WebSocket.readyState (on serverside) is checked before we consider sending data over the ws back to client , the states is "OPEN" but when sending we get "

`Error: write ECONNRESET`

some things about the socket on server side
- it is not removed from `clients` (aka `wss.clients`)
- the readyState is "OPEN" (we do explicit check before we send anything)
- calling `ws.terminate()` does not trigger cleanup from `wss.client` list.

#### Reproducible in:

- version: 7.3.1
- Node.js version(s):v12.18.2
- OS version(s): Linux (Ubuntu) VERSION="16.04.1 LTS (Xenial Xerus)"  "Ubuntu 16.04.1 LTS

#### Steps to reproduce:

1.  create ws server connect to it and let it send you data,

2.

3.

#### Expected result:

-  the websocket NOT  to be in the `wss.clients`  (we loop over this set to send data to clients)
- the websocket `readyState` should not be `OPEN`

#### Actual result:

- the `readyState` was `OPEN`
- the ws object was in the `wss.clients` list

**Comment by lpinca** [comment] 2020-09-02 13:38
Are you sure you are using `ws@7.3.1`? This is not possible because `ECONNRESET` is emitted by the internal socket and socket errors are swallowed by `ws` as per https://github.com/websockets/ws/blob/7.3.1/lib/websocket.js#L895-L905. See also https://github.com/websockets/ws/commit/a4050db3ad981db1c49daf5ba756ec4f4f71bc44.

**Comment by jacobbogers** [comment] 2020-09-02 14:03
We dont get the error via an "error" event handler,  the error is emitted when we call `ws.send` (exception is thrown), 
```javascript
if (ws.readyState !== WebSocket.OPEN) {
   return Promise.reject(...);
}
try {
  ws.send( .. jsondata.. );
catch(err) {
   logger.warn(err); // <-- error is reported here
   ws.terminate(); // <-- does not client up ws from wss.clients
}
```
Above snippet is called via
```javascript
for (const ws of wss.clients){  //<-- ws comes from this list
    send(ws, data)
}
```

**Comment by jacobbogers** [comment] 2020-09-02 14:05
this is form the package-lock.json used
```json
 "ws": {
      "version": "7.3.1",
      "resolved": "https://ip-109-71-162-126.dditscdn.com/nexus/repository/npm-all/ws/-/ws-7.3.1.tgz",
      "integrity": "sha512-D3RuNkynyHmEJIpD2qrgVkc9DQ23OrN/moAwZX4L8DfvszsJxpjQuUq3LMx6HoYji9fbIOBY18XWBsAux1ZZUA==" 
    },
````

**Comment by jacobbogers** [comment] 2020-09-02 14:11
I think the underlying socket is "half closed", is there any way we can remove it from wss.clients forcably?, the weird thing is that we expected `ws.terminate()` to do this, but it doesnt.

**Comment by lpinca** [comment] 2020-09-02 14:28
You can reproduce the `ECONNRESET` error like this:

```js
const EventEmitter = require('events');
const WebSocket = require('ws');

const ee = new EventEmitter();

const server = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${server.address().port}`);

  ws.on('open', function() {
    ws._socket.destroy();
    ee.emit('send');
  });
});

server.on('connection', function (ws) {
  // ws._socket.on('error', console.error);

  ee.on('send', function() {
    ws.send('Hello');
  });
});
```

but as written above the error is swallowed. Uncomment the line `ws._socket.on('error', console.error);` to see that the error is emitted.

Wrapping `ws.send()` in a `try...catch` is useless because `ws.send()` throws an error only if the ready state is `0`.

**Comment by lpinca** [comment] 2020-09-02 14:36
> I think the underlying socket is "half closed", is there any way we can remove it from wss.clients forcably?

Every `WebSocket` object is removed from the `wss.clients` set when the `'close'` event is emitted. Using `ws.terminate()` is the correct way to make a `WebSocket` object emit the `'close'` event as soon as possible.

**Comment by jacobbogers** [comment] 2020-09-02 14:46
"Half open", thats only a suspecion https://en.wikipedia.org/wiki/TCP_half-open  , because thats the only thing i can think of that  fits the facts,  half open also means a "close" event is never emitted.

Wich makes sense because `ws.readyState` was still "1" (OPEN) and the ws object still existed in `wss.clients`

**Comment by jacobbogers** [comment] 2020-09-02 14:52
https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L326
ok so the `ws.termnate()` calls `this._socket.destroy()` wich causes the "close" event to be fired that removes it from the `wss.clients` Set. The `this._socket.destroy()` is not causing an `close` to  be emitted. This looks like a `net.Socket` issue.

**Comment by lpinca** [comment] 2020-09-02 14:54
It's totally possible that you will find a `WebSocket` in an `OPEN` ready state even if the other peer closed the connection when looping the `wss.clients` set, but again without a test case that reproduces the issue I don't believe the `ECONNRESET` error will surface (see https://github.com/websockets/ws/issues/1794#issuecomment-685773856).

**Comment by jacobbogers** [comment] 2020-09-02 14:56
Could we code terminate()  to forcible remove it from `wss.clients` in all instances and not let it depend on `close`?

**Comment by jacobbogers** [comment] 2020-09-02 14:58
the ECONNRESET  is NOT emitted via `error` it is thrown (when the underlying socket.write is called?)

**Comment by jacobbogers** [comment] 2020-09-02 15:08
> It is necessary to wait for the 'close' event to make sure no data is lost.
Looking at your code, it is immaterial because I didnt say remove the "close" (or any other event handler) handler from the `ws` , just remove it from the `wss.clients` Set, if there is pending data, it would be handled, 

> Prove it.
Would like too, not sure if this is easily reproducable. See what i can do.

Will removing it from the `wss.clients` list work?. That will in any case guarantee that it is not a candidate for futher, receiving messages

**Comment by lpinca** [comment] 2020-09-02 15:16
> Looking at your code, it is immaterial because I didnt say  "remove the "close" (or any other event handler) handler" from the `ws` , just remove `ws` itself it from the `wss.clients` Set, if there is pending data, it would be handled, 

I don't follow, in my example the `ws` object will be removed from the `wss.clients` object.

> Would like too, not sure if this is easily reproducable. See what i can do.

Look at https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js. When an error occurs `socket.destroy(error)` is called. See https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L205 for example. That emits an `'error'` event on the `socket`. No error `Error` is thrown.

> Will removing it from the `wss.clients` list work?. That will in any case guarantee that it is not a candidate for futher, message transport if i loop over the clients list.

It doesn't make sense much sense as `ws.send()` checks the ready state and when an error occurs the ready state is changed to `2`. You can opt out of automatic client tracking by using the `clientTracking` option if you want and roll your own.

**Comment by lpinca** [comment] 2020-09-02 15:18
Can you please run `npm ls ws` from the root of your app and show the result?

**Comment by jacobbogers** [comment] 2020-09-02 15:46
> I don't follow, in my example the ws object will be removed from the wss.clients object.
yes, i mentioned that your code will do this https://github.com/websockets/ws/issues/1794#issuecomment-685788976

> No error Error is thrown.

We really got an error in the `try catch`..... and the error was `Error: write ECONNRESET` (literal quote), it wasnt emitted by any error event handler (our `logger` list the linenumber of the source file)

I dont see an explicit `throw` either this means the `handle.writev` (very likely) throws it.

> npm ls ws

One moment,

**Comment by jacobbogers** [comment] 2020-09-02 16:14
> npm ls ws

```bash
`-- xxxxxx (sorry this is info i cannot post here)
  `-- ws@7.3.1
```

**Comment by lpinca** [comment] 2020-09-02 17:13
> We really got an error in the `try catch`..... and the error was `Error: write ECONNRESET` (literal quote), it wasnt emitted by any error event handler (our `logger` list the linenumber of the source file)

Then it's either https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L154 or https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L92 and it both cases the error is emitted not thrown.

I'm very skeptical about this because if the error was thrown both `ws` and Node.js core issue trackers would have been flooded with reports.

Without a reproducible test case this is not actionable.

**Comment by jacobbogers** [comment] 2020-09-02 17:46
> Then it's either [referring to triggering try catch] ... and in both cases the error is emitted not thrown."

internally inconsistent statement, if it is not thrown then it cannot be  _"then it's either"_

I am talking about this -> https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L132

> would have been flooded with reports.

We have your library running 24/7 on 12 machines, transmitting 6G-8G per hour (cummulative)  this happens only 1x every 8 month. I have seen this issue 3x up till now.

> Without a reproducible test case this is not actionable.

I understand,  for me to recreate this error I would in any case need to reproduce it on a test environment.

**Comment by lpinca** [comment] 2020-09-02 17:55
> internally inconsistent statement, if it is not thrown then it cannot be "then it's either"

I was referring to

> Error: write ECONNRESET (literal quote)

It's either https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L154 or https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L92 and in both cases the error is emitted not thrown.

> BTW: I am talking about this -> https://github.com/nodejs/node/blob/v12.18.2/lib/internal/stream_base_commons.js#L132

That eventually returns an error which is handled by `afterWriteDispatched()` or `onWriteComplete()`. It certainly does not write `write ECONNRESET` in the error message. That is done by `errnoException()`.

**Comment by jacobbogers** [comment] 2020-09-02 18:00
> nd in both cases the error is emitted not thrown.

The code in the `try catch` did actually run

````javascript
try {
  ws.send( .. jsondata.. ); 
} catch(err) {
   logger.warn(err); // <-- this really happened, 
}
```

**Comment by jacobbogers** [comment] 2020-09-02 18:23
I wanted to add if above `logger.warn` is executed .. then on all subsequent `send` on the socket it will throw , and considering the amount of data we send, thats a lot of logs,  in such case we restart the process, since we see that the 'close' events is not fired, (the `ws` (or underlying `net.Socket` thinks its doing ok)

**Comment by lpinca** [comment] 2020-09-02 18:38
> then on all subsequent send on the socket it will throw

Do they? If so, why? You call `ws.terminate()` and that changes the ready state.

> since we see that the 'close' events is not fired

This also doesn't make sense ¯\_(ツ)_/¯. I have never seen a socket not emitting `'close'` after calling `socket.destroy()`.

**Comment by lpinca** [comment] 2020-09-02 18:44
I'll keep this open for a while, but with current informations there is not much we can do.

**Comment by jacobbogers** [comment] 2020-09-02 21:53
> Do they? 

Yes,

> `ws.terminate()` and that changes the ready state.

Not according to your code, there is a check if 'this._socket' exist


>This also doesn't make sense ¯_(ツ)_/¯. I have never seen a socket not emitting `'close'` after calling `socket.destroy()`.

This is also conditional if this._socket exist

**Comment by lpinca** [comment] 2020-09-03 05:09
On the server a `WebSocket` object **always** have a socket set. The check is for the client. On the client the socket is set after the handshake completes.

**Comment by lpinca** [comment] 2020-09-08 05:07
This is the gist of the discussion so far:

1. `{net,tls}.Socket` randomly throw errors when calling `{net,tls}.Socket.prototype.write()` instead of emitting them.
1. `WebSocket.prototype.terminate()` does not change the ready state of the `WebSocket` object.
1. The `WebSocket` object does not emit the `'close'` event, even if `websocket.terminate()` is called.

Every point in the above list is very strange and unproven:

1. There is no evidence in the Node.js core code that errors are thrown.
1. On the server a `WebSocket` object always has a socket set so the ready state is [changed unconditionally](https://github.com/websockets/ws/blob/7.3.1/lib/websocket.js#L368) to `WebSocket.CLOSING` when calling `websocket.terminate()`.
1. The `WebSocket` `'close'` depends on the internal socket `'close'` event. `websocket.terminate()` calls `websocket._socket.destroy();` and I have never seen a socket not emitting `'close'` after calling `socket.destroy()` as per https://github.com/websockets/ws/issues/1794#issuecomment-685924338.

I'm closing this as per https://github.com/websockets/ws/issues/1794#issuecomment-685927311.

**Closed by lpinca** 2020-09-08 05:07 UTC
