### ISSUE TITLE
createWebSocketStream supports either text or binary messages (but not mixed)

### ISSUE THREAD

**Issue by viyaha** [websockets/ws#1804] opened 2020-10-09 13:09 UTC
#### Description

Websockets can receive binary or text messages. Using createWebSocketStream forces the decision to receive either string or buffer results.

#### Expected result:

Text messages are received as string, binary messages are received as buffer.

#### Actual result:

Without specified encoding: All text messages are converted to buffers.
With specified encoding: All binary messages are converted to string.

**Comment by lpinca** [comment] 2020-10-09 14:51
There is not much to do about this. That's how Node.js streams work.

**Comment by mika-fischer** [comment] 2020-10-09 15:00
Fair enough. Our use case is actually to properly handle backpressure with websockets. createWebSocketStream seems to be the only supported way to do that currently, right? Unfortunately, that way we lose important information (the type of the WebSocket message)...

We also don't really need a nodejs stream. We're using async iterators and use those to iterate over the stream.

We could write an async iterator ourselves, but only by accessing internals of the WebSocket class, which is why I would prefer if this project would support this functionality out-of-the-box.

**Comment by lpinca** [comment] 2020-10-09 15:06
It's not the only way but it's the easiest to use. A possible workaround it something like this:

```js
const duplex = WebSocket.createWebSocketStream(ws);
duplex.resume(); // or `duplex.pipe(writable)`

ws.on('message', function(msg) {
  // `msg` can be a `Buffer` or a `string`.
});
```

**Comment by lpinca** [comment] 2020-10-09 15:07
That way backpressure is still correctly handled.

**Comment by lpinca** [comment] 2020-10-09 15:26
For the writable side of the `Duplex` stream returned by `WebSocket.createWebSocketStream()`, you can use the `decodeStrings` option to retain the original type of the written chunk.

**Comment by lpinca** [comment] 2020-10-10 11:46
@mika-fischer I'm not inclined to make the `WebSocket` object async iterable because:

1. The stream returned by `WebSocket.createWebSocketStream()` can already be consumed as an async iterator, but of course, chunks are all strings or all buffers so the issue still applies. I think that when streaming, having the ability to know the original type of the WebSocket message is not a common requirement, especially if you control the source. Using an efficient binary serialization/deserialization format and no compression for all message is best option in my opinion.
1. It is not trivial to to make the `WebSocket` object async iterable and correctly handle backpressure without a backing `Readable` stream.

Besides https://github.com/websockets/ws/issues/1804#issuecomment-706236008, it is possible to use the `readableObjectMode` option and set it to `true` to retain the original type of the `WebSocket` message. However this can mess up backpressure handling as discussed in https://github.com/websockets/ws/issues/1640.

**Comment by mika-fischer** [comment] 2020-10-12 08:43
I think the only thing we really need in order to do this ourselves is a properly supported way of stopping and restarting the reception of websocket mesages from the underlying socket. What do you think about providing that? Then we can go from there without worrying about things breaking with new releases. And you could use that same interface in `createWebSocketStream()`.

**Comment by lpinca** [comment] 2020-10-12 10:10
That is already possible by pausing and resuming the underlying socket (`ws._socket.pause()` and `ws._socket.resume()`) but the problem is that an unspecified number of `'message'` events can be emitted. A chunk of data read from the underlying socket can contain many frames and the parser cannot be paused. It's a `Writable` stream that will continue processing until there is available data (until all data read from the socket is consumed).

I think it's hard to build an async iterator upon that without changing `ws` internals.

**Comment by viyaha** [comment] 2020-10-12 12:02
@lpinca thanks for your help :) 

For us it's no issue, that an unspecified number of "message" events can be emitted (the queue will nearly always "overshoot", but we can handle that). 
Implementing a simple Queue with a capacity and handling the resume/pause-logic ourselves instead of using createWebSocketStream (==> the underlying NodeJS-Stream) gave us even a performance boost (~10%).

But it's still not as simple as using pause and resume, ws._receiver also handles pause and resume calls, that means (as in createWebSocketStream) you need to do something like:

`

    private init(): void {
        this.ws.once('open', () => {
            (this.ws as any)._receiver.removeAllListeners('drain');
            (this.ws as any)._receiver.on('drain', () => {
                if (!this.paused) {
                    (this.ws as any)._socket.resume();
                }
            });
        });
    }

    private onFull(): void {
        this.paused = true;
        (this.ws as any)._socket.pause();
    }

    private onNotFull(): void {
        this.paused = false;
        (this.ws as any)._socket.resume();
    }
`

**Comment by lpinca** [comment] 2020-10-12 14:29
True, that is to make sure that the socket stays paused. Otherwise something like might happen:

1. Receiver needs drain.
1. Messages are added to the queue and the queue is full.
1. The socket is paused.
1. `'drain'` is emitted and the socket is resumed.
1. go to 1.

but I'm not sure how likely it is to happen.

We could add `WebSocket.prototype.pause()` and `WebSocket.prototype.resume()` but I don't want to deviate from the HTML interface which is the reason why the `'drain'` hack was used in `WebSocket.createWebSocketStream()`.

I think the original issue is an edge case, so my question is.

Apart from the performance would something like https://github.com/websockets/ws/issues/1804#issuecomment-706236008 work for you? That is, using `duplex.pause()`, `duplex.resume()`, and listening directly to the `'message'` events of the `WebSocket` object.

**Comment by viyaha** [comment] 2020-10-12 15:21
We have some high performance requirements and a 10% performance boost is game changing ;)

But at the moment we use something like that, we're using the same 'drain' hack, the same 'pause' and 'resume' logic, we only skipped using a NodeJS-Stream for calculating the Message-Buffer-Size. 

``` ts
import WebSocket = require('ws');

export class BackpressureHandler {
    private cache: any[] = [];
    private closed: boolean = false;
    private paused: boolean = false;

    private waitingForNextPush: Array<(chunk: any) => void> = [];

    constructor(private ws: WebSocket, private capacity: number) {
        this.ws.on('message', (msg) => this.push(msg));
        this.ws.once('close', () => this.close());
        this.ws.once('open', () => {
            (this.ws as any)._receiver.removeAllListeners('drain');
            (this.ws as any)._receiver.on('drain', () => {
                if (!this.paused) {
                    (this.ws as any)._socket.resume();
                }
            });
        });
    }

    public async next(): Promise<any | undefined> {
        if (this.cache.length === 0) {
            if (this.closed) {
                return undefined;
            }
            return new Promise((resolve) => this.waitingForNextPush.push(resolve));
        }
        const chunk = this.cache.shift();

        if (this.cache.length < this.capacity) {
            this.onNotFull();
        }

        return chunk;
    }

    private push(chunk: any) {
        if (this.waitingForNextPush.length > 0) {
            this.waitingForNextPush.shift()!(chunk);
        } else {
            this.cache.push(chunk);
            if (this.cache.length >= this.capacity) {
                this.onFull();
            }
        }
    }

    private close(): void {
        this.closed = true;
        if (this.cache.length === 0) {
            while (this.waitingForNextPush.length > 0) {
                this.waitingForNextPush.shift()!(undefined);
            }
        }
    }

    private onFull(): void {
        this.paused = true;
        (this.ws as any)._socket.pause();
    }

    private onNotFull(): void {
        this.paused = false;
        (this.ws as any)._socket.resume();
    }
}
```

**Comment by lpinca** [comment] 2020-10-12 16:43
It seems your solution is based on counting the number of chunks, like a stream in object mode so if my understanding is correct it suffers from the same issues discussed here https://github.com/websockets/ws/issues/1640#issuecomment-540660954.

Did you benchmarked it against `WebSocket.createWebSocketStream()` in object mode (`WebSocket.createWebSocketStream(ws, { readableObjectMode: true })`)? In object mode the stream is faster as there is no conversion from string to buffer.

**Comment by viyaha** [comment] 2020-10-13 09:52
yeah, you're right, i completely missed the possibility to set it to object-mode (i thought it was disabled).
The performance difference afterwards is only marginal. So we'll use it in object-mode. As for the issue with the size: That's no issue for us, we have direct control over the size of the messages ==> so it's more and less the same ;)

But I just noticed using the (not object-mode) stream as AsyncIterator (as defined in Nodejs) completly breaks it... it takes longer and it misses ~50% of the messages afterwards...
==> as I have read in the other ticket the async iterator breaks something and should not be used ==> shouldn't it be fixed or removed from the interface then? That's an easy missable trap...

But for us: as far as my tests go and I understood your comments we're good to go with activated object-mode?

**Comment by lpinca** [comment] 2020-10-13 11:24
> as I have read in the other ticket the async iterator breaks something and should not be used ==> shouldn't it be fixed or removed from the interface then? That's an easy missable trap...

It works fine but you can't expect each chunk to be exactly equal to one `WebSocket` message. Nothing is lost. That is ok as it works like `net.Socket` or another binary stream. You can't expect every chunk read from a `net.Socket` to be exactly equal to the chunk that was written to the other end. What matters is that the final data read from one end is exactly equal to the data that is written to the other end.

> But for us: as far as my tests go and I understood your comments we're good to go with activated object-mode?

Yes.

**Comment by lpinca** [comment] 2020-10-14 12:50
I'm going to close this, please let me know if this should stay open.

**Closed by lpinca** 2020-10-14 12:51 UTC
