### ISSUE TITLE
One WebSocketServer test fails if we are using root account 

### ISSUE THREAD

**Issue by smartmouse** [websockets/ws#314] opened 2014-05-08 15:19 UTC
Hi, I was trying the packaged tests that comes with ws.
If I am using a normal user account, all tests pass.
If I am using a root account , one of the tests fail.

 184 passing (9 seconds)
  1 failing

  1) WebSocketServer #ctor emits an error if http server bind fails:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/root/testWS/node_modules/ws/node_modules/mocha/lib/run                  nable.js:165:14)
      at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

I am using 10.28 nodejs  and npm version 1.4.3

Do the tests designed to be run with normal user account only?
Thanks for your help in advance.

**Comment by lpinca** [comment] 2016-11-14 14:31
I can't reproduce the issue, tests pass also when run with the root user on my machine.
Closing this, please comment or reopen if needed.

**Closed by lpinca** 2016-11-14 14:31 UTC
