### ISSUE TITLE
what to do when WS is not a constructor?

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#1060] opened 2017-04-03 08:29 UTC
for some exotic browsers i want to support, like opera, i see the `WS is not a constructor error`.

do you think you could add a workaround for that? if not, what else would you suggest in my place?

**Comment by binarykitchen** [comment] 2017-04-03 09:03
there is also the `object argument expected` error sometimes when trying to create it

**Comment by lpinca** [comment] 2017-04-03 10:12
Care to elaborate? ws is only for Node.js in the browser you have to use the native `WebSocket` object.

**Comment by binarykitchen** [comment] 2017-04-03 21:55
sorry, i wasn't clear. initially we are using the websocket-stream package which uses yours. and it encapsulates everything into a `WS` class, see https://github.com/maxogden/websocket-stream/blob/master/stream.js#L5 which is then instantiated further down at https://github.com/maxogden/websocket-stream/blob/master/stream.js#L43

hence addressing this here, since that class is coming from websockets/ws ...

**Comment by lpinca** [comment] 2017-04-04 06:13
@binarykitchen this is what `websocket-stream` uses for the browser: https://github.com/maxogden/websocket-stream/blob/master/ws-fallback.js. It's not `ws` :)

**Comment by lpinca** [comment] 2017-04-04 06:24
What is the Opera version where this happens?

**Comment by binarykitchen** [comment] 2017-04-04 07:43
ah, it is the `ws-fallback.js` file, thanks for correcting.

i think this error happened on old opera v12 something

**Comment by lpinca** [comment] 2017-04-04 07:49
In 11.50 WebSocket had to be manually enabled, not sure about 12. Anyway I think that the issue happens because there isn't a global `WebSocket` object.

I would download those very old versions of Opera and try to run the `ws-fallback.js` script in the console to reproduce the issue.

Closing as this is not a `ws` issue.

**Closed by lpinca** 2017-04-04 07:49 UTC

**Comment by binarykitchen** [comment] 2017-04-04 07:51
i see, thanks @lpinca
