### ISSUE TITLE
What do we need in the next major version release?

### ISSUE THREAD

**Issue by JoshuaWise** [websockets/ws#835] opened 2016-09-21 20:18 UTC
It's been a while since we've published a `ws` release, but I know we've made a lot of breaking changes in `master`, so our next release will have to be a major version.  To get the ball rolling, I'm creating a list of everything that should be included in the next major version release.

Here's what I'm currently aware of:
- `Set` instead of `Array` for client tracking
- Rewrite everything as ES6

What else?

@3rd-Eden 
@JacksonTian 
@einaros

**Comment by lpinca** [comment] 2016-09-22 06:08
Few ideas:

- Remove support for older versions of the protocol (Hixie and HyBi drafts 07-12)
- Ignore data that is sent along with the upgrade request. If I'm reading https://tools.ietf.org/html/rfc6455#section-1.2 correctly, data transfer should start only when the handshake is completed.
- Check if the closing handshake https://tools.ietf.org/html/rfc6455#section-7.1.1) is working as intended (#784).
- Fix permessage deflate issues (#799).
- Add proper stream support.

**Comment by JoshuaWise** [comment] 2016-09-26 01:24
Those are all good. I'm especially interested in removing support for old protocols (due to security and many other issues). Hopefully the other maintainers agree with me on that.

**Comment by JacksonTian** [comment] 2016-09-26 05:45
I am OK.

**Comment by Aleksey-Danchin** [comment] 2016-09-28 08:23
Add reconnection event for sockets.

**Comment by aryeharmon** [comment] 2016-09-29 11:44
proxy support

**Comment by LightningShock** [comment] 2016-12-16 06:53
i second proxy support

**Comment by lpinca** [comment] 2016-12-16 06:58
I don't think we add proxy support in next release unless someone from the community steps up and makes an awesome PR.

For the moment proxy support can be added with a custom agent.
Take a look a these modules:

- https://github.com/TooTallNate/node-socks-proxy-agent
- https://github.com/TooTallNate/node-https-proxy-agent

**Comment by lpinca** [comment] 2017-01-02 16:55
`ws` is quite popular and I wonder if we should we go through a beta phase before cutting version 2.0.0. If so I would do it soon so people can start using it and report issues, if any.

Thoughts?

**Comment by kmansoor** [comment] 2017-01-03 17:34
Support for node cluster?

**Comment by lpinca** [comment] 2017-01-03 17:40
@kmansoor cluster already works out of the box.

**Comment by kmansoor** [comment] 2017-01-03 17:54
Fully aware that this is not the right place to ask this, but I'm in the middle of rewriting a production app to use Ajax instead of 'ws' because it started to fail in a node cluster'ed env. Is it possible for you to point me to any docs or example?

**Comment by lpinca** [comment] 2017-01-03 17:59
This is a very simple implementation, but that a look at this example: https://github.com/hashrocket/websocket-shootout/blob/master/js/run-cluster.js

**Comment by kmansoor** [comment] 2017-01-03 18:29
Great, thank you so much.

**Closed** 2017-01-10 15:02 UTC
