### ISSUE TITLE
Unexpected token: name (PerMessageDeflate)

### ISSUE THREAD

**Issue by megamindbrian** [websockets/ws#1181] opened 2017-08-05 02:04 UTC
- [ x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I am trying to use socket.io (server) with https://github.com/ng-seed/universal.
I have installed babel-preset-es2015.  I have set my babelrc file.
I have not tried modifying https://github.com/fulls1z3/angular-webpack-config in order to add es2016.
This post does not specify the context of webpack config to modify (really lame @pmirnd):
https://stackoverflow.com/questions/42071529/error-in-bundle-js-from-uglifyjs-syntaxerror-unexpected-token-name-x

#### Reproducible in:
The project described above.

#### Steps to reproduce:

1.  Checkout ng-seed/universal
2.  ```npm install babel-preset-es2015 socket.io @types/socket.io```
3.  ```npm run build:universal-prod```

### Expected result:

ws module to provide properly packed versions of js.

### Actual result:

Impossible to use with webpack?  Works fine in dev mode (- uglify and aot).

**Comment by lpinca** [comment] 2017-08-05 05:33
I honestly don't know what ng-seed/universal does and how to use it.
Also the description on how to reproduce the issue seems to be partial

> 3. See webpack fails to build with the error above

How? The first two steps only tell to clone a repository and install a couple of dependencies.

Are you bundling for the browser or Node.js? In the former case you need to shim `ws` and use the native `WebSocket` object but `socket.io` should already do this for you.

Lastly this seems to be an issue with `socket.io` not `ws` as you are not using `ws` directly?

**Comment by megamindbrian** [comment] 2017-08-05 06:52
Angular universal uses webpack but runs an Express server so it is running on node. When I compile in Dev mode without uglify everything works great. When compiling for production the client side using socket.io-client works, but the server side (running along side express) fails to pack with the error message in the title of this issue. It would seem that was does not come with a pre-transpiled es5 module for webpack to load. I am not sure how this works but with a lot of libraries I see a lib.js, lib.es5.js, lib.slim.js along side each other. Is there a way to build ws to transpile and include those in the package?

**Comment by lpinca** [comment] 2017-08-05 08:19
> It would seem that `ws` does not come with a pre-transpiled es5 module

This is correct as `ws@^2` only runs on Node.js >= 4 so there is no reason to transpile.

You can try to use `socket.io@^1` and `socket.io-client@^1` which use an older version of `ws` written in ES5 and see if this changes something.

> Is ws meant to work with uglify?

The `uglify-js` version used in the package does not support ES6 features but if `ws` is transpiled to ES5 I see no reason why it should not work.

**Comment by megamindbrian** [comment] 2017-08-05 14:02
So I should transpile it to ES5 myself and try to include it?

**Comment by lpinca** [comment] 2017-08-05 15:38
I would try to use `socket.io@1` first.

**Comment by lpinca** [comment] 2017-08-09 15:48
Closing as I think there is not actionable for us to do here.

**Closed by lpinca** 2017-08-09 15:48 UTC

**Comment by windsome** [comment] 2017-08-11 14:57
I also encounter this issue.

**Comment by megamindbrian** [comment] 2017-08-11 15:08
I haven't worked on it. But I was going to use babel on ws 2.* And see if I
got anywhere with uglify.
