### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by lawlmart** [websockets/ws#869] opened 2016-10-20 20:59 UTC
I've trying to track down a memory leak that seems to be related to ws. My socket server has ~ 300 connections per second and peaks out at around 15000 concurrents before running out of memory (8 gb).  Memory usage seems to rise linearly (proportional to new connections, not concurrent connections). Here's what I believe to be the relevant part of the heap dump:

![image](https://cloud.githubusercontent.com/assets/10986838/19577753/64468768-96cd-11e6-94ba-c8cf433b6ff5.png)

Thanks in advance for your assistance.

**Comment by lpinca** [comment] 2016-10-21 05:45
Can you try to disable the permessage-deflate extension?

**Comment by lawlmart** [comment] 2016-10-21 14:50
Yes, same result just without the deflate calls in the stack.

**Comment by lpinca** [comment] 2016-10-21 15:43
I'm kinda new to ws codebase so I'm not sure where to look.
Did you also try to disable client tracking?
Is it possible to reproduce the issue somehow?
Thanks.

**Comment by schwiet** [comment] 2017-01-12 23:07
I too wonder if it has to do with client tracking, which does not seem to work for me, at least when a client has disconnected. If I print `wss.clients.length` each `'connection'` event and then again each time a client hits `onclose`, I see something like:
```

client connected:  1 clients
client disconnected. 1 clients

client connected:  2 clients
client disconnected. 2 clients

client connected:  3 clients
client disconnected. 3 clients

client connected:  4 clients
client disconnected. 4 clients

client connected:  5 clients
client disconnected. 5 clients

client connected:  6 clients
client disconnected. 6 clients

```

Looks like clients are not removed upon disconnection, which seems like it would be the expected behavior, right?

**Comment by schwiet** [comment] 2017-01-12 23:44
#967 possibly related.

**Comment by lpinca** [comment] 2017-01-27 09:07
@lawlmart were you using `ws.onclose = function () {};` on the server?

**Comment by lawlmart** [comment] 2017-01-27 15:17
No, I'm not.

**Comment by lpinca** [comment] 2017-01-27 15:21
Can you try with `ws@beta` and see if the issue persists? Also disable permessage-deflate if you can.

Thanks.

**Comment by lpinca** [comment] 2017-04-28 06:01
Closing as I can reproduce the issue. Please post back if you have more info.
Thanks.

**Closed by lpinca** 2017-04-28 06:01 UTC
