### ISSUE TITLE
After handshake, no data messagem is received

### ISSUE THREAD

**Issue by rafasimionato** [websockets/ws#1516] opened 2019-02-26 03:19 UTC
[X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Dear maintainers,

despite I am very new on websocket Javascript and websockets, I am trying to establish communication between 3 clients and a webserver built with Node JS and WS module.

So the problem is I don't have access to the clients code as it is embeeded into 3 different equipment I have. The 3 of them works perfectly transmitting and receiveing websocket messages To and From a server built in C# (which I also don't have access to the DLL code that instantiates the sockets).

Using WireShark I could check that when succeeding the handshake upgrading from HTTP to WebSocket, we can see following sequence of messages:

86  24.796580   192.168.1.127   192.168.1.110   HTTP    237 GET /pub/chat HTTP/1.1 
87  24.831739   192.168.1.110   192.168.1.127   HTTP    183 HTTP/1.1 101 Switching Protocols 
88  24.835353   192.168.1.127   192.168.1.110   TCP 60  1101 → 7788 [ACK] Seq=184 Ack=130 Win=1671 Len=0
96  26.858092   192.168.1.127   192.168.1.110   WebSocket   352 WebSocket Text [FIN] 
97  26.956991   192.168.1.110   192.168.1.127   WebSocket   117 WebSocket Text [FIN]

I have tried different Javascript libraries but ony got success (same sequence of messages as above) using WS library (https://www.npmjs.com/package/ws) just for one of the 3 equipment I have. For the other two equipment, the TCP ACK seems to never reach destination. See below WireShark logs for these other two equipment:

1351    433.758538  192.168.1.127   192.168.1.110   HTTP    237 GET /pub/chat HTTP/1.1 
1352    433.760198  192.168.1.110   192.168.1.127   HTTP    183 HTTP/1.1 101 Switching Protocols 
1353    433.764133  192.168.1.127   192.168.1.110   TCP 60  1320 → 7788 [ACK] Seq=184 Ack=130 Win=1671 Len=0
1361    435.824357  192.168.1.127   192.168.1.110   TCP 60  [TCP Dup ACK 1353#1] 1320 → 7788 [ACK] Seq=184 Ack=130 Win=1671 Len=0
1371    439.818889  192.168.1.127   192.168.1.110   TCP 60  [TCP Dup ACK 1353#2] 1320 → 7788 [ACK] Seq=184 Ack=130 Win=1671 Len=0
1400    447.824172  192.168.1.127   192.168.1.110   TCP 60  [TCP Dup ACK 1353#3] 1320 → 7788 [ACK] Seq=184 Ack=130 Win=1671 Len=0
1408    451.759634  192.168.1.127   192.168.1.110   TCP 60  1320 → 7788 [FIN, ACK] Seq=184 Ack=130 Win=1671 Len=0
1409    451.762178  192.168.1.110   192.168.1.127   TCP 54  7788 → 1320 [ACK] Seq=130 Ack=185 Win=64240 Len=0
1410    451.762408  192.168.1.110   192.168.1.127   TCP 54  7788 → 1320 [FIN, ACK] Seq=130 Ack=185 Win=64240 Len=0
1411    451.765244  192.168.1.127   192.168.1.110   TCP 60  1320 → 7788 [RST, ACK] Seq=185 Ack=130 Win=0 Len=0
1412    451.766881  192.168.1.127   192.168.1.110   TCP 60  1320 → 7788 [RST, ACK] Seq=185 Ack=131 Win=0 Len=0

As you can see, after 3 DUP ACK, client send a FIN/ACK to finish connection.

I am using the Simple Server described on WS landing web page just to receive messages from the clients and print it in the console. See my code below:

```javascript
const WebSocket = require('ws');
const wss = new WebSocket.Server({ port: 7788 });

wss.on('connection', function connection(ws) {

  console.log('connection...');

  ws.on('message', function incoming(message) {

    var client_message = JSON.parse(message);
    console.log('message received: %s', JSON.stringify(client_message));

    var server_timestamp = currentFormattedDate();  

    var response = {
      "ret": client_message.cmd,
      "result": true,
      "cloudtime": server_timestamp
    };

    console.log('responseeeee message: %s', JSON.stringify(response));
    ws.send(JSON.stringify(response));

  });

});

function currentFormattedDate() {
  var current_date = new Date();
  return (current_date.getFullYear() + "-" +
         ("0" + (current_date.getMonth() + 1)).substr(-2) + "-" +
         ("0" + current_date.getDate()).substr(-2) + " " +
         ("0" + current_date.getHours()).substr(-2) + ":" +
         ("0" + current_date.getMinutes()).substr(-2) + ":" +
         ("0" + current_date.getSeconds()).substr(-2));
}
```
I really do not know if I am doing something wrong or if I am missing something. Or even I found a bug.

However, if it is not a bug in the library, I would really appreaciate any help to debug this situation as the 3 equipment works perfectly transmitting to the server written in C# I told before.

Thanks in advance.

#### Reproducible in:

- version: 6.1.4
- Node.js version(s): v10.15.1
- OS version(s): Win 7 Home

#### Steps to reproduce:

1. Just try to establish websocket connection with embbeed equipment I have. 

#### Expected result:

Handshake succeed.

#### Actual result:

Handshake TCP AKC message seems to never reach destination.

#### Attachments:

If you need any futher information to help on this debug, please give directions and I can get is promptly.

**Comment by lpinca** [comment] 2019-02-26 07:06
I see nothing wrong in your example but I have no idea why the client sends 3 `TCP Dup ACK`. I think that it is sent when the client detects that some packet has been lost?

**Comment by rafasimionato** [comment] 2019-02-26 14:38
Would you suggest any where I could put some logs to check input and
output, if values are as  expected.

Em ter, 26 de fev de 2019 04:06, Luigi Pinca <notifications@github.com>
escreveu:

**Comment by lpinca** [comment] 2019-02-26 14:51
Try this:

```js
const http = require('http');

const GUID = '258EAFA5-E914-47DA-95CA-C5AB0DC85B11';

const server = http.createServer();

server.on('upgrade', (req, socket) => {
  const key = crypto.createHash('sha1')
    .update(req.headers['sec-websocket-key'] + GUID)
    .digest('base64');

  socket.on('error', console.error);
  socket.on('data', console.log);

  socket.write([
    'HTTP/1.1 101 Switching Protocols',
    'Upgrade: websocket',
    'Connection: Upgrade',
    `Sec-WebSocket-Accept: ${key}`,
    '\r\n'
  ].join('\r\n'));
});

server.listen(7788, () => {
  console.log('Listening on *:7788');
});
```

It doesn't use ws and should give you more freedom. The example should be sufficient to pass the opening handshake. `socket` is a raw socket, so data framing is up to you but at least you can see if data comes through.

**Comment by rafasimionato** [comment] 2019-02-27 03:10
dear @lpinca, unfortunately I got same error using code above.
I am attaching wireshark logs for debug if you or someone else have any clue.

[ack-error.txt](https://github.com/websockets/ws/files/2908410/ack-error.txt)
[ack-error.zip](https://github.com/websockets/ws/files/2908413/ack-error.zip)

**Comment by lpinca** [comment] 2019-02-27 06:38
@rafasimionato I don't know.
Can you try with something like `nc` and see if the issue persists?

```
nc -l 7788
```

Then connect your device and send the headers as show in the above example.

**Comment by lpinca** [comment] 2019-02-28 06:22
I'm closing this as it doesn't seem to be an issue in ws. Discussion can continue if needed.

**Closed by lpinca** 2019-02-28 06:22 UTC

**Comment by rafasimionato** [comment] 2019-03-07 02:33
Sorry for the delay on this. I just figured out what was happening.

Library ws replies to the upgarde request as following:

    'HTTP/1.1 101 Switching Protocols',
    'Upgrade: websocket',
    ...

And I realized that in the C# code which works (it is built using SuperWebSocket library) with my embeeded clients, it replies slightly different as following:

    'HTTP/1.1 101 Switching Protocols',
    'Upgrade: **W**eb**S**ocket',
    ...

Then I changed ws to reply as above and voilà, it start working.

Should clients handle it from there side? Is there a way to handle this situation from server side, I mean into the lib code?

**Comment by lpinca** [comment] 2019-03-07 06:16
The spec says that the header field value should be case-insensitive. Both `WebSocket` and `websocket ` must work.

Anyway the server emits a `'headers'` event, you can change the value there and it should work.

```js
const wss = new WebSocket.Server({ server });

wss.on('headers', function(headers) {
  headers[1] = 'Upgrade: WebSocket';
});

wss.on('connection', function(ws) {
  // ...
});
```

**Comment by iyjian** [comment] 2019-10-06 04:28
@rafasimionato I'm not sure am I experienced the same issue as yours. I build the ws client and ws server using this library.

I use wireshark to examine the transmission process and I found, after the client recieved "switching protocols", the client recieved two "out of order" packet, and then client send two ack to websocket server, finally, the server reset the connection. see below wireshark screenshot.

after I found this discussion, I use the [above ws server code](https://github.com/websockets/ws/issues/1516#issuecomment-467467840) written by @lpinca , and the issue persistant and can be reproduced, I suspect this is a network issue, because after I bind another public ip(139.198.191.55) on the server, everything goes perfect. 

But I still want to know the root cause of this problem, could anyone give me some directions?

## enviroment
nodejs 10.16.3 both on client and server
ws 6.1.4 (and I also tried 7.1.4) both on client and server
server os: ubuntu 18.04
client os:  win7 / win10 / ubuntu 18.04 (tried all of them)


## wireshark screenshot

![image](https://user-images.githubusercontent.com/466985/66264195-59dad300-e833-11e9-8b28-8789d78c5d29.png)

**Comment by iyjian** [comment] 2019-10-06 07:25
the payload of 304 and 305 are "302 Found", it is wired, I am using @lpinca  's code as ws server, seems that this 302 is send by nodejs http library.

```
HTTP/1.1 302 Found 
Connection: closed
Cache-Control: no-cache
Content-Length: 0
Location: http://localhost
Refresh: 1
```

0000   a0 a4 c5 5f 59 a6 c0 61 18 65 3b e8 08 00 45 00    ¤Å_Y¦Àa.e;è..E.
0010   00 a5 12 34 40 00 7a 06 e2 10 8b c6 bf 37 c0 a8   .¥.4@.z.â..Æ¿7À¨
0020   00 68 22 3d c8 c6 f0 92 f5 a3 05 05 f7 8f 50 18   .h"=ÈÆð.õ£..÷.P.
0030   01 04 ef dd 00 00 48 54 54 50 2f 31 2e 31 20 33   ..ïÝ..HTTP/1.1 3
0040   30 32 20 46 6f 75 6e 64 0d 0a 43 6f 6e 6e 65 63   02 Found..Connec
0050   74 69 6f 6e 3a 20 63 6c 6f 73 65 0d 0a 43 61 63   tion: close..Cac
0060   68 65 2d 43 6f 6e 74 72 6f 6c 3a 20 6e 6f 2d 63   he-Control: no-c
0070   61 63 68 65 0d 0a 43 6f 6e 74 65 6e 74 2d 6c 65   ache..Content-le
0080   6e 67 74 68 3a 20 30 0d 0a 4c 6f 63 61 74 69 6f   ngth: 0..Locatio
0090   6e 3a 20 68 74 74 70 3a 2f 2f 6c 6f 63 61 6c 68   n: http://localh
00a0   6f 73 74 0d 0a 52 65 66 72 65 73 68 3a 20 31 0d   ost..Refresh: 1.
00b0   0a 0d 0a                                          ...

**Comment by bigbizze** [comment] 2020-11-26 04:29
This is a really silly reason to be looking at this thread with concern in the way anyone else is, but in our case we just happened to be subscribing to the event "connect" instead of "connection".
