### ISSUE TITLE
Error: WebSocket is not open: readyState 0 (CONNECTING) at onopen event.

### ISSUE THREAD

**Issue by ductridev** [websockets/ws#2175] opened 2023-11-10 11:59 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

The `onopen` event should be emitted after connection is open. At current, I see this error happens very frequently.

### ws version

8.14.2

### Node.js Version

Node.js v18.18.0

### System

  System:
    OS: Linux 5.4 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (2) x64 QEMU Virtual CPU version 2.5+
    Memory: 2.90 GB / 3.84 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash

### Expected result

The `onopen` event should be emitted after `readyState` is `OPEN`.

### Actual result

The `onopen` event emitted while `readyState` is `CONNECTING`.

### Attachments

```
Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/root/node_modules/ws/lib/websocket.js:444:13)
    at client.onopen (/root/client.js:47:27)
    at callListener (/root/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onOpen (/root/node_modules/ws/lib/event-target.js:237:9)
    at WebSocket.emit (node:events:517:28)
    at WebSocket.setSocket (/root/node_modules/ws/lib/websocket.js:239:10)
    at ClientRequest.<anonymous> (/root/node_modules/ws/lib/websocket.js:993:15)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketOnData (node:_http_client:581:11)
    at TLSSocket.emit (node:events:517:28)
```

My simple code:
```
client.onopen = () => {
    console.log(`New client just connected`);

    client.send(JSON.stringify(
        {
            "method": "VERIFY"
        }
    ))
};
```

**Comment by lpinca** [comment] 2023-11-10 12:56
I cannot reproduce the issue.

```
$ cat index.js
const WebSocket = require('ws');

const ws = new WebSocket('wss://websocket-echo.com');

ws.onopen = () => {
  console.log('New client just connected');

  ws.send(
    JSON.stringify({
      method: 'VERIFY'
    })
  );
};
```

```
$ node index.js
New client just connected
```

**Comment by lpinca** [comment] 2023-11-10 13:02
I just did, it works and exits. No error is raised.

**Comment by ductridev** [comment] 2023-11-10 13:15
Weird. I just get it. and now still exist so I have to implement a logic to handle it.

**Comment by lpinca** [comment] 2023-11-10 14:13
Can you provide a reproducible test case?

**Comment by ductridev** [comment] 2023-11-10 14:17
I just test with stream from stream.binance.com. That's all. Maybe because internet problem. 

```
const binanceWS = new WebSocket(`wss://stream.binance.com:443/ws/ve_ware_${fromSymbol}${toSymbol}`);

binanceWS.onopen = async () => {
        // Handle problem.
        if (binanceWS._readyState == 0) {
            ready = false;
        } else if (binanceWS._readyState == 1) {
            ready = true;
        } else {
            return;
        }
        while (!ready) {
            if (binanceWS._readyState == 0) {
                ready = false;
            } else if (binanceWS._readyState == 1) {
                ready = true;
            } else {
                return;
            }
            await timer(100);
        }

        console.log(`[binanceWS_btcusdt] Connected`);

        binanceWS.send(JSON.stringify(
            {
                "method": "SUBSCRIBE",
                "params":
                    [
                        `btcusdt@kline_1m`,
                        `btcusdt@kline_1h`,
                        `btcusdt@kline_1d`,
                    ],
                "id": i
            }
        ))
    };
```

**Comment by lpinca** [comment] 2023-11-10 14:23
@ductridev it does not make sense. Please show a minimal example where the error is raised.

**Comment by lpinca** [comment] 2023-11-10 14:25
When the `'open'` event listener is called, the ready state cannot be 0, so there must be something wrong in your code.

**Comment by ductridev** [comment] 2023-11-10 14:27
> I just test with stream from stream.binance.com. That's all. Maybe because internet problem.
> 
> ```
> const binanceWS = new WebSocket(`wss://stream.binance.com:443/ws/ve_ware_${fromSymbol}${toSymbol}`);
> 
> binanceWS.onopen = async () => {
>         // Handle problem.
>         if (binanceWS._readyState == 0) {
>             ready = false;
>         } else if (binanceWS._readyState == 1) {
>             ready = true;
>         } else {
>             return;
>         }
>         while (!ready) {
>             if (binanceWS._readyState == 0) {
>                 ready = false;
>             } else if (binanceWS._readyState == 1) {
>                 ready = true;
>             } else {
>                 return;
>             }
>             await timer(100);
>         }
> 
>         console.log(`[binanceWS_btcusdt] Connected`);
> 
>         binanceWS.send(JSON.stringify(
>             {
>                 "method": "SUBSCRIBE",
>                 "params":
>                     [
>                         `btcusdt@kline_1m`,
>                         `btcusdt@kline_1h`,
>                         `btcusdt@kline_1d`,
>                     ],
>                 "id": 112
>             }
>         ))
>     };
> ```
@lpinca this is my code and error raised when I send message to websocket server.

**Comment by lpinca** [comment] 2023-11-10 14:29
```js
const binanceWS = new WebSocket(
  `wss://stream.binance.com:443/ws/ve_ware_${fromSymbol}${toSymbol}`
);

binanceWS.onopen = () => {
  // Handle problem.
  console.log('[binanceWS_btcusdt] Connected');

  binanceWS.send(
    JSON.stringify({
      method: 'SUBSCRIBE',
      params: ['btcusdt@kline_1m', 'btcusdt@kline_1h', 'btcusdt@kline_1d'],
      id: 112
    })
  );
};
```

This should not raise any error.

**Comment by ductridev** [comment] 2023-11-10 14:37
@lpinca I just try with 4G with my lap and no problem, So I believe this is a problem with my internet. Thank you for your reply.

**Comment by lpinca** [comment] 2023-11-10 14:51
It cannot be your internet connection. When the `'open'` event is emitted, the ready state is guaranteed to be 1. See https://github.com/websockets/ws/blob/a049674d936746c36fe928cc1baaaafd3029a83e/lib/websocket.js#L238-L239.

Make sure that the`WebSocket` instance you are calling `websocket.send()` on, is the same the `WebSocket` instance that emitted the `'open'` event.

**Comment by ductridev** [comment] 2023-11-10 14:55
> It cannot be your internet connection. When the `'open'` event is emitted, the ready state is guaranteed to be 1. See
> 
> https://github.com/websockets/ws/blob/a049674d936746c36fe928cc1baaaafd3029a83e/lib/websocket.js#L238-L239
> 
> .
> Make sure that the`WebSocket` instance you are calling `websocket.send()` on, is the same the `WebSocket` instance that emitted the `'open'` event.

Yes, I understand it should be 1 when emit `open` event. But it happens at my desktop just 1 hour, it doesn't happen before.

**Comment by lpinca** [comment] 2023-11-10 15:10
I'm closing this. Please reopen if you find a way to reliably reproduce the issue.

**Closed by lpinca** 2023-11-10 15:10 UTC
