### ISSUE TITLE
Cannot assign to read only property 'target' of invalid compressed data

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#553] opened 2015-08-16 05:24 UTC
Seeing this weird error few times and have no clue what the real cause is:

```
TypeError: Cannot assign to read only property 'target' of invalid compressed data
    at WebSocket.onError (/var/www/videomail/production/source/node_modules/ws/lib/WebSocket.js:422:18)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (/var/www/videomail/production/source/node_modules/ws/lib/WebSocket.js:832:10)
    at Receiver.error (/var/www/videomail/production/source/node_modules/ws/lib/Receiver.js:317:8)
    at /var/www/videomail/production/source/node_modules/ws/lib/Receiver.js:528:32
    at /var/www/videomail/production/source/node_modules/ws/lib/Receiver.js:354:9
    at InflateRaw.onError (/var/www/videomail/production/source/node_modules/ws/lib/PerMessageDeflate.js:222:5)
    at emitOne (events.js:77:13)
    at InflateRaw.emit (events.js:169:7)
    at Zlib._handle.onerror (zlib.js:366:10)
```

**Comment by psorowka** [comment] 2015-08-24 22:38
I also observe this type of error, when using iojs v3. 

The error occurs here: https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L425-L429 

From a perspective of ws this happens because the emitted error is a `string` and not an object of type `Error`. 

A workaround seems inserting:

```
if(typeof event == 'string') {

  event = new Error(event);
}
```

in the `onError` function. However, I also haven't figured out yet why the error happens in the first place.

**Comment by 3rd-Eden** [comment] 2015-08-25 06:22
@psorowka Do you have any trace on where the string originates from because I'm pretty sure we're all using Error instances.

**Comment by psorowka** [comment] 2015-08-25 09:35
@3rd-Eden I see the same trace as @binarykitchen is showing.

I cannot strictly reproduce the error. For me it happens in test cases of the mosca mqtt broker. In about 30% of the cases, the tests run without error, the rest raises either the above error or the similar variant: 

```
 Uncaught TypeError: Cannot assign to read only property 'target' of continuation frame cannot follow current opcode
      at WebSocket.onError (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:422:18)
      at emitTwo (events.js:87:13)
      at WebSocket.emit (events.js:172:7)
      at Receiver.onerror (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:832:10)
      at Receiver.error (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:317:8)
      at Receiver.processPacket (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:208:12)
      at Receiver.add (/app/node_modules/websocket-stream/node_modules/ws/lib/Receiver.js:91:24)
      at Socket.firstHandler (/app/node_modules/websocket-stream/node_modules/ws/lib/WebSocket.js:774:22)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:146:16)
      at Socket.Readable.push (_stream_readable.js:110:10)
      at TCP.onread (net.js:521:20)
```

In both cases the argument to `onError` is definitely a `string`, which causes the error message in ws.
I have the impression this occurs in a race condition when a connection is closed while one side is still trying to send data.

I have no problems with all node-versions, neither on iojs:v1 or iojs:v2.

I think what we need is a minimal sample which reproduces the error. I will give that a try.

**Comment by psorowka** [comment] 2015-08-25 10:21
@3rd-Eden actually here:
```
  self._receiver.onerror = function onerror(reason, errorCode) {
    // close the connection when the receiver reports a HyBi error code
    self.close(typeof errorCode !== 'undefined' ? errorCode : 1002, '');
    self.emit('error', reason, errorCode);
  };
```
(from:  https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L848-L852)

is the point, where ws emits a string rather than an `Error` Object.

However I could not figure out why this only happens in iojs3..

**Comment by psorowka** [comment] 2015-08-31 20:32
We just discovered the errors in mosca are gone in iojs 3.2.0. 

However, I think the `ws` error handling would still needs a fix, as described in my last post, doesn't it?

**Comment by binarykitchen** [comment] 2015-08-31 21:32
yes, absolutely @psorowka, the above code should emit an instance of the error class

**Comment by psorowka** [comment] 2015-08-31 21:44
@binarykitchen for me, the zlib (and similar) errors are gone in 3.2.0, can you confirm this for your case?

**Comment by binarykitchen** [comment] 2015-08-31 21:46
@psorowka I am still using iojs v2.5 here so please fix the bug. It is getting annoying

Let me paste a longer stack here:

```
$ cat error.log                                                                                                                                                                                            
TypeError: Cannot assign to read only property 'type' of invalid compressed data
    at WebSocket.onError (/var/www/videomail/production/source/node_modules/ws/lib/WebSocket.js:426:16)
    at emitTwo (events.js:87:13)
    at WebSocket.emit (events.js:172:7)
    at Receiver.onerror (/var/www/videomail/production/source/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/var/www/videomail/production/source/node_modules/ws/lib/Receiver.js:321:8)
    at /var/www/videomail/production/source/node_modules/ws/lib/Receiver.js:532:32
    at /var/www/videomail/production/source/node_modules/ws/lib/Receiver.js:358:9
    at InflateRaw.onError (/var/www/videomail/production/source/node_modules/ws/lib/PerMessageDeflate.js:226:5)
    at emitOne (events.js:77:13)
    at InflateRaw.emit (events.js:169:7)
    at Zlib._handle.onerror (zlib.js:366:10)
    ---- async ----
    at WriteStream._write (fs.js:1856:6)
    at WriteStream.<anonymous> (fs.js:1852:12)
    at doWrite (_stream_writable.js:292:12)
    at writeOrBuffer (_stream_writable.js:278:5)
    at InflateRaw.Writable.write (_stream_writable.js:207:11)
    at InflateRaw.Zlib.flush (zlib.js:453:10)
    at InflateRaw.<anonymous> (zlib.js:449:12)
    at InflateRaw.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at InflateRaw.emit (events.js:166:7)
    at onwriteDrain (_stream_writable.js:356:12)
    at afterWrite (_stream_writable.js:344:5)
    at onwrite (_stream_writable.js:337:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:614:5)
    ---- async ----
    at InflateRaw.Transform._read (_stream_transform.js:167:10)
    at InflateRaw.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
    at TransformState.afterTransform (_stream_transform.js:54:12)
    at Zlib.callback (zlib.js:614:5)
```

**Comment by psorowka** [comment] 2015-08-31 21:48
I have filed a PR for it: https://github.com/websockets/ws/pull/569

**Comment by binarykitchen** [comment] 2015-08-31 21:57
@psorowka thanks - just added a small comment there

**Comment by rupamkhaitan** [comment] 2015-12-16 04:30
I see similar but different error code today.. with node 4.2.3 and ws library 0.8.1

TypeError: Cannot assign to read only property 'domainEmitter' of continuation frame cannot follow current opcode
    at WebSocket.emit (events.js:136:24)
    at Receiver.onerror (/opt/cnmaestro-server/deploy/node_modules/ws/lib/WebSocket.js:851:10)
    at Receiver.error (/opt/cnmaestro-server/deploy/node_modules/ws/lib/Receiver.js:321:8)
    at Receiver.processPacket (/opt/cnmaestro-server/deploy/node_modules/ws/lib/Receiver.js:212:12)
    at Receiver.add (/opt/cnmaestro-server/deploy/node_modules/ws/lib/Receiver.js:95:24)
    at Socket.realHandler (/opt/cnmaestro-server/deploy/node_modules/ws/lib/WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by rupamkhaitan** [comment] 2015-12-24 15:06
Nodejs 4.2.4 catches this error properly in domain now and doesnt kill our process.

**Comment by leeyeh** [comment] 2016-01-23 13:42
Also: https://github.com/websockets/ws/blob/9dc7e6b4651711d47bd87bbeddb6446e5aa429e1/lib/WebSocket.js#L724-L733

**Closed** 2016-11-09 19:55 UTC
