### ISSUE TITLE
Receiving more than one message as if it were just one

### ISSUE THREAD

**Issue by PerduGames** [websockets/ws#1231] opened 2017-11-06 04:24 UTC
**## Description**

I'm having a problem, but I'm not sure if it's ws, so I apologize if it's not. But apparently it's being server-side. I'm getting stuck messages at times, which leads me to get an invalid JSON error, which is expected, because it has two JSON objects stuck together, for example:

```
message: {"newPos":{"pos":"1:1"}}{"newPos":{"pos":"2:2"}}
```

notice that they are together, two messages have been sent, and he is only returning me one with the contents of the two, the expected was thus:

```
message: {"newPos":{"pos":"1:1"}}
message: {"newPos":{"pos":"2:2"}}
```

which logically leads me to receive "_**SyntaxError: Unexpected token { in JSON at position 59**_"

**## Reproducible in:**

version: 3.2.0
Node.js version(s): v6.11.2
npm version: 3.10.10
x86_64 GNU/Linux

**## Steps to reproduce:**

```
var express = require('express');
var app = express();
var http = require('http').Server(app);

const WebSocket = require('ws').Server;
const wss = new WebSocket({ server: http, port: 8080 });

wss.on('connection', function connection(ws) {
  
    ws.on('message', function incoming(message) {
        console.log("message: " + message.toString());
        var obj = JSON.parse(message.toString());
    });
});
```

**Comment by lpinca** [comment] 2017-11-06 06:45
Do you have a piece of code to reproduces the issue?
I can only think of bad corking but we are not corking messages.

I doubt this is an issue in `ws`. Are you using other modules?

**Comment by PerduGames** [comment] 2017-11-06 12:11
I edited with the steps to reproduce, I am using the redis module, but it does not come up against ws. Maybe it's the express?

and what would be "bad corking"?

**Comment by lpinca** [comment] 2017-11-06 12:36
> Maybe it's the express?

No, `express` only handles non WebSocket connections.

Why you say it's server-side? In the above example you are only logging messages coming from the client. Are those messages coming from a browser? What is the client doing?

The above example does not reproduce the issue, it only starts a server and waits for messages. Can you also please add the client part?

**Comment by PerduGames** [comment] 2017-11-06 14:27
I'm not sure where it is. But it is true that it can also be on the client, thinking now it is more likely to be on the client, but checking the message on the client returns me as if it was being sent right, so I thought it was server side. But I may be wrong.

I am using this module for Godot Engine(a game engine) as a client https://github.com/LudiDorici/godot-lws. I think it would be too much code, and I would run out of ws if I post the client code here, so I apologize, I'll do more tests here and also ask about LudiDorici, maybe he knows what might be happening, if the problem is on the side of the customer. If it's actually on the server, I'll come back here with more information.

**Comment by lpinca** [comment] 2017-11-06 14:35
Thank you.

**Comment by lpinca** [comment] 2017-11-08 19:44
Closing as per https://github.com/LudiDorici/godot-lws/issues/4#issuecomment-342465470. Please reopen if the issue is in ws.

**Closed by lpinca** 2017-11-08 19:44 UTC
