### ISSUE TITLE
ws+Electron Angular issue (Cannot read property 'setHeader' of null)

### ISSUE THREAD

**Issue by harshkoralwala** [websockets/ws#1651] opened 2019-10-17 08:58 UTC
Hello,

I need to create a desktop application for WebSocket communication.

So I choose Angular7 + electron as technology.

In my application, there is a feature of the Test WebSocket connection.

So users can enter the Host/Ip and port details of the server for communication.
After this, the user needs to click on button.so in background WebSocket communication initializes with user giver server details.

So based on a response app shows success/fail message like  "open" event handler called it means success in connection.

if "error","close","unexpected-response" event handler called.It means failed to connect.

So users can do test connections here before actual server communication.

But here I am _facing 1 issue_ which is described below...

If user types IP/host as '192.168.0.123' and port as '4564' (wrong server info).
assume here server details are wrong, so "error"  handler called.which is perfect.

Now user types IP/host as 'localhost' and port as 4564 (wrong server info).
assume here server details again wrong,
So again "error"  clause executed, which is perfect again.
But after this 'websocket.js' file throws an internal error (after handshake timeout) and the **electron app stops responding**. refer below image...

![Screenshot from 2019-10-17 15-08-24](https://user-images.githubusercontent.com/33347464/66997483-3136c100-f0f0-11e9-9851-8d26c056457a.png)

I observed if I click on the button many times with the same server details. The functionality works fine.
But as soon as I change host/IP or port details,error event handler executed and then above **error arise after handshake timeout**.(which is 2 seconds)

My sample angular code looks like...
`
testConnection(url) {
let testClient = new this.WebSocket(url, {
      handshakeTimeout: 2000
    });
    testClient.addEventListener('error', this.onTestConnectionError.bind(this));
    testClient.addEventListener('close', this.onTestConnectionClose.bind(this));
    testClient.addEventListener('message', this.onTestConnectionMessage.bind(this));
    testClient.addEventListener('unexpected-response', this.onTestConnectionUnexpectedResponse.bind(this))
    testClient.addEventListener('open', this.onTestConnectionOpen.bind(this))
    testClient.addEventListener('upgrade', this.onTestConnectionUpgrade.bind(this))
  }
 onTestConnectionMessage() {
  }

  onTestConnectionUpgrade() {
  }

  onTestConnectionOpen() {
  }

  onTestConnectionError(err) {
  }

  onTestConnectionClose(code, msg) {
  }

  onTestConnectionUnexpectedResponse() {
  }
`
Assume here I have implemented all the above event handlers with proper coding...

my package.json for ws looks like...

"ws": "^7.1.2",

So kindly help me how can I solve this.

Thanks in advance.

**Comment by lpinca** [comment] 2019-10-17 19:21
From the stack trace I can see that the error occurs after [`req` is nulled](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L596) and the [`'timeout'` event is emitted](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L545).

This baffles me because it should never happen. `req` is nulled only when the `'upgrade'` event is emitted, and when this happens the socket is freed so the `'timeout'` event should no longer be re-emitted on the `req` object. Furthermore the socket is either destroyed or its timer reset with [`socket.setTimeout(0)`](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L161) if the `'upgrade'` event is emitted.

Can you try to monkey patch ws to verify that the [`'upgrade'` event](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L587) is actually emitted when the error occurs and if so can you check if `socket.setTimeout(0)` is called?

Are you able to create a minimal reproducbile test case?

**Comment by harshkoralwala** [comment] 2019-10-18 05:24
Hello @lpinca,

Thank you for your reply.

As you suggested to implement the 'upgrade' event handler on client-side(angular).I have already implemented that. My handler function looks like...

> onTestConnectionUpgrade() {
    console.log(">>>>>>>>>>>>>>>  onTestConnectionUpgrade !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
  }

But this log is **NEVER** printed on the console!!!

To understand better we have created  _WS node client(nodejs)_ with handshake timeout and other configuration same as angular app.

We have noticed, _NodeJs client works fine_ in all cases which are _failing for angular app_.

Furthermore, We have added console logs in the internal [WebSocket file](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js) js file.

We have noticed by logs that, for node client when an error occurs, the ['error' event is emitted](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L549) and 'req' object become null. Then never[ 'timeout' event ](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L544) emitted for nodeJS client.

Same thing with an Angular app and logs, when an error occurs, the ['error' event is emitted](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L549) and 'req' object become null. 
But after handshake timeout **[ 'timeout' event ](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L544) is emitted**!!! so **this is the issue** that arises with the angular app.

So issue is how can **timeout event** is gets called when **object is already nulled**.

I have no idea how can i create test case for you to investigate as my application is desktop application.
And with angular web application i believe i can not use '**ws**' library as my version is angular 7.

Thank you.

**Comment by lpinca** [comment] 2019-10-18 05:55
Ok, so it seems that `'timeout'` is emitted after [`'error'`](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L549). This looks like a bug in Node.js core. I will investigate.

In the mean time a possible workaround is to remove the [`'timeout'` listener](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L544-L546) when the [`'error'` event](https://github.com/websockets/ws/blob/7.1.2/lib/websocket.js#L549) is emitted.

**Comment by harshkoralwala** [comment] 2019-10-18 06:34
Hello @lpinca,

Thank you again for your reply...

As to do change in _node_modules's any file_, it's **not a good idea** as we need to **keep track** of this and need to **update all other colleagues**.

So what we have done is...
We have **removed handshake timeout**.

We have added **setTimeout**,(refer code below)

There is a flag which maintains that connection established or not(true/false).value is set in event handler like in 'open' hander true and in 'error' as false.

setTimeout implementation is described below...

so if flag value is **true**(which is set in 'open' event handler), **nothing to do** as already connection established.

If the **flag is false** means till time **no connection created** or **no event handler gets called**, So just **terminate the connection** and do a **process of connection failure**.

My new code looks like...

> 
 testConnection(url) {
    this.isTestConnectionActive = false;
    const self = this;
    try {
      this.testClient = new self.WebSocket(url);
      setTimeout(() => {
        //wait for 2.5 second,if connection not established consider it as fail operatin
        if (myflag == false) {
          self.testClient.terminate();
//some logic here of fail connection
        }
      }, 2500);
      this.testClient.addEventListener('error', self.onTestConnectionError.bind(self));
      this.testClient.addEventListener('close', self.onTestConnectionClose.bind(self));
      this.testClient.addEventListener('message', self.onTestConnectionMessage.bind(self));
      this.testClient.addEventListener('unexpected-response', self.onTestConnectionUnexpectedResponse.bind(self))
      this.testClient.addEventListener('open', self.onTestConnectionOpen.bind(self))
      this.testClient.addEventListener('upgrade', self.onTestConnectionUpgrade.bind(self))
    } catch (ex) {
//consider here as connection failed to connect
    }
  }

Looking for this bug solution in **next** **releases.**

Thank you.

**Comment by lpinca** [comment] 2019-10-18 07:44
On what version of Node.js (embedded in Electron) does this happen?

**Comment by harshkoralwala** [comment] 2019-10-18 07:57
Hello @lpinca ,

OS: Ubuntu 18.04.3 LTS (Linux x64)
Angular CLI: 7.3.9
Node: 10.16.3
Angular: 7.2.15
Electron:5.0.1


Thank you.

**Comment by lpinca** [comment] 2019-10-18 08:52
@harshkoralwala I don't know if something is different in the Node.js embedded in Electron 5.0.1 but I cannot reproduce:

```
luigi@ubuntu:~$ uname -a
Linux ubuntu 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
luigi@ubuntu:~$ node -v
v10.16.3
luigi@ubuntu:~$ cat test.js
'use strict';

const { connect } = require('net');
const { get } = require('http');
const { kTimeout } = require('internal/timers');
const { deepStrictEqual, strictEqual } = require('assert');

function createConnection(options) {
  return connect(options);
}

const result = {
  timeoutEventEmitted: false,
  socketEventEmitted: false,
  errorEventEmitted: false
};

const request = get({
  createConnection,
  host: 'localhost',
  port: 4564,
  timeout: 2000
});

request.on('timeout', function() {
  result.timeoutEventEmitted = true;
});

request.on('socket', function(socket) {
  result.socketEventEmitted = true;
  strictEqual(socket[kTimeout]._idleTimeout, 2000); // Timeout is set.
});

request.on('error', function() {
  result.errorEventEmitted = true;
  strictEqual(request.socket[kTimeout]._idleTimeout, -1); // Timeout is cleared.
});

process.on('exit', function() {
  deepStrictEqual(result, {
    timeoutEventEmitted: false,
    socketEventEmitted: true,
    errorEventEmitted: true
  });
});
luigi@ubuntu:~$ node --expose-internals test.js
luigi@ubuntu:~$
```

This is what ws does internally.

**Comment by harshkoralwala** [comment] 2019-10-18 10:21
Hello @lpinca ,

Thank you for sharing code and it looks correct.

I believe there is some issue with integrating electron and nodejs itself. But I don't know whats exactly issue.

By assuming this I am leaving this topic as I have already implemented an alternative solution mentioned above by me.

Thank you for your time and efforts.

**Comment by lpinca** [comment] 2019-10-19 06:02
Ok, I'm closing this then.

**Closed by lpinca** 2019-10-19 06:02 UTC
