### ISSUE TITLE
heap out of memory

### ISSUE THREAD

**Issue by huangjilaiqin** [websockets/ws#999] opened 2017-02-12 07:56 UTC
I try to write a chat room,simple code

Server code:
```javascript
'use strict';

const WebSocket = require('ws');

const wss = new WebSocket.Server({
  perMessageDeflate: false,
  port: 8080
});

var clients={};
var incid=1;
wss.on('connection',function(ws){
  var wsid=incid++;
  clients[wsid]=ws;

  ws.on('message',function(data){
  for(let id in clients)
    clients[id].send(data);
  });
  ws.on('close',function(){
    delete clients[wsid];
    console.log('on close',wsid);
  });
});
```

Client code:
```javascript
'use strict';

const WebSocket = require('ws');
const schedule = require('node-schedule');

function getWs(){
  return new WebSocket('ws://localhost:8080', {
    perMessageDeflate: false
  });
}

var seconds=[];
for(let i=0;i<60;i++)
  seconds.push(i);

for(let i=0;i<500;i++){
  let ws=getWs();
  ws.on('open',function(){
    console.log('on open');
    let rule = new schedule.RecurrenceRule();
    rule.second = seconds;
    schedule.scheduleJob(rule, function(){
      ws.send('request from client i:'+i);
    });
  });

  ws.on('message',function(data){
    //console.log('message',data);
  });
}
```

Error:
![error](https://cloud.githubusercontent.com/assets/10682938/22860515/19c3cb1a-f13b-11e6-9181-caba43aed32c.png)

**Comment by huangjilaiqin** [comment] 2017-02-12 08:18
@lpinca please help,3q

**Comment by lpinca** [comment] 2017-02-12 10:49
@huangjilaiqin hi,
Are you using `ws@2.0.3`? What is the operating system? I can't reproduce the issue with `ws@2.03` on macOS.

I've simplified the client code like this:

```js
'use strict';

const WebSocket = require('ws');

const clients = [];

(function open() {
  const ws = new WebSocket('ws://localhost:8080');

  ws.on('open', () => {
    clients.push(ws);
    console.log(clients.length);
    if (clients.length < 500) open();
  });
})();

setInterval(() => {
  clients.forEach((ws, i) => ws.send(`request from client i: ${i}`));
}, 1000);
```

**Comment by lpinca** [comment] 2017-02-12 11:41
Ok, I think I've managed to reproduce the issue which happens when killing all the clients (the client process) after a while.

I can also reproduce the issue with `ws@1.1.1` so this is not something we introduced with version 2.0.0.

**Comment by huangjilaiqin** [comment] 2017-02-12 16:01
@lpinca  I use CentOS release 6.5 (Final)，my version is 2.0.3, yes mac will not crash with this error,but the terminal like dead after run a while, I test in linux and windows the rss keep growing and crash finally, I doubt gc not recycle momery as fast as used,so lead to crash. Thank for your response! I will keep testing the problem.

**Comment by lpinca** [comment] 2017-02-12 16:08
My guess is that this issue happens because backpressure is not handled so data sent from client to server keeps being buffered server-side until the process goes OOM.

**Comment by huangjilaiqin** [comment] 2017-02-12 16:25
I use node-heapdump found there a big array with object wicth contain msg like 'xxxxx.... response from server',  if I chage server code to this : 
```javascript
ws.on('message',function(data){
  for(let id in clients)
    clients[id].send(data+'response from server');
  });
````

**Comment by lpinca** [comment] 2017-02-12 17:21
@huangjilaiqin yes, that is also an issue (server to client backpressure), but you can handle that. You can either use the `send` callback or the [`websocket.bufferedAmount`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketbufferedamount) getter.

If the `bufferedAmount` is bigger than a given threshold you shouldn't keep calling `send`.

**Comment by huangjilaiqin** [comment] 2017-02-13 01:58
@lpinca but I think I should find where is the  bottleneck, and fixed to make my nodejs server can handle more client and more. #heap out of memory# because v8 has memory limit, but Buffer is not alloc by v8 can we use Buffer to fixed this problem?

**Comment by huangjilaiqin** [comment] 2017-02-13 14:10
@lpinca do you have any idea to solve this problem and not effect the normal client, and this problem make nodejs server easy to attack, just a js file make server to crash.hope to see your idea

**Comment by lpinca** [comment] 2017-02-13 17:12
No, not really, as I wrote in the previous comment you shouldn't keep calling `send()` if data is getting buffered and not sent over the wire.

**Comment by lpinca** [comment] 2017-05-21 06:50
Closing, feel free to continue discussing on the closed thread.

**Closed by lpinca** 2017-05-21 06:50 UTC
