### ISSUE TITLE
PerMessageDeflate.js error

### ISSUE THREAD

**Issue by duwayy** [websockets/ws#984] opened 2017-02-01 13:01 UTC
Hello,
Recently installed node ws via npm to run an Ogar server, but I get this error when I try to load ws module:
```
[...]/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
```

Any help please ?
I'm on Ubuntu 16
Thanks !

**Comment by JacksonTian** [comment] 2017-02-01 13:08
What's version of Node.js.

**Comment by lpinca** [comment] 2017-02-01 13:29
@duwayy as requested by @JacksonTian what's the result of?

```
node -v
```

**Comment by duwayy** [comment] 2017-02-01 13:34
v7.5.0 (latest I think)

**Comment by lpinca** [comment] 2017-02-01 13:38
Weird, does it throw if you create the buffer from the REPL?

```
$ node
> Buffer.from([0x00, 0x00, 0xff, 0xff]);
<Buffer 00 00 ff ff>
>
```

**Comment by duwayy** [comment] 2017-02-01 13:40
It give me the same output as yours.. :/

**Comment by lpinca** [comment] 2017-02-01 13:41
Can you post the full stack trace of the error?

**Comment by duwayy** [comment] 2017-02-01 13:43
Is it what you asked for ?
```
/var/www/html/agario/MultiOgar-Edited-Instant/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/var/www/html/agario/MultiOgar-Edited-Instant/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/html/agario/MultiOgar-Edited-Instant/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
```

**Comment by lpinca** [comment] 2017-02-01 13:44
Yes, thanks.

**Comment by lpinca** [comment] 2017-02-01 13:56
Are you using a modified version of this https://github.com/Megabyte918/MultiOgar-Edited?
If so I think the problem is caused by its start script which uses [`nodejs`](https://github.com/Megabyte918/MultiOgar-Edited/blob/642a4d452e850110b89c5759b84244c6b09c0e2b/run/lin-Start.sh#L24) instead of `node`.

Try to uninstall `nodejs`:

```
apt-get purge nodejs
```

**Comment by duwayy** [comment] 2017-02-01 13:58
Is node different than nodejs ? After uninstalling nodejs, when trying to run server it say nodejs not found

**Comment by duwayy** [comment] 2017-02-01 14:01
I replaced "nodejs" by node in Multiogar launcher and it works now

Thank you for your help :)

**Comment by lpinca** [comment] 2017-02-01 14:08
I think that by default `apt-get install nodejs` installs an outdated Node.js version.
You probably have 2 version of Node.js installed. Closing, please comment of reopen if needed.

**Closed by lpinca** 2017-02-01 14:08 UTC
