### ISSUE TITLE
Corrupted messages between server and client

### ISSUE THREAD

**Issue by LewisTehMinerz** [websockets/ws#1285] opened 2018-01-21 18:25 UTC
- [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

Randomly, data sent between server and client is corrupted.

#### Reproducible in:

version: 4.0.0
Node.js version(s): 9.3.0
OS version(s): Windows 10 Fall Creators Update

#### Steps to reproduce:

I don't believe this is reproducible, as it is spontaneous.

### Expected result:

The tests should pass and there should be no corrupted data.

### Actual result:

In the same spot (for me at least) there is a corrupted message being sent, causing the test to fail.

### Attachments:

```
/e/Node Projects/PancakeDB npm run test

> pancakedb@0.0.1-dev test E:\Node Projects\PancakeDB
> mocha --reporter mocha-circleci-reporter --bail



  Client
    √ should connect
    AUTH
      √ should deny access when using an incorrect password
      √ should grant access when using a correct password
    CREATE
      DATABASE
        √ should create 1 database by the name test_database
        √ should create 1 database by the name test_database1
      TABLE
        √ should create a table by the name test_table in the database test_database
        √ should create a table by the name test_table1 in the database test_database1
    INSERT
      1) "before all" hook


  7 passing (39ms)
  1 failing

  1) Client INSERT "before all" hook:

      Uncaught AssertionError: expected 'RE�\u0002OK�' to equal 'OK'
      + expected - actual

      -RE�╗OK�
      +OK

      at WebSocket.ws.on.m (test\test.js:108:30)
      at Receiver._receiver.onmessage (node_modules\ws\lib\websocket.js:145:47)
      at Receiver.dataMessage (node_modules\ws\lib\receiver.js:430:14)
      at Receiver.getData (node_modules\ws\lib\receiver.js:368:12)
      at Receiver.startLoop (node_modules\ws\lib\receiver.js:164:16)
      at Receiver.add (node_modules\ws\lib\receiver.js:138:10)
      at Socket._ultron.on (node_modules\ws\lib\websocket.js:143:54)
      at addChunk (_stream_readable.js:252:12)
      at readableAddChunk (_stream_readable.js:239:11)
      at Socket.Readable.push (_stream_readable.js:197:10)
      at TCP.onread (net.js:589:20)
```

Also, on an unrelated note, I get RSV2 and RSV3 errors (`Uncaught RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear`) most of the time whenever I test PancakeDB (for example, https://circleci.com/gh/PancakeDB/PancakeDB/42).

**Comment by lpinca** [comment] 2018-01-21 19:20
Are you using ws for both the server and the client? what you can do is trying to add a listener for the `'data'` event on the internal socket and see what is received when the error occurs.

```js
ws._socket.prependListener('data', console.log);
```

**Comment by lpinca** [comment] 2018-01-21 19:48
Anyway why all these [tests](https://github.com/PancakeDB/PancakeDB/blob/ea12619de99d035fe42346807a967b4d8b59ca1c/test/test.js#L44-L49) are sync?
If I'm not wrong each of them should wait for a message. In that case they should be async.

```js
it('should deny access when using an incorrect password', (done) => {
    ws.once('message', m => {
        expect(m).to.equal('AUTH_FAIL');
        done();
    });
    ws.send('AUTH this_is_not_the_password');
});
```

**Comment by LewisTehMinerz** [comment] 2018-01-21 20:35
It's been a while since I've had to write a test case.

Anyway...

I use ws for both server and client, and I cannot get the issue to replicate. I'll keep you updated if it happens again.

**Comment by lpinca** [comment] 2018-01-23 19:55
Closing as the issue was caused by broken tests on PancakeDB.

**Closed by lpinca** 2018-01-23 19:55 UTC

**Comment by LewisTehMinerz** [comment] 2018-01-23 20:03
👌
