### ISSUE TITLE
Error: "ECONNRESET" after a client disconnect. Can't handle the error.

### ISSUE THREAD

**Issue by ProgrammingLife** [websockets/ws#1266] opened 2017-12-29 22:17 UTC
#### Description

My code is: 
```
const WebSocket = require( 'ws' );
const wss = new WebSocket.Server( { port: 1337 } );
function wssHeartbeat() { this.isAlive = true; }
wss.on( 
	'connection', 
	( ws ) => {
		ws.isAlive = true;
		ws.on( 'pong', wssHeartbeat );
		ws.on( 'message', function incoming( message ) {
			console.log( 'RECEIVED: %s', message );
		});
		ws.send( 'qrqrwererweq435543!!!' );
	}
);

const interval = setInterval(
	function ping() {
		wss.clients.forEach(
			function each(ws) {
				if ( ws.isAlive === false ) return ws.terminate();
				ws.isAlive = false;
				ws.ping( '', false, true );
			}
		);
	}, 
	4000 );

wss.on( 'close', function close() {
	console.log( 'disconnected' );
} );

wss.on( 'error', () => console.log( 'error!!!' ) );
```

When the client has disconnect I get:

> events.js:182
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: read ECONNRESET
>     at _errnoException (util.js:1041:11)
>     at TCP.onread (net.js:606:25)

Even if I try to handle the error. So my server crashes and I need to run it again manually.

Tried to remove node_modules folder and packages_lock.js file and install it again. But it doesn't solve the problem.

#### Reproducible in:

WS version: 3.3.3
Node.js version(s): v9.3.0
OS version(s): MacOS X

#### Steps to reproduce:

1. Run the server
2. Connect with client
3. Disconnect the client

**Comment by lpinca** [comment] 2017-12-30 06:46
Duplicate of #1256.

**Closed** 2017-12-30 06:59 UTC
Labels: duplicate
