### ISSUE TITLE
How to check client is connected in web socket?

### ISSUE THREAD

**Issue by waleedbutt** [websockets/ws#353] opened 2014-08-09 14:31 UTC
My question is that I am using web socket for my iphone native app so if user is disconnected the internet then web socket cannot get the state of client that it is close or disconnect. my code is here
var webSocketServer = new (require('ws')).Server({port: (process.env.PORT || 5000)}),
webSockets = {} // userID: webSocket
//Delete userID from connected list of userID
  webSocket.on('close', function () 
  {
    delete webSockets[userID]
    util.log('User_id: [' + userID+'] deleted from Connected users list: ['+ Object.getOwnPropertyNames(webSockets)+' ]');

  })

but if i use that code it did not work.

// if client is disconnect with internet
webSocket.on('disconnect',function()
  {
   console.log('hello i am disconnected');  
  });

**Comment by humingchun** [comment] 2015-02-27 07:37
I had the same issue and after some Googling, here is result:

WebSocket is based on TCP and TCP uses FIN packet to close the connection. In the case of sudden loss of Internet connection, both the WebSocket server and the phone are unware of the already dead TCP connection because no FIN packet was sent.

To address the issue, TCP has a mechanism called [keepalive](http://en.wikipedia.org/wiki/Keepalive#TCP_keepalive).

What I did to solve the issue is adjusting the [TCP keepalive settings](http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html) in Linux kernel, and invoke `ws._socket.setKeepAlive(true)`.

I am going to propose a new public method `setKeepAlive` to ws so it clearly shows a way for ws to use the underlying TCP mechanism to maintain connection or detect dead connection.

**Comment by waleedbutt** [comment] 2015-02-27 11:26
Hi humingchun
Thanks for update. Can you please tell me that after set ws._socket.setKeepAlive(true). How socket disconnect those client or delete from connected user list ?

**Comment by humingchun** [comment] 2015-02-27 17:15
Hi waleedbutt, for the detailed introduction for TCP keepalive machanism, you could refer to the link I posted before.

And after the keepalive detects the failure of the connection, TCP layer will raise a `close` event which is forwarded to ws. So you could just listen to ws's `close` event and do any necessary clean ups.

For example, you want to detect a dead TCP connection within 10 seconds, you can set following kenel params:
```
net.ipv4.tcp_keepalive_time=6
net.ipv4.tcp_keepalive_intvl=2
net.ipv4.tcp_keepalive_probes=2
```
It will add a little more extra network traffic, but you can choose to enable keep alive to specific TCP connection by invoking `ws._socket.setKeepAlive(true)`

**Comment by binarykitchen** [comment] 2015-08-16 22:21
this is interesting - but let me clarify something: what when i am on the road with the mobile, having an open websocket connection to the server for app X but loose connection for few seconds during a cell handover? will the above trick resume the same connection or create a new one?

**Comment by Spentas** [comment] 2015-11-21 19:11
binarykitchen,it depends on your client side implementation.As i tested on android, immediately after re-connection it  will close the current session and generate a new one.

**Comment by binarykitchen** [comment] 2015-11-22 01:28
why can't we re-use the session when re-connecting? @Spentas

**Comment by Spentas** [comment] 2015-11-22 13:30
simply cause your ip address may change upon reconnection and the old session is bound to an invalid ip address

**Comment by binarykitchen** [comment] 2015-11-22 20:57
hmmm, are websocket sessions really bound to an ip address instead of a token??

**Comment by Spentas** [comment] 2015-11-23 02:55
what is token made of?

**Comment by vlivanov** [comment] 2015-11-28 14:20
binarykitchen, websocket is basically a tcp/ip connection, there is no reconnection option. What we do in our android app, we use telephone manager to subscribe on cell change event. If it triggers, we just do the reconnect manually

**Comment by binarykitchen** [comment] 2015-11-29 00:54
sure i understand that. reason i am asking all that is because my www.videomail.io app is having issues on androids when you are moving from one cell to another. when reconnected, new streams are instantiated instead of the existing one which makes it very difficult to send data to the same destination on the server side.

**Comment by snowbreeze** [comment] 2016-06-28 17:09
How to implent the fix @humingchun . Where do i set ws._socket.setKeepAlive?

**Comment by abrarjahin** [comment] 2016-07-25 12:47
Hi, I am using this library in Node.js - https://www.npmjs.com/package/express-ws
To implement `websocket`.

But I am not finding any way of running this code-

`ws._socket.setKeepAlive(true)`

Can anyone please help?

**Comment by slava-osipov-qs** [comment] 2016-08-09 09:12
Hi,
> ws._socket.setKeepAlive

You can found answer [here](http://stackoverflow.com/questions/35503895/nodejs-websocket-detect-disconnected-socket)

**Comment by lpinca** [comment] 2017-05-12 19:57
A possible way is to use something like this: https://github.com/websockets/ws#how-to-detect-and-close-broken-connections.
Closing, feel free to continue discussing on the closed thread.

**Closed by lpinca** 2017-05-12 19:57 UTC

**Comment by Bomper** [comment] 2018-01-11 19:10
@lpinca: that's only for verifying as a server, that the client is still connected. How about [reconnecting, as a client, when the connection no longer sends data for a while](https://github.com/coinbase/gdax-node/issues/104)?

**Comment by lpinca** [comment] 2018-01-11 19:15
Add a timer on the client that terminate the connection when expires, clear the timer every time a ping is received from the server.

**Comment by Bomper** [comment] 2018-01-12 22:49
@lpinca: that's what I did in [this sample](https://github.com/pladaria/reconnecting-websocket/issues/48), but it's not that straightforward to reconnect. Not even reconnecting-websocket manages to.

**Comment by kashishkhullar** [comment] 2018-10-18 09:00
Is there any close event that the websockets emit which we can listen to whenever a connection breaks. eg:
`var sockets = [ ] ; // here i save all the socket `
then I do this
`sockets.forEach( socket => socket.on('close', console.log("Connection closed"));`

or can I add the same logic whenever a new connection opens?

**Comment by kenethcinco** [comment] 2019-11-10 09:48
setTimeout(function() {
	console.log(socket.connected);
},500);
