### ISSUE TITLE
Handle an error when message could not been sent

### ISSUE THREAD

**Issue by Josema** [websockets/ws#923] opened 2016-12-06 11:09 UTC
This code is running in the same node.js script
```js
server.close(); // This is a socket created with new WebSocket('ws://localhost:1234/test');
clientX.send("something"); // This is a socket from wss.on('connection', function connection(clientX ...
```

Here I am trying to close the connection to the server from the client. The message is never caught by the client.

I tried `clientX.send("something", function(err){ ... });` but err is always undefined. And the readyState for clientX is OPEN.

Is this message being missed or is just because `server.close()` flag the client as close and do not emit more message events?

**Comment by lpinca** [comment] 2016-12-06 11:25
The message is probably sent but I'm not sure why it doesn't reach the client.
Can you post a reproducible test case?

**Comment by Josema** [comment] 2016-12-06 11:35
```js
var WebSocket = require('ws'),
    wss = new WebSocket.Server({ port:1234 });

//server
wss.on('connection', function connection(client) {
    client.send('something1');
    setTimeout(function(){
        serverConnection.close(); // Comenting this something2 will be handle
        client.send('something2');
    }, 2000)
});



//client
var serverConnection = new WebSocket('ws://localhost:1234');
serverConnection.on('message', function incoming(message) {
    console.log('received: %s', message);
});
```

**Comment by lpinca** [comment] 2016-12-06 11:48
From a quick look it seems a duplicate of #799.
Try to disable permessage-deflate and see if it works.

The problem is that the client receives a TCP FIN packet when data is being decompressed. It's a bug that should be fixed.

**Comment by Josema** [comment] 2016-12-06 11:52
Any help to disable `permessage-deflate`? Don't know how to do it.

**Comment by lpinca** [comment] 2016-12-06 11:53
Use `perMessageDeflate: false` in the server options:

```
const wss = new WebSocket.Server({ perMessageDeflate: false, port:1234 });
```

**Comment by Josema** [comment] 2016-12-06 11:55
It works! Thank you!

**Comment by lpinca** [comment] 2016-12-06 11:55
No problem.

**Comment by Josema** [comment] 2016-12-08 03:52
`perMessageDeflate` has a big side effect.  
If `serverConnection` close the connection just after the connection is established then the event `close` is not emitted either in client and server.

I wouldn't recommend use this.

**Closed** 2017-01-03 07:27 UTC
