### ISSUE TITLE
Bug: v8.18.0 released major breaking change (not minor) and data sent as Blob (not Buffer)

### ISSUE THREAD

**Issue by titanism** [websockets/ws#2239] opened 2024-07-04 02:48 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

See comment here <https://github.com/websockets/ws/pull/2229#issuecomment-2207912046>

### ws version

8.18.0

### Node.js Version

latest

**Comment by lpinca** [comment] 2024-07-04 05:41
Are you are setting [`websocket.binaryType`](https://github.com/websockets/ws/blob/master/doc/ws.md#websocketbinarytype) to `'blob'`?

**Comment by lpinca** [comment] 2024-07-04 09:42
Please share a minimal test case to reproduce the issue. I am unable to do it with the provided info. The following example works as expected.

```js
import { WebSocket, WebSocketServer } from 'ws';
import { pack, unpack } from 'msgpackr';

const wss = new WebSocketServer({ port: 0 }, function () {
  const { port } = wss.address();
  const ws = new WebSocket(`ws://127.0.0.1:${port}`);

  ws.on('open', function () {
    ws.send(pack('Hello'));
    ws.close();
  });
});

wss.on('connection', function (ws) {
  ws.on('message', function (buf) {
    console.log(unpack(buf));
  });

  ws.on('close', function () {
    wss.close();
  });
});
```

**Comment by lpinca** [comment] 2024-07-05 06:09
Maybe it was already set. It was simply ignored before.

**Comment by billti** [comment] 2024-07-11 22:22
This is breaking our dependably security bump also. Not sure why as it's a transitive dependency via JupyterLab. I'll see if I can figure out more, but sharing early here for more evidence.

<https://github.com/microsoft/qsharp/pull/1730> (see details at <https://github.com/microsoft/qsharp/actions/runs/9895969380/job/27337054057?pr=1730#step:9:777>)

**Comment by billti** [comment] 2024-07-11 23:39
Ignore that last post - it was bumps to other packages as part of dependabot bumping 'ws' causing the issue in my case, (which I've fixed now via https://github.com/microsoft/qsharp/pull/1734 ). Sorry for the noise.

**Comment by lpinca** [comment] 2024-07-18 05:34
I'm closing this due to inactivity.

**Closed by lpinca** 2024-07-18 05:34 UTC
