### ISSUE TITLE
Unit tests for websocket timeouts

### ISSUE THREAD

**Issue by binarykitchen** [websockets/ws#536] opened 2015-07-29 01:07 UTC
This is more a question: do you have unit tests concerning websocket timeouts?

Because in this issue https://github.com/maxogden/websocket-stream/issues/69 I am struggling building an unit tests that triggers a websocket timeout on localhost.

**Comment by lpinca** [comment] 2017-03-11 14:45
@binarykitchen the issue you linked is probably caused by NGINX. From http://nginx.org/en/docs/http/websocket.html

> By default, the connection will be closed if the proxied server does not transmit any data within 60 seconds. This timeout can be increased with the proxy_read_timeout directive. Alternatively, the proxied server can be configured to periodically send WebSocket ping frames to reset the timeout and check if the connection is still alive.

Closing this, please comment if needed.

**Closed by lpinca** 2017-03-11 14:45 UTC
