### ISSUE TITLE
Pleas update your @types/ws 

### ISSUE THREAD

**Issue by Traineratwot** [websockets/ws#1943] opened 2021-09-07 18:54 UTC
Pleas update your  @types/ws 
![image](https://user-images.githubusercontent.com/41589091/132396438-27e40766-2f74-4ed8-812b-54e25961021b.png)

**Comment by lpinca** [comment] 2021-09-08 04:53
Duplicate of https://github.com/websockets/ws/issues/1932.

**Closed by lpinca** 2021-09-08 04:53 UTC
