### ISSUE TITLE
WARNING in ./node_modules/ws/lib/BufferUtil.js on using of Websocket in storybook

### ISSUE THREAD

**Issue by waheed25** [websockets/ws#1236] opened 2017-11-13 09:42 UTC
hi, i am using websocket in my config file but after usage of websocket i am getting warnings like that
`
WARNING in ./node_modules/ws/lib/BufferUtil.js
Module not found: Error: Can't resolve 'bufferutil' in '/home/waheed/Projects/Components/node_modules/ws/lib'
 @ ./node_modules/ws/lib/BufferUtil.js 35:21-42
 @ ./node_modules/ws/lib/PerMessageDeflate.js
 @ ./node_modules/ws/lib/WebSocketServer.js
 @ ./node_modules/ws/index.js
 @ ./dev/client.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js

WARNING in ./node_modules/ws/lib/Validation.js
Module not found: Error: Can't resolve 'utf-8-validate' in '/home/waheed/Projects/Components/node_modules/ws/lib'
 @ ./node_modules/ws/lib/Validation.js 10:22-47
 @ ./node_modules/ws/lib/Receiver.js
 @ ./node_modules/ws/index.js
 @ ./dev/client.js
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/react/dist/server/config/polyfills.js ./node_modules/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true 
./.storybook/config.js
`
i just want to remove these warnings on my console .how can i remove these warnings.

**Comment by lpinca** [comment] 2017-11-13 11:22
Duplicate of #1220. See discussion there.

**Comment by waheed25** [comment] 2017-11-13 11:47
but this is not in webpack this in storybook

**Comment by lpinca** [comment] 2017-11-13 12:00
Those warnings are created by webpack which is used by storybook. If you are using `ws` directly you should add a shim for it like [this](https://github.com/SocketCluster/socketcluster-client/blob/87ac534521471e8da6cc95967a7af059601fdd2a/lib/ws-browser.js) and add it yo your package.json using the `browser` key.

**Comment by WQHASH** [comment] 2017-11-13 12:08
对于刚学习websockets有什么推荐？

**Comment by WQHASH** [comment] 2017-11-13 12:09
What's the recommendation for learning WebSockets?

**Comment by lpinca** [comment] 2017-11-13 16:38
Closing as there is not much we can do about this.

**Closed by lpinca** 2017-11-13 16:38 UTC

**Comment by svngoku** [comment] 2018-01-17 15:08
That's not a real warning! You can forget it

**Comment by jrodl3r** [comment] 2018-12-31 20:30
```
module.exports = {
  ...,
  stats: 'errors-only'
}
```
