### ISSUE TITLE
pong not emitted anymore?

### ISSUE THREAD

**Issue by ea167** [websockets/ws#2010] opened 2022-02-02 08:27 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

First of all, thanks for this great lib.

In 8.4.2, pong does not seem to be emitted anymore when a ping is received.
Was working at least in 7.x

### ws version

8.4.2

### Node.js Version

16.13.2

**Comment by lpinca** [comment] 2022-02-02 11:12
I cannot reproduce:

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('open', function () {
    ws.ping();
  });

  ws.on('pong', function () {
    console.log('pong');
    ws.close();
    wss.close();
  });
});
```

```js
const WebSocket = require('ws');

const wss = new WebSocket.Server({ port: 0 }, function () {
  const ws = new WebSocket(`ws://localhost:${wss.address().port}`);

  ws.on('pong', function () {
    console.log('pong');
    ws.close();
    wss.close();
  });
});

wss.on('connection', function (ws) {
  ws.pong();
});
```

Both examples work as expected.

**Comment by lpinca** [comment] 2022-02-06 06:15
I'm closing this. Discussion can continue if needed.

**Closed by lpinca** 2022-02-06 06:15 UTC
