### ISSUE TITLE
Once connection  is established and close event 1006 after 30 secs

### ISSUE THREAD

**Issue by MingJiang1988** [websockets/ws#1648] opened 2019-10-14 07:23 UTC
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Reproducible in:

- version: 7.1.2
- Node.js version(s): 10.15
- OS version(s): Windows 10

#### Steps to reproduce:

1.

2.

3.

#### Actual result:

![1006](https://user-images.githubusercontent.com/31149697/66734621-62b45000-ee96-11e9-986b-36c5f270d3d3.jpg)

**Comment by lpinca** [comment] 2019-10-14 14:19
Can you please clarify? What is the problem?

**Comment by MingJiang1988** [comment] 2019-10-14 14:36
I connected websocket server but after 30 seconds connection is closed by 1006 code
There is no websocket error.

**Comment by lpinca** [comment] 2019-10-14 14:40
It's possible that the server or a proxy between your client and the server closes the connection after a timeout if there is no activity.

Try to periodically send some data on ping messages.

**Comment by MingJiang1988** [comment] 2019-10-14 15:05
I sent data via connection every 10 seconds but closed

**Comment by rgawenda** [comment] 2019-10-14 15:15
is data received at the endpoint?

**Comment by MingJiang1988** [comment] 2019-10-14 16:46
yeah

**Comment by lpinca** [comment] 2019-10-14 17:58
@MingJiang1988 I cannot reproduce:

```js
const WebSocket = require('ws');

const ws = new WebSocket('wss://echo.websocket.org/', {
  origin: 'https://www.websocket.org',
  protocolVersion: 13
});

ws.on('open', () => {
  ws.send(Date.now());
});

ws.on('message', (timestamp) => {
  const now = Date.now();

  ws.send(now);
  console.log('latency %s', (now - timestamp) / 2);
});
```

**Comment by lpinca** [comment] 2019-10-17 19:29
Closing as I cannot reproduce the issue.

**Closed by lpinca** 2019-10-17 19:29 UTC
