### ISSUE TITLE
Connect to websocket under cloudflare causes 403 forbidden error

### ISSUE THREAD

**Issue by car1ot** [websockets/ws#1925] opened 2021-08-01 15:54 UTC
- [ ] I've searched for any related issues and avoided creating a duplicate
      issue.

#### Description

I am trying to connect to websocket under cloudflare, and it refuse connection with 403 forbidden error.

When I am trying this in node.js, connection refused with 403 code.
```
new WebSocket('wss://live-arena-rjsqbe.agar.io/?party_id=GPUBAM', [], {
            headers: {
                Accept: `*/*`,
                "Accept-Encoding": `gzip, deflate, br`,
                "Accept-Language": `en-GB,en;q=0.5`,
                "Cache-Control": `no-cache`,
                Connection: `keep-alive, Upgrade`,
                ... More headers here ...
            },
        })
```
```
        "websocket": "^1.0.34",
        "ws": "^7.1.2",
        "wss": "^3.3.4"
```

When I am trying to connect to websocket in this way from browser, it works fine.

**Comment by lpinca** [comment] 2021-08-01 18:54
This is not a `ws` issue. The server is responding with 403 which means that access is forbidden. You probably need to add a `Cookie` or `Authorization` header. See what headers are sent in the browser. Also make sure you are actually using `ws`. `websocket` and `ws` are two different modules.

**Comment by car1ot** [comment] 2021-08-01 20:23
> 
> 
> This is not a `ws` issue. The server is responding with 403 which means that access is forbidden. You probably need to add a `Cookie` or `Authorization` header. See what headers are sent in the browser. Also make sure you are actually using `ws`. `websocket` and `ws` are two different modules.

I am using all required headers, wich are sent by browser.  Also, I am using correct package. Problem is still the same.

**Comment by lpinca** [comment] 2021-08-02 07:06
Did you also add the same `User-Agent` header? I'm sorry but I can't help you without a reproducible example and I can't establish a WebSocket connection to `wss://live-arena-rjsqbe.agar.io/?party_id=GPUBAM` from a browser.

**Comment by car1ot** [comment] 2021-08-02 09:01
> 
> 
> Did you also add the same `User-Agent` header? I'm sorry but I can't help you without a reproducible example and I can't establish a WebSocket connection to `wss://live-arena-rjsqbe.agar.io/?party_id=GPUBAM` from a browser.

You need to enstablish connection from domain https://agar.io . Maybe some errors with Origin header? Exactly, I am using the same User-Agent.

**Comment by lpinca** [comment] 2021-08-02 09:17
The WebSocket constructor only works on `ws:` and `wss:` URLs . Please write the URL where the WebSocket connection is established is the browser.

**Comment by car1ot** [comment] 2021-08-02 10:35
> 
> 
> The WebSocket constructor only works on `ws:` and `wss:` URLs . Please write the URL where the WebSocket connection is established is the browser.

I am using `wss:` exactly. What is the problem?

**Comment by lpinca** [comment] 2021-08-02 12:58
> Please write the URL where the WebSocket connection is established is the browser.

**Comment by car1ot** [comment] 2021-08-02 13:04
> 
> 
> > Please write the URL where the WebSocket connection is established in the browser.

agar.io may close servers after some time.
The fresh link (if it will work when you try) wss://live-arena-12cowy4.agar.io/?party_id=4DA458

If link don't work, try to catch the link in the browser inspector > network > websocket connection.
And try to make new WebSocket(url) with this link from browser, and after from node.js with same headers, as in browser

**Comment by trasherdk** [comment] 2021-08-02 14:41
Opening agar.io in Firefox makes all warning-lights go to red. Ad blockers and tracking blockers are working overtime :laughing:

**Comment by lpinca** [comment] 2021-08-02 15:11
@car1ot I don't know, I guess cloudflare uses some trick to detect browser usage. Anyway I also get 403 with https://github.com/vi/websocat so it's not a `ws` issue. I'm closing this. Discussion can continue if needed.

**Closed by lpinca** 2021-08-02 15:11 UTC

**Comment by felixvonderladen** [comment] 2021-10-30 17:23
I know this Issue isn't related to ws at all, but I ran into the same error but can't find anything on the Internet about it. @car1ot did you ever fixed this issue?

**Comment by lpinca** [comment] 2021-10-30 17:57
@felixvonderladen they probably use fingerprinting for web clients. See https://www.cloudflare.com/products/bot-management/ and https://research.google/pubs/pub45581/.

**Comment by felixvonderladen** [comment] 2021-10-31 11:02
I'm not really sure if they do. What I tested was making a WebSocket connection on the same website, and It worked just fine. Then I tried it on Postman and changed most of the headers to match the connection on the website. It connected, but It gave me a 403 error. I don't know if the problem is from Postman, so I tried it in JavaScript with ws, but I couldn't change the origin. And now I'm stuck at this point. Is there someway to change the origin of the WebSocket in ws?

**Comment by lpinca** [comment] 2021-10-31 16:15
You can use any headers you want with the `headers` option as show in the issue decription.

**Comment by flaviut** [comment] 2022-02-21 18:42
Looks like Cloudflare uses [SSL client fingerprinting to do this blocking](https://developers.cloudflare.com/bots/concepts/ja3-fingerprint).

That pretty much means your options are:

- figure out how to reproduce a fingerprint that cloudflare allows through (good luck!)
- use a different way of connecting to your websocket (not this library or any other NodeJS thing)
- contact Cloudflare/your site admin to add this client to the allowed list

Sorry to keep going off-topic, but hopefully this is a definitive answer to this problem.

**Comment by lpinca** [comment] 2022-02-21 19:16
You can try to shuffle the default ciphers. See https://httptoolkit.tech/blog/tls-fingerprinting-node-js/.

**Comment by JhonatanRian** [comment] 2024-03-25 03:49
Has anyone found a solution to this problem? I have the same problem but for another websocket.

**Comment by myweorld** [comment] 2024-04-22 13:30
same problem, any solve?
