### ISSUE TITLE
terminate() doesnt terminate instantly

### ISSUE THREAD

**Issue by cenullum** [websockets/ws#2209] opened 2024-03-17 20:53 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

I'm wanted to add rate limiter with https://www.npmjs.com/package/rate-limiter-flexible then terminate function seems doesnt terminate ws instantly then made my own rate limiter however same result. After limit request of client reached server still can receives request from client.

### ws version

7.5.9

### Node.js Version

v16.16.0

### System

    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 19.62 GB / 29.88 GB

### Expected result

I expected to not receive another requests after 50 limit in the video. So I wanted dos2 result but got dos

### Actual result

After terminate() I'm getting 300 more requests from client. I recorded a video and made a sample project

### Attachments

![resim](https://github.com/websockets/ws/assets/57962685/be486d59-d45e-40c9-a5fe-1f24d1a88e02)
when cpu isnt that much busy, invalid requests count increase
while recording it was less
when delaying request it instantly terminates (which is dos2 in the video)
https://youtu.be/4f6QQEHaHB8 
[sample.zip](https://github.com/websockets/ws/files/14628818/sample.zip)

**Comment by lpinca** [comment] 2024-03-18 20:35
`websocket.terminate()` destroys the underlying socket. If the there is buffered data that data is read and then the `'close'` event is emitted. Buffered data is not discarded by design.

**Comment by cenullum** [comment] 2024-03-19 06:18
Is there a way to delete buffered data manually or can limit buffered data count or longer polling interval?

**Comment by lpinca** [comment] 2024-03-19 11:55
> Is there a way to delete buffered data manually or can limit buffered data count or longer polling interval?

No, the amount of buffered data is defined by https://nodejs.org/api/stream.html#readablereadablehighwatermark but you can't discard it.

**Comment by FabioZan86** [comment] 2024-03-19 18:32
> `websocket.terminate()` destroys the underlying socket. If the there is buffered data, that data is read and then the `'close'` event is emitted. Buffered data is not discarded by design.

@lpinca I know it's not the right place, but I couldn't create a problem in ws (it's disabled). Could you help me here: https://stackoverflow.com/questions/78188657/client-does-not-connect-to-websocket-server Gracias.

**Comment by cenullum** [comment] 2024-03-20 14:39
@lpinca Is there a way to artificially delay adding data to the buffer? If there is any other recommendation I'm listening

**Comment by lpinca** [comment] 2024-03-20 16:05
No, that's how Node.js streams work. If you don't care about the the messages received after calling `websocket.terminate()`, you can remove the listener for the `'message'` event.

**Comment by lpinca** [comment] 2024-03-21 19:39
I'm closing this as answered.

**Closed by lpinca** 2024-03-21 19:39 UTC
