### ISSUE TITLE
PING sent from server does not result in PONG on server

### ISSUE THREAD

**Issue by cadorn** [websockets/ws#2258] opened 2024-10-19 16:57 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

The server initiated ping/pong as documented in README is not working: https://github.com/websockets/ws?tab=readme-ov-file#how-to-detect-and-close-broken-connections

Sample code provided below.

With `node v23.0.0` I get
```
send ping to client
received ping on client
send ping to client
received ping on client
...
```

With `bun v1.1.31` I get:
```
send ping to client
send ping to client
...
```

Code:
```
const WebSocket  = require('ws')

const main = async () => {

    function heartbeat() {
        console.log('received pong on server')
        this.isAlive = true;
    }

    const wss = new WebSocket.Server({ port: 8080 });

    wss.on('connection', function connection(ws) {
        ws.isAlive = true;
        ws.on('error', console.error);
        ws.on('pong', heartbeat);
    });

    const interval = setInterval(function ping() {
        wss.clients.forEach(function each(ws) {
            // if (ws.isAlive === false) return ws.terminate();
        
            ws.isAlive = false;
            console.log('send ping to client')
            ws.ping();
        });
    }, 100);

    wss.on('close', function close() {
        console.log('close server')
        clearInterval(interval);
    });


    function heartbeat() {
        clearTimeout(this.pingTimeout);
        
        // Use `WebSocket#terminate()`, which immediately destroys the connection,
        // instead of `WebSocket#close()`, which waits for the close timer.
        // Delay should be equal to the interval at which your server
        // sends out pings plus a conservative assumption of the latency.
        this.pingTimeout = setTimeout(() => {
            this.terminate();
        }, 30000 + 1000);
    }

    const client = new WebSocket('ws://localhost:8080/');

    client.on('error', console.error);
    client.on('open', heartbeat);
    client.on('ping', () => {
        console.log('received ping on client')
        heartbeat()
    });
    client.on('close', function clear() {
        console.log('close client')
        clearTimeout(this.pingTimeout);
    });

}

main()
```

### ws version

8.18.0

### Node.js Version

v23.0.0

### System

 System:
    OS: macOS 14.6
    CPU: (11) arm64 Apple M3 Pro
    Memory: 1.19 GB / 36.00 GB
    Shell: 5.9 - /bin/zsh

### Expected result

I expect to see `received pong on server` logged.

### Actual result

`received pong on server` is never logged.
i.e. the server is not receiving the `pong` response from client.

**Comment by lpinca** [comment] 2024-10-20 06:00
The problem is in you code, you have two `heartbeat` functions. Only the redefined one is used.

**Comment by cadorn** [comment] 2024-10-20 15:16
You are totally right. Not sure how I missed that. Thanks!
Changing the name fixes it for `node`.

It does NOT fix it for `bun`.

**Comment by lpinca** [comment] 2024-10-20 18:17
> It does NOT fix it for `bun`.

It's not a Node.js / ws problem. Feel free to open an issue in the `bun` repository.

**Comment by lpinca** [comment] 2024-10-20 19:00
I'm closing this as answered.

**Closed by lpinca** 2024-10-20 19:00 UTC
