### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by whes1015** [websockets/ws#2055] opened 2022-06-05 14:57 UTC
### Is there an existing issue for this?

- [X] I've searched for any related issues and avoided creating a duplicate issue.

### Description

```
RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (C:\Users\whes1015\node_modules\ws\lib\receiver.js:189:14)
    at Receiver.startLoop (C:\Users\whes1015\node_modules\ws\lib\receiver.js:136:22)
    at Receiver._write (C:\Users\whes1015\node_modules\ws\lib\receiver.js:83:10)
    at writeOrBuffer (node:internal/streams/writable:390:12)
    at _write (node:internal/streams/writable:331:10)
    at Receiver.Writable.write (node:internal/streams/writable:335:10)
    at Socket.socketOnData (C:\Users\whes1015\node_modules\ws\lib\websocket.js:1231:35)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9) {
  code: 'WS_ERR_UNEXPECTED_RSV_1',
  [Symbol(status-code)]: 1002
}
```

### ws version

8.7.0

### Node.js Version

17.3.0

### System

```
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 16.23 GB / 39.91 GB
```

**Comment by lpinca** [comment] 2022-06-05 15:27
Add a listener for the `'error'` event to the `WebSocket` instance.

**Comment by lpinca** [comment] 2022-06-05 15:28
Duplicate of https://github.com/websockets/ws/issues/2019.

**Closed by lpinca** 2022-06-05 15:28 UTC
