### ISSUE TITLE
Unable to resolve module `url` from [path]/node_modules/ws/lib/WebSocket.js

### ISSUE THREAD

**Issue by mosesmc52** [websockets/ws#1037] opened 2017-03-08 17:29 UTC
I created a new React Native v 0.42.0 project with the following libraries installed. 
react-native-ble: 1.0.8
bleat: 0.1.1

I load these libraries, one which I assume uses websocket v 1.1.2. I receive this error. 

==============================================
The development server returned error code: 500

URL: http://localhost:8081/index.android.bundle?platform=android&dev=true&hot=false&minify=false

Unable to resolve module url from [path]/node_modules/ws/lib/WebSocket.js
Module does not exist in the module map or in these directories
/node_modules/

===============================

Would you have any reason why this issue is occurring?

**Comment by lpinca** [comment] 2017-03-08 17:43
Hi,
I guess the error is raised by this [`require()`](https://github.com/websockets/ws/blob/98f0d21f49c0d2c2daa175f840bc36c44d2729b1/lib/WebSocket.js#L9) but I have no idea why.

I doubt the problem is in `ws`.

**Comment by lpinca** [comment] 2017-03-09 09:03
Closing this as I think it is an external issue.

**Closed by lpinca** 2017-03-09 09:03 UTC
