### ISSUE TITLE
Setting a proxy

### ISSUE THREAD

**Issue by Pimeau** [websockets/ws#690] opened 2016-02-25 20:26 UTC
Hello,

Sorry if I'm duplicating an issue, but I could not find something similar. I need to create a web socket that uses an HTTP proxy. I tweaked the WebSocket.js file directly with no success. Some non-authoritative sources I found said the way to do it was in the requestOptions variable:

`var requestOptions = {
    port: 8080,
    host: 'OUR_PROXY',
    headers: {
      'Connection': 'Upgrade',
      'Upgrade': 'websocket',
      'Host': headerHost,
      'Sec-WebSocket-Version': options.value.protocolVersion,
      'Sec-WebSocket-Key': key
    }
  };`

We need this because we're behind a corporate proxy we have no control over.
Any advice would be highly appreciated.

**Comment by alexjwong** [comment] 2016-03-14 16:36
@Pimeau You can use the https-proxy-agent package (https://www.npmjs.com/package/https-proxy-agent) to route websocket requests through a proxy. (I just tried and succeeded through my corporate proxy).

**Comment by lpinca** [comment] 2016-11-13 16:42
Possible duplicate of #559.

**Closed** 2017-01-27 09:50 UTC
