### ISSUE TITLE
Websocket RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear

### ISSUE THREAD

**Issue by ztnark** [websockets/ws#1354] opened 2018-04-06 18:27 UTC
- [ x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description

I'm using ws as a client in my node application, and when I attempt to connect to the host, the connection is closed with the error 'Websocket RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear'.

It is worth noting that the connection is successful to a different host, but I believe this is a client issue?

It's also worth noting that faye-websocket functions correctly in the same situation.

#### Reproducible in:

version: 5.1.1
Node.js version(s): 8.9.4
OS version(s): Windows 7 Professional v6.1 (build 7601)

#### Steps to reproduce:

1. Run the following code inside of a Node Application:

```
const WebSocket = require('ws')

const ws = new WebSocket('ws://site:8765/ws')

ws.on('message', data => {
  console.log(data)
})
ws.on('error', err => { console.log(err) })
ws.on('close', () => { console.log('close') })
```

**Comment by lpinca** [comment] 2018-04-06 20:45
It might be a bug that has been recently fixed in https://github.com/nodejs/node/pull/17806 but I think not yet backported to Node.js 8.

Try to use Node.js 9. If the issue persist please post the received data on the socket. You can do that by attaching a listener for the `'data'` event on the internal socket.

```js
const ws = new WebSocket('ws://site:8765/ws');

ws.on('open', function () {
  ws._socket.on('data', console.log);
});
```

**Comment by lpinca** [comment] 2018-04-10 19:39
@ztnark any update?

**Comment by jeroenvollenbrock** [comment] 2018-04-11 21:38
Should be resolved in the next Node.js 8 version as well, presumably 8.11.2 :)

**Comment by ztnark** [comment] 2018-04-11 21:39
Sorry, haven't had a chance to take a look yet. I'll give it a shot
tomorrow.

**Comment by ztnark** [comment] 2018-04-12 21:27
@lpinca, good news. I can confirm that upgrading to Node.js 9 (11.1) fixes this issue. I can also test on 8.11.2, when released. Thank you.

**Comment by lpinca** [comment] 2018-04-13 05:07
I'm closing then. Please reopen if the issue persists.
Thank you.

**Closed by lpinca** 2018-04-13 05:07 UTC

**Comment by danielmurray** [comment] 2018-06-06 00:44
Howdy all,

As of today, electron is currently running node@8.9.3 in it's main process. So the solution of upgrading the local node version is not a viable option for electron app developers. 

If you are experiencing this issue while attempting to create a web socket connection in the electron main process I would switch to [WebSocket-Node](https://github.com/theturtle32/WebSocket-Node). This library seems to be unaffected by the bug in node<8.11.2

Dan

**Comment by Turbo87** [comment] 2018-07-02 19:47
FWIW I'm hitting the same issue with Node 10 too, but I would expect that this is a server-side issue, with a server sending a frame with those flags that should actually not be set.

**Comment by ashleybrener** [comment] 2018-07-12 18:35
I am experiencing the same issue on node v8.11.3 and v10.6.0

**Comment by lpinca** [comment] 2018-07-12 18:50
Are you getting it on the client or server? If it is on the server it's possible that a malicious client is sending faulty frames intentionally.

If it's on client instead, you can try to log the received data

```js
ws._socket.prependListener('data', console.log);
```

**Comment by ashleybrener** [comment] 2018-07-12 19:55
@lpinca thank you for the fast response. This advice was most helpful, the error is on the client and I added the listener as you suggested.

This led me to find what I think could be the cause. The server (which also uses ws) is aborting the handshake based on a certain condition (a custom override in our app) using a copy of the [abortHandshake](https://github.com/websockets/ws/blob/master/lib/websocket-server.js#L347) function.

And so it is writing the following data to the socket:

```http
HTTP/1.1 401 Unauthorized
Connection: close
Content-type: text/html
Content-Length: 12

Unauthorized
```

... which the client receives and throws the RangeError on. Does this make sense?

**Comment by lpinca** [comment] 2018-07-12 20:03
No not really, that should not trigger the [`'upgrade'`](https://nodejs.org/api/http.html#http_event_upgrade) event on the client, so you should only get an error with a message like "Unexpected server response...".

**Comment by lpinca** [comment] 2018-07-12 20:05
Are you able to create a reproducible test case? If so please do it so I can investigate.

**Comment by lpinca** [comment] 2018-07-12 20:10
Or are you writing that on the socket after the [101 response](https://github.com/websockets/ws/blob/fc957939460cd0c461618bef4c6d59a9b5a4b90e/lib/websocket-server.js#L243-L248)? In this case, yes, it makes sense.

**Comment by ashleybrener** [comment] 2018-07-12 20:17
Its quite possible this is after the 101, my class inherits from WebSocket.Server and overrides the handleUpgrade function to inspect the client IP address and abort the handshake if unrecognized.

**Comment by lpinca** [comment] 2018-07-12 20:24
You probably have your own reasons to do that (overriding `handleUpgrade`) but the [`verifyClient`](https://github.com/websockets/ws/blob/master/doc/ws.md#new-websocketserveroptions-callback) can be used for this.

**Comment by marcellillyes** [comment] 2019-12-12 15:41
Hi there, I am trying to send data from a client(Arduino) to a server(Node.js Express on my laptop) through websocket using the Arduino Websocket client library and the ws npm package.
I get the handshake and the initial data transfer going but after like 3/4 seconds the data transfer starts to lag and gives me an error after a while:

{ RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (C:\Users\illye\IdeaProjects\webserver\node_modules\ws\lib\receiver.js:167:14)
    at Receiver.startLoop (C:\Users\illye\IdeaProjects\webserver\node_modules\ws\lib\receiver.js:127:22)
    at Receiver._write (C:\Users\illye\IdeaProjects\webserver\node_modules\ws\lib\receiver.js:74:10)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Receiver.Writable.write (_stream_writable.js:299:11)
    at Socket.socketOnData (C:\Users\illye\IdeaProjects\webserver\node_modules\ws\lib\websocket.js:875:35)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11) [Symbol(status-code)]: 1002 }

I suspect that the data rate is too fast (2/3 ms per message) and the buffer floods on the server side and when it clears, the incoming message wont have the right bits on the right place of the websocket protocol(FIN, RSV1,RSV2,RSV3, opcode, etc....)

Do you have any experience with how much data websocket can push through or how to resolve this problem?

**Comment by tgraupmann** [comment] 2021-02-07 06:49
FYI, this issue still reproduces on both WSL2 and Windows 10 for Node v14.15.4.

I have a sample client that can crash a WS server instantly.

I'm using pretty much the minimal sample - https://github.com/tgraupmann/NodeJS_WS/blob/master/app.js

This worked fine sending JSON payloads. I'm testing a C client with binary payloads which crash the server.

Server: https://github.com/tgraupmann/NodeJS_WS/blob/master/app.js

```
C:\Public\NodeJS_WS>node app.js
events.js:292
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV2 and RSV3 must be clear
    at Receiver.getInfo (C:\Public\NodeJS_WS\node_modules\←[4mws←[24m\lib\receiver.js:171:14)
    at Receiver.startLoop (C:\Public\NodeJS_WS\node_modules\←[4mws←[24m\lib\receiver.js:131:22)
    at Receiver._write (C:\Public\NodeJS_WS\node_modules\←[4mws←[24m\lib\receiver.js:78:10)
←[90m    at writeOrBuffer (internal/streams/writable.js:358:12)←[39m
←[90m    at Receiver.Writable.write (internal/streams/writable.js:303:10)←[39m
    at Socket.socketOnData (C:\Public\NodeJS_WS\node_modules\←[4mws←[24m\lib\websocket.js:900:35)
←[90m    at Socket.emit (events.js:315:20)←[39m
←[90m    at addChunk (internal/streams/readable.js:309:12)←[39m
←[90m    at readableAddChunk (internal/streams/readable.js:284:9)←[39m
←[90m    at Socket.Readable.push (internal/streams/readable.js:223:10)←[39m
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (C:\Public\NodeJS_WS\node_modules\←[4mws←[24m\lib\websocket.js:805:13)
←[90m    at Receiver.emit (events.js:315:20)←[39m
←[90m    at emitErrorNT (internal/streams/destroy.js:106:8)←[39m
←[90m    at emitErrorCloseNT (internal/streams/destroy.js:74:3)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:80:21)←[39m {
  [←[32mSymbol(status-code)←[39m]: ←[33m1002←[39m
}

C:\Public\NodeJS_WS>node --version
v14.15.4
```

**Comment by lpinca** [comment] 2021-02-07 06:56
`'error'` events must be handled.

```js
wss.on('connection', function(ws) {
  ws.on('error', console.error);
});
```

**Comment by tgraupmann** [comment] 2021-02-07 07:00
> `'error'` events must be handled.
> 
> ```js
> wss.on('connection', function(ws) {
>   ws.on('error', console.error);
> });
> ```

That was it. Just needed an error handler to avoid crashing. Thanks!

**Comment by crisdosyago** [comment] 2022-10-23 05:17
I'm seeing this in node v18.8.0 when connecting from a Safari client (latest Safari, latest iOS 16.3). Hard to reproduce: it does not happen on first connect, but after reloading the page. Yet after a couple of reloads it works, then breaks again. 

Sorry could not provide more details right now. Weird bug...don't even know if it comes from the ws library, just posting here because I found this issue while searching for answers

**Comment by crisdosyago** [comment] 2022-10-23 05:18
> > `'error'` events must be handled.
> > ```js
> > wss.on('connection', function(ws) {
> >   ws.on('error', console.error);
> > });
> > ```
> 
> That's all it was. The server just needed an error handler to avoid crashing. And now it logs errors without exiting. Thanks!

@tgraupmann I have an error handler, but my websocket closes after showing  thisRangeError.

**Comment by lpinca** [comment] 2022-10-23 17:35
@crisdosyago the spec specifically says that

> the receiving endpoint MUST Fail the WebSocket Connection.

I'm strongly against adding a `strictProtocol` option or anything like that. A lot of `WebSocket` implementation do not even inform the user of the error. They just close the connection silently.

Also, it is not the first time that Safari introduces bugs like this. See https://github.com/websockets/ws/issues/1922.

**Comment by crisdosyago** [comment] 2022-10-23 17:46
Understood @lpinca I know you don't want to dirty this library with irregularities or tolerances of those. Sounds like that's the right choice. Thank you for your information, including on the other bug (how interesting! that Safari!), and thanks for the amazing work on this great library!

**Comment by crisdosyago** [comment] 2022-10-23 18:01
Understood @lpinca I know you don't want to dirty this library with irregularities or tolerances of those. Thank you for your consideration of this idea, it sounds like you've given this some serious thought and like you believe it's the right choice to not include here because doing so would mean your library would no longer meet the standard of quality you're trying to keep. I trust you. Thank you for your information--including on the other bug (how interesting! that Safari!)--and thanks for the amazing work on this great library!

**Comment by lpinca** [comment] 2022-12-08 18:13
> Probably `ws` error handler not working properly or removed?

Yes, make sure that the `'error'` event listener is not removed before the `'close'` event is emitted.

**Comment by misi** [comment] 2022-12-12 08:55
Yes removed error handler in tear down, and it caused it. Thanks!

**Comment by marcolanaro** [comment] 2022-12-16 17:58
@misi Can you please provide a code example or reference for this use case?

**Comment by atanasyordanov21** [comment] 2023-06-19 19:26
I was also struggling with such an issue for some time. Tried several different web socket clients, and always the same. Then I started breaking down my code, and it turned out that the following line was causing the issue in my case:
`request.socket.setEncoding("utf8");`
`request` comes from here:
```
wss.on('connection', (ws, request) => {
...
});

```

**Comment by smallCF** [comment] 2023-07-13 14:58
Hello author;

Using node as a program to use ws, will inconsistent time between the user and server in the same time zone result in the issue of RSV2 and RSV3 must be clear?

The node service on my end is installed using the Docker method
